### ISSUE TITLE
[🐞] exports is not defined 

### ISSUE THREAD

**Issue by hjw0968** [electron-vite/electron-vite-vue#103]
#### What did I do

```typescript
renderer vite.config.ts

// 这个位置, 按你的样例更新了原先的脚手架
// import electron from 'vite-plugin-electron/renderer' 0.2.1
    plugins: [
        vue(),
        electron(),
        resolve(
            /**
             * Here you can specify other modules
             * 🚧 You have to make sure that your module is in `dependencies` and not in the` devDependencies`,
             *    which will ensure that the electron-builder can package it correctly
             */
            {
                // If you use electron-store, this will work
               // 'electron-store': 'const Store = require("electron-store"); export default Store;',
            }
        ),
    ],

// 原来是
    plugins: [
        vue(),
        resolveElectron(
            /**
             * Here you can specify other modules
             * 🚧 You have to make sure that your module is in `dependencies` and not in the` devDependencies`,
             *    which will ensure that the electron-builder can package it correctly
             * @example
             * {
             *   'electron-store': 'const Store = require("electron-store"); export default Store;',
             * }
             */
        ),
    ], 

/**
 * For usage of Electron and NodeJS APIs in the Renderer process
 * @see https://github.com/caoxiemeihao/electron-vue-vite/issues/52
 */
export function resolveElectron(
    resolves: Parameters<typeof resolve>[0] = {}
): Plugin {
    const builtins = builtinModules.filter((t) => !t.startsWith('_'))

    /**
     * @see https://github.com/caoxiemeihao/vite-plugins/tree/main/packages/resolve#readme
     */
    return resolve({
        electron: electronExport(),
        ...builtinModulesExport(builtins),
        ...resolves,
    })

    function electronExport() {
        return `
/**
 * For all exported modules see https://www.electronjs.org/docs/latest/api/clipboard -> Renderer Process Modules
 */
const electron = require("electron");
const {
  clipboard,
  nativeImage,
  shell,
  contextBridge,
  crashReporter,
  ipcRenderer,
  webFrame,
  desktopCapturer,
  deprecate,
} = electron;

export {
  electron as default,
  clipboard,
  nativeImage,
  shell,
  contextBridge,
  crashReporter,
  ipcRenderer,
  webFrame,
  desktopCapturer,
  deprecate,
}
`
    }

    function builtinModulesExport(modules: string[]) {
        return modules
            .map((moduleId) => {
                const nodeModule = require(moduleId)
                const requireModule = `const M = require("${moduleId}");`
                const exportDefault = `export default M;`
                const exportMembers =
                    Object.keys(nodeModule)
                        .map((attr) => `export const ${attr} = M.${attr}`)
                        .join(';\n') + ';'
                const nodeModuleCode = `
${requireModule}

${exportDefault}

${exportMembers}
`

                return {[moduleId]: nodeModuleCode}
            })
            .reduce((memo, item) => Object.assign(memo, item), {})
    }
}

// 这里没去动它, 因为我希望运行环境保持隔离
    webPreferences: {
      preload: join(__dirname, '../preload/index.cjs'),
      nodeIntegration: true,// 使用false
      contextIsolation: false, // 使用true
    },
```

#### What happened

直接按你当前脚手架的配置, dev是没有问题的, 但是打包之后, 入口文件就会出现 exports is not defined 
似乎是什么模块没有正确打包

#### Expected

我不确定这是不是一个BUG, 或者说使用'vite-plugin-electron/renderer'时还需要一些额外的配置, 看了源码, 好像也没什么需要配置的, 旧脚手架里的export function resolveElectron 内的方法也被你拆分到vite-plugin-electron中了

#### Environment

- OS: macOS 12.3.1 / windows11
- electron-vue-vite version (or commit hash), e.g. v1.0.0

#### More detail
```typescript

// import resolve from 'vite-plugin-resolve' 2.0.1
// 目前我是去掉'vite-plugin-electron/renderer'
// 按之前旧版本脚手架的 builtinModulesExport 和 electronExport 修改后使用, 这样做可以正常打包运行
    plugins: [
        vue(),
        resolve({
            electron: electronExport(), // 
            ...builtinModulesExport()
        }),
    ],
```

**Comment by caoxiemeihao** [comment]
Mac OS 下也有这个问题么？
这个问题奇奇怪怪的，之前也碰到过几次。

**Comment by hjw0968** [comment]
> Mac OS 下也有这个问题么？ 这个问题奇奇怪怪的，之前也碰到过几次。

打包之后都有这个问题, 并且肉眼可见的体积变大了至少3MB, 不知道消耗到哪去了, 现在就是去掉'vite-plugin-electron/renderer', 只使用
```typescript
        resolve({
            electron: electronExport(), // 
            ...builtinModulesExport()
        }),
```
不会有问题, 并且安装包体积也会缩小, 应该是跟之前 "vite-plugin-resolve": "1.6.1", 原先的脚手架效果一致

**Comment by caoxiemeihao** [comment]
插件代码不可能有 3M 加上源码才 55kB  
electron 版本不同体积会不一样

**Comment by caoxiemeihao** [comment]
我这打包看不出问题来，实在不行你手动修复下 `exports`  
```diff
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline';" />
    <title>Vite App</title>
+   <script>const exports = module.exports;</script>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
```

**Comment by hjw0968** [comment]
```json
// package.json

"dependencies": {
    "@electron/remote": "^2.0.8",
    "ant-design-vue": "^3.1.1",
    "axios": "^0.26.1",
    "cnchar": "^3.0.6",
    "cos-js-sdk-v5": "^1.3.5",
    "dayjs": "^1.11.0",
    "dexie": "^3.2.1",
    "electron-log": "^4.4.6",
    "electron-updater": "^4.6.5",
    "howler": "^2.2.3",
    "js-base64": "^3.7.2",
    "mitt": "^3.0.0",
    "nanoid": "^3.3.2",
    "pinia": "^2.0.13",
    "pinia-plugin-persist": "0.0.93",
    "protobufjs": "^6.11.2",
    "qrcode.vue": "^3.3.3",
    "textarea-caret": "^3.1.0",
    "ts-md5": "^1.2.11",
    "vue-cropper": "^1.0.2",
    "vue-router": "^4.0.14",
    "vue-virtual-scroller": "^2.0.0-alpha.1",
    "vue3-click-away": "^1.2.4",
    "vue3-lazy": "^1.0.0-alpha.1"
  },
  "devDependencies": {
    "@ant-design/icons-vue": "^6.0.1",
    "@types/howler": "^2.2.7",
    "@vitejs/plugin-vue": "^2.3.1",
    "electron": "^18.0.3",
    "electron-builder": "^22.14.5",
    "electron-devtools-installer": "^3.2.0",
    "sass": "^1.50.0",
    "typescript": "^4.6.3",
    "vite": "^2.9.1",
    "vite-plugin-resolve": "2.0.1",
    "vue": "^3.2.29",
    "vue-tsc": "^0.33.9"
  },
```

> 我这打包看不出问题来，实在不行你手动修复下 `exports`
> 
> ```diff
> <!DOCTYPE html>
> <html lang="en">
>   <head>
>     <meta charset="UTF-8" />
>     <link rel="icon" href="/favicon.ico" />
>     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>     <meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline';" />
>     <title>Vite App</title>
> +   <script>const exports = module.exports;</script>
>   </head>
>   <body>
>     <div id="app"></div>
>     <script type="module" src="/src/main.ts"></script>
>   </body>
> </html>
> ```

```typescript
// renderer/vite.config.ts
import {builtinModules} from 'module'
import {defineConfig} from 'vite'
import vue from '@vitejs/plugin-vue'
import resolve from 'vite-plugin-resolve'
import pkg from '../../package.json'
import {resolve as pathResolve} from "path";

// https://vitejs.dev/config/
export default defineConfig({
    mode: process.env.NODE_ENV,
    root: __dirname,
    plugins: [
        vue(),
        resolve({
            electron: electronExport(),
            ...builtinModulesExport()
        }),
    ],
    // 别名
    resolve: {
        alias: {
            '@': pathResolve(__dirname, './src')//设置别名
        }
    },
    // 全局css
    css: {
        preprocessorOptions: {
            scss: {
                // 全局的scss ，跨域放多个，例如：主题的变量，和一些混合等
                additionalData: `@import "@/assets/styles/theme.scss";`,
                charset: false // 避免vite build时出现css charset冗余警告
            }
        }
    },
    base: './',
    build: {
        sourcemap: process.env.NODE_ENV == 'development',
        outDir: '../../dist/renderer',
        chunkSizeWarningLimit: 1500,
        emptyOutDir: true
    },
    server: {
        host: pkg.env.VITE_DEV_SERVER_HOST,
        port: pkg.env.VITE_DEV_SERVER_PORT,
    },
})

function electronExport() {
    return `
const electron = require("electron");
const {
  clipboard,
  nativeImage,
  shell,
  contextBridge,
  crashReporter,
  ipcRenderer,
  webFrame,
  desktopCapturer,
  deprecate,
} = electron;

export {
  electron as default,
  clipboard,
  nativeImage,
  shell,
  contextBridge,
  crashReporter,
  ipcRenderer,
  webFrame,
  desktopCapturer,
  deprecate,
}
`
}

function builtinModulesExport() {

    const builtins = builtinModules.filter((t) => !t.startsWith('_'))

    return builtins
        .map((moduleId) => {
            const nodeModule = require(moduleId)
            const requireModule = `const M = require("${moduleId}");`
            const exportDefault = `export default M;`
            const exportMembers =
                Object.keys(nodeModule)
                    .map((attr) => `export const ${attr} = M.${attr}`)
                    .join(';\n') + ';'
            const nodeModuleCode = `
${requireModule}
${exportDefault}
${exportMembers}
`
            return {[moduleId]: nodeModuleCode}
        })
        .reduce((memo, item) => Object.assign(memo, item), {})
}
```
我是这么缝合解决的, main和preload内的还是之前的配置, 我看vite-plugin-electron/renderer的主要目的还是在渲染进程中使用node, 那也用不到它, 继续采用contextBridge方式

```JavaScript
// main/index.ts
// 关闭默认菜单
Menu.setApplicationMenu(null)
// 创建窗口  
win = new BrowserWindow({
    width: 300,// 窗口初次开启时的宽度
    height: 400,// 窗口初次开启时的高度
    titleBarStyle: process.platform !== 'darwin' ? 'hidden' : "hiddenInset",// windows不能完美支持hiddenInset, 使用自定义最小化关闭按钮
    center: false,
    skipTaskbar: false, // 是否隐藏windows任务栏图标
    autoHideMenuBar: true,// 隐藏windows窗口内的顶部菜单
    maximizable: false,// 禁止最大化
    webPreferences: {
        webSecurity: !isDev,
        contextIsolation: true,// 上下文隔离
        preload: join(__dirname, '../preload/index.cjs')
    },
})

// preload/index.ts
contextBridge.exposeInMainWorld("electron", {
  fs: fs,// 文件系统http://nodejs.cn/api/fs.html
  removeLoading: removeLoading,// 移除窗口加载动画
  ipcRenderer: _ipcRenderer,// electron.ipcRenderer,
// ......
})
```
现在没有问题就没有深究了, 包体积那个问题我看了, 还是electron-builder打包时的问题导致asar体积异常增大, 按目前这个用法, 没有发生问题
不好意思, 本issues可以关闭了

**Comment by undancer** [comment]
这个问题我也遇到了，具体复现的方式好像是当使用vite-router**懒加载**的时候，release打包就会报这个错误。我试着提供一个最简复现例子吧。

**Comment by undancer** [comment]
BUG复现地址在这里：https://github.com/undancer/electron-vite-vue-bug

不使用懒加载好像没问题

**Comment by undancer** [comment]
> > Mac OS 下也有这个问题么？ 这个问题奇奇怪怪的，之前也碰到过几次。
> 
> 打包之后都有这个问题, 并且肉眼可见的体积变大了至少3MB, 不知道消耗到哪去了, 现在就是去掉'vite-plugin-electron/renderer', 只使用
> 
> ```ts
>         resolve({
>             electron: electronExport(), // 
>             ...builtinModulesExport()
>         }),
> ```
> 
> 不会有问题, 并且安装包体积也会缩小, 应该是跟之前 "vite-plugin-resolve": "1.6.1", 原先的脚手架效果一致

打包后体积肉眼可见的变大了，原因是dist目录里存有历次编译产生的文件，而打包是打包整个dist文件夹，也就是说打包时会包含一些用不到的旧编译文件进去。我也是把asar:false之后才发现的。

**Comment by undancer** [comment]
并且当在根目录下新建build文件夹（这是electron-builder默认的electron app icon放置的位置），并添加icon.png文件时，再打包，会在release文件夹下多出一个名为${name}空的文件夹

**Comment by caoxiemeihao** [comment]
@undancer Hey! 👋
`remove build.emptyOutDir` https://github.com/electron-vite/electron-vite-vue/commit/eb0753ea7274311ac8bdafe1a402728170f0a8dc 是我当时偶然发现默认情况下 emptyOutDir 是开启的

https://github.com/vitejs/vite/blob/83d32d965e3abd78fe390e347923e68dfb6de773/packages/vite/src/node/build.ts#L155

```ts
  /**
   * Empty outDir on write.
   * @default true when outDir is a sub directory of project root
   */
  emptyOutDir?: boolean | null
```

**Comment by undancer** [comment]
> 

如果你看了vite的源码就会发现，如果vite.config.ts里，root和build.outDir的关系不是父子文件夹的话，这个emptyOutDir是关闭的。而你的配置碰巧是这种情况。你的root是${project}/dist/renderer，outDir是${project}/packages/renderer ，而vite的源码里是判断root是否有outDir的开头。
https://github.com/vitejs/vite/blob/83d32d965e3abd78fe390e347923e68dfb6de773/packages/vite/src/node/build.ts#L584

**Comment by undancer** [comment]
https://github.com/undancer/electron-vite-vue-bug

这个项目重现了标题的问题，对应的解决方案是：
在renderer的vite.config.ts里修改配置：
```
   rollupOptions: {
            output: {
                format: 'es'
            }
        }
```
然后debug了一下yarn run build的过程，发现是你的这个插件修改了默认值。
rollup里output.format的默认值是es，而你在插件里将它修改为了cjs。
我觉得你可能要重新思考一下如何修改那个插件

https://github.com/electron-vite/vite-plugin-electron/blob/main/renderer/index.js#L37

**Comment by hjw0968** [comment]
> > > Mac OS 下也有这个问题么？ 这个问题奇奇怪怪的，之前也碰到过几次。
> > 
> > 
> > 打包之后都有这个问题, 并且肉眼可见的体积变大了至少3MB, 不知道消耗到哪去了, 现在就是去掉'vite-plugin-electron/renderer', 只使用
> > ```ts
> >         resolve({
> >             electron: electronExport(), // 
> >             ...builtinModulesExport()
> >         }),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不会有问题, 并且安装包体积也会缩小, 应该是跟之前 "vite-plugin-resolve": "1.6.1", 原先的脚手架效果一致
> 
> 打包后体积肉眼可见的变大了，原因是dist目录里存有历次编译产生的文件，而打包是打包整个dist文件夹，也就是说打包时会包含一些用不到的旧编译文件进去。我也是把asar:false之后才发现的。
> 
> 可以通过修改vite.config.ts来解决
> 
> ```js
> {
>   // ...
>   build: {
>        // ...
>        // https://cn.vitejs.dev/config/#build-emptyoutdir
>        emptyOutDir: process.env./* from mode option */NODE_ENV === 'production',
>        // ...
>   }
> }
> ```

> ```ts
>     build: {
>         sourcemap: process.env.NODE_ENV == 'development',
>         outDir: '../../dist/renderer',
>         chunkSizeWarningLimit: 1500,
>         emptyOutDir: true // 这个我一直是默认开启的
>     },
> ```
我这边发现的情况跟你还不太一样, 因为resolve配置的缘故

**Comment by undancer** [comment]
> > > > Mac OS 下也有这个问题么？ 这个问题奇奇怪怪的，之前也碰到过几次。
> > > 
> > > 
> > > 打包之后都有这个问题, 并且肉眼可见的体积变大了至少3MB, 不知道消耗到哪去了, 现在就是去掉'vite-plugin-electron/renderer', 只使用
> > > ```ts
> > >         resolve({
> > >             electron: electronExport(), // 
> > >             ...builtinModulesExport()
> > >         }),
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 不会有问题, 并且安装包体积也会缩小, 应该是跟之前 "vite-plugin-resolve": "1.6.1", 原先的脚手架效果一致
> > 
> > 
> > 打包后体积肉眼可见的变大了，原因是dist目录里存有历次编译产生的文件，而打包是打包整个dist文件夹，也就是说打包时会包含一些用不到的旧编译文件进去。我也是把asar:false之后才发现的。
> > 可以通过修改vite.config.ts来解决
> > ```js
> > {
> >   // ...
> >   build: {
> >        // ...
> >        // https://cn.vitejs.dev/config/#build-emptyoutdir
> >        emptyOutDir: process.env./* from mode option */NODE_ENV === 'production',
> >        // ...
> >   }
> > }
> > ```
> 
> > ```ts
> >     build: {
> >         sourcemap: process.env.NODE_ENV == 'development',
> >         outDir: '../../dist/renderer',
> >         chunkSizeWarningLimit: 1500,
> >         emptyOutDir: true // 这个我一直是默认开启的
> >     },
> > ```
> 
> 我这边发现的情况跟你还不太一样, 因为resolve配置的缘故

我提到的情况，作者也遇到了。

https://github.com/electron-vite/electron-vite-vue/issues/95#issuecomment-1089974926

你看他这张截图，很明显有脏文件，electron-build打包的时候会都包含进去。
另外你提到的情况，我的确没注意看。

**Comment by hjw0968** [comment]
> 
> 你看他这张截图，很明显有脏文件，electron-build打包的时候会都包含进去。 另外你提到的情况，我的确没注意看。如果可以的话，我倒是可以追踪一下源码，但你得提供一下复现的DEMO。

这里确定没有脏文件, 上个月刚开始转移脚手架到`electron-vite` 的时候就注意到`dist/renderer` build 后会有之前编译的文件问题, 当时还没注意到emptyOutDir的事
```json
"scripts": {
    "dev": "node scripts/watch.mjs",
    "typecheck": "vue-tsc --project packages/renderer/tsconfig.json --noEmit",
    "prebuild": "rm -rf /electron-vite-chat/dist/renderer && node scripts/build.mjs", // 这里在更早的时候 emptyOutDir 使用vite默认逻辑时, 使用了 rm 命令
    "build": "electron-builder --win",
  },
```

解决掉标题的问题之后, 就没有继续深究下去的想法和动力了😄

这个issues主要还是由 vite-plugin-electron-renderer 这个插件引出的, 去掉它
配置好 `vite-plugin-resolve resolve({
electron: xxxxxx,
...other
})` 也就没有后面的事了

怪我追新, 没有认真看那个插件的说明, 此题终结

**Comment by caoxiemeihao** [comment]
如果用户用的 npm 包只支持 cjs 格式，且用户想在 Renderer-process 中使用；  
这种情况是否考虑在 `vite-plugin-electron/renderer` 中，给 index.html 中插入 `var exports = module.exports` 修复掉这个问题呢？

**Comment by undancer** [comment]
https://github.com/electron-vite/electron-vite-vue/issues/103#issuecomment-1096940315

这个问题的答案，我也追踪到了。
现象是：electron-builder 执行后，会在release文件夹下出现一个空的${version}文件夹。
实际上这个文件夹并不是空文件夹，而是有**隐藏文件**。_macOS系统会默认将以点开头的文件设为隐藏文件。所以一开始我才没有看到。_
```bash
tree -al \$\{version\}/
${version}/
└── .icon-icns
    └── icon.icns

1 directory, 1 file
```
对应源码的位置为：
https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/platformPackager.ts#L684

electron-builder当发现有图标文件在项目中后，会调用icon ... --out ???来将图标转格式。
而这段代码的第684行，```path.resolve(this.projectDir, this.config.directories!.output!, `.icon-${outputFormat}`),```
中 this.config.directories!.output!的值，就是项目中electron-builder.json中设置的**release/${version}**。

**Comment by caoxiemeihao** [comment]
简而言之：  
In general:  

如果你需要在 Renderer-porcess 中使用 Electron、Node.js API 时候，你必须指定 `rollupOptions.output.format='cjs'`  
If you need use Electron, Node.js API in Renderer-process, you must be explicit specify [rollupOptions.output.format='cjs'](https://github.com/electron-vite/vite-plugin-electron/pull/2/commits/e6decf42164bc1e3801e27984322c41b9c2724b7)

```js
// ❌ don't work
import fs from 'fs'
import electron from 'electron'

// ✅ work normally
const fs = require('fs')
const electron = require('electron')
``` 

此外，那么你可能没必要使用 `vite-plugin-electron/renderer`  
Otherwise, you may not need to use `vite-plugin-electron/renderer`

**Comment by caoxiemeihao** [comment]
> 所以对于使用vue-router懒加载的功能依然不能正常工作。

1. Electron 应用懒加载没有意义吧。。。  
2. rollup 的 dynamic import 会直接把文件全部 bundle 到一个文件中，可能需要陪一下 manuallyChunks 切下包(没细研究过)

**Comment by undancer** [comment]
> > 所以对于使用vue-router懒加载的功能依然不能正常工作。
> 
> 1. Electron 应用懒加载没有意义吧。。。
> 2. rollup 的 dynamic import 会直接把文件全部 bundle 到一个文件中，可能需要陪一下 manuallyChunks 切下包(没细研究过)

是我搞错了，vue-router的history改为createMemoryHistory就好了。
另外，使用了0.4.2的vite-plugin-electron后，打包出来的应用会有个报错在控制台里。
```
Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Proxy.removeLoading (/Users/undancer/Projects/WebstormProjects/electron/electron-app/release/1.0.0/mac/electron-vue-vite.app/Contents/Resources/app/dist/preload/index.cjs:27:306)

```
