### ISSUE TITLE
[Help] 如何解决main进程引入依赖后，build过慢的问题

### ISSUE THREAD

**Issue by meedfine** [electron-vite/electron-vite-vue#104]
默认模板npm run dev时  build 主进程 就花200ms，编译更新时也就花100ms左右

但是当 main 引入依赖后，比如如下代码（简化版）
import installExtension from "electron-devtools-installer";
app.whenReady().then(async () => {
  installExtension("ljjemllljcmogpfapbkkighbhhppjdbg");
  createWindow();
});
会导致build就花1s以上，并且修改编译也会到500ms以上

初始模板开发可以秒开，编译也秒开，但主进程依赖引入变多后，编译就越来越慢

希望有种方法来解决这种问题
想过不用ts，用js，这样就可以直接electron执行，这样启动非常快，编译监听重启主进程也可以通过chokidar来实现，
但是这样也缺失了ts的便利

**Comment by caoxiemeihao** [comment]
将你的模块配置到 `rollupOptions.external` 中绕开构建

**Comment by meedfine** [comment]
依赖 放 dependencies ，会被排除，build快，但体积略大
依赖 放 devDependencies ，build慢，但体积小

为求速度和体积， 应该要在开发时过滤依赖，打包时不过滤依赖

**Comment by caoxiemeihao** [comment]
> 依赖 放 dependencies ，会被排除，build快，但体积略大 依赖 放 devDependencies ，build慢，但体积小
> 
> 为求速度和体积， 应该要在开发时过滤依赖，打包时不过滤依赖

开发时过滤，用 `vite-plugin-resolve`
