### ISSUE TITLE
[Bug] 路由使用懒加载第一次点击报错

### ISSUE THREAD

**Issue by michael51** [electron-vite/electron-vite-vue#105]
Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Proxy.removeLoading (E:\web\test_project\electron\electron-vite-vue-main\release\upload\win-unpacked\resources\app.asar\dist\preload\index.cjs:27:306)

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-vue/blob/52e3d0d6f7a3bb3e8f12f1ec49d4fbe0a662c726/packages/preload/loading.ts#L51

```diff
    removeLoading() {
-      document.head.removeChild(oStyle)
-      document.body.removeChild(oDiv)
+      const oStyle = document.querySelector('#app-loading-style')
+      const oDiv = document.querySelector('.app-loading-wrap')
+      oStyle && document.head.removeChild(oStyle)
+      oDiv && document.body.removeChild(oDiv)
    },
````

**Comment by michael51** [comment]
> 现在不报错了,但是异步路由,第一次点击不生效.怪事

**Comment by michael51** [comment]
> https://github.com/electron-vite/electron-vite-vue/blob/52e3d0d6f7a3bb3e8f12f1ec49d4fbe0a662c726/packages/preload/loading.ts#L51
> 
> ```diff
>     removeLoading() {
> -      document.head.removeChild(oStyle)
> -      document.body.removeChild(oDiv)
> +      const oStyle = document.querySelector('#app-loading-style')
> +      const oDiv = document.querySelector('.app-loading-wrap')
> +      oStyle && document.head.removeChild(oStyle)
> +      oDiv && document.body.removeChild(oDiv)
>     },
> ```

现在不报错了,但是异步路由,第一次点击不生效.怪事

**Comment by michael51** [comment]
现在把默认路由也改成异步。就是所有路由都使用异步加载。好像问题解决了。

**Comment by nongzhenli** [comment]
> 现在把默认路由也改成异步。就是所有路由都使用异步加载。好像问题解决了。

上天，我也遇到了这个问题。vue-router 第一次触发，无法发生URL变更，要点击第二次才行。请问您是怎么解决了呢？
（在DEV不存在此问题，仅BUILD之后遇到了.... 苦恼）

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-vue/blob/ec630d408a452f22796201c67ed5ece0fd3d977e/electron/main/index.ts#L102
