### ISSUE TITLE
[Bug] 当路由使用异步加载的情况。打包之后切换路由css没有加载。dev环境没有问题

### ISSUE THREAD

**Issue by michael51** [electron-vite/electron-vite-vue#107]
#### What did I do

当路由使用异步加载的情况。

#### What happened

打包之后切换路由css没有加载。只加载了index.css，但是路由页面的css是生成了的，只是没加载。dev环境没有问题

**Comment by caoxiemeihao** [comment]
模板没集成 router，你提的问题没有参考性；你可以写个最小的复现 Demo 放到 github 或者 StackBlitz

**Comment by michael51** [comment]
> 模板没集成 router，你提的问题没有参考性；你可以写个最小的复现 Demo 放到 github 或者 StackBlitz

其实问题就是，异步路由那个页面，比如是about.vue，打包之后会生成about.js和about.css。在首页点击about这个路由，不会加载这个about.css。导致页面样式失效。目前我暂时关闭css切割。

```
 build: {
    outDir: '../../dist/renderer',
    cssCodeSplit: false // 异步路由加载css有问题,所以暂时禁用
  },
```

**Comment by mx623303468** [comment]
> > The template can't included `vue-router`, can you provide a minimum repetition of the Demo.
> > 模板没集成 router，你提的问题没有参考性；你可以写个最小的复现 Demo 放到 github 或者 StackBlitz
> 
> In face, the async-router page, e.g. `about.vue`. After build will generated `about.js` and `about.css`. When enter about-route from Home page and can't load `about.css`, so the styles not works. At present, disabled `cssCodeSplit` and all styles will be built into `index.css` :)
> 
> 其实问题就是，异步路由那个页面，比如是about.vue，打包之后会生成about.js和about.css。在首页点击about这个路由，不会加载这个about.css。导致页面样式失效。目前我暂时关闭css切割，全部集中到index.css才行。
> 
> ```diff
>  build: {
>     // 异步路由加载css有问题,所以暂时禁用
>     // It works!
> +   cssCodeSplit: false,
>   },
> ```
TQ~
This worked for me.  I wonder if there will be a more elegant way
可以解决我的问题。不知道会不会有更优雅的方式

**Comment by caoxiemeihao** [comment]
@mx623303468 可不可以提供一个最小复现的 Demo，我可能找到了 “更优雅的方式” 😅
