### ISSUE TITLE
[Help] 请问electron想兼容win7，这套脚手架应该怎么配置

### ISSUE THREAD

**Issue by jscgq** [electron-vite/electron-vite-vue#112]
### 兼容win7
win7 版本是不是nodejs版本需要12 13，新版本是不是不行？
electron-builder 最新版本需要node14，是不是需要更改更早的版本？

**Comment by caoxiemeihao** [comment]
Vite 限制

```json
{
  "engines": {
    "node": ">=12.2.0"
  }
}
```

至于 electron-builder 你可以安装低版本

**Comment by jscgq** [comment]
感谢您的回复，我之前描述的有问题。
想问的具体是：目前用的mac，虚拟机还没装好。
开发阶段用最新版本的electron和node，是不是不能打包成兼容win7的应用，是不是需要降低版本才行？

**Comment by caoxiemeihao** [comment]
不用降低，打包出来直接放到 win7 是跑就行；有问题也是 electron 的问题
