### ISSUE TITLE
[Feature] 可不可以加个浏览器环境运行

### ISSUE THREAD

**Issue by a982246809** [electron-vite/electron-vite-vue#113]
#### Motivation

因为有,兼容浏览器端的需求

#### Detailed design

run browser 启动

**Comment by caoxiemeihao** [comment]
Node.js API 没法在浏览器中运行，强行运行在浏览器中功能缺失

**Comment by a982246809** [comment]
这个就 使用者自己去做阉割或兼容吧

**Comment by caoxiemeihao** [comment]
> 这个就 使用者自己去做阉割或兼容吧 

是的，需要阉割功能

**Comment by a982246809** [comment]
这个看使用者吧  比如说vscode也有网页版 虽然阉割掉一些功能
