### ISSUE TITLE
require is not defined     at promises.js:2:11

### ISSUE THREAD

**Issue by Miracle6** [electron-vite/electron-vite-vue#121]
大佬，求助！

1. npm run dev应用程序正常启动，但打开http://localhost:3344/会报错。
![Snipaste_2022-05-07_10-57-19](https://user-images.githubusercontent.com/61740563/167236258-8c40a3ae-f242-4a05-ad15-221760375252.png)

2. 应用打包本来会出现之前其他issue的exports is not defined。根据issue改了render/vite.config.ts。
但发现好像只能用require来引入，import会报错
![Snipaste_2022-05-07_11-45-01](https://user-images.githubusercontent.com/61740563/167236931-e261cd0f-dc4a-4300-b762-268b86e810b3.png)

3. 解决掉issue的exports is not defined，但还会出现之前别人那个问题
![Snipaste_2022-05-07_11-21-32](https://user-images.githubusercontent.com/61740563/167236979-ea07778e-d3a2-4c9e-82b7-f04ec70925cd.png)

**Comment by caoxiemeihao** [comment]
1. 🤔 打开 `http://localhost:3344/` 会报错，拜托~这是 Electron 应用；你要知道这不是个 Web 应用
2. 🐞 `require` 引入和 `import` 引入都可以正常工作，只是提供 type 导致你的 IDE 类型推导爆红；下个版本会加上 type 声明
3. 🐞 这个是业务侧的问题，改前端代码即可(连这么点排错能力都没有么？)；下个版本会加判断

**Comment by Miracle6** [comment]
好的，谢谢大佬！
