### ISSUE TITLE
[Bug] 初始化项目失败

### ISSUE THREAD

**Issue by bacy** [electron-vite/electron-vite-vue#125]
#### What did I do

初始化项目

#### What happened

Get an error.

![image](https://user-images.githubusercontent.com/5163569/167639989-28db4b41-07bf-4dc7-9821-1de7f7984d2e.png)

What is the expected result.

初始化成功

- OS: win11
- electron-vue-vite version latest
- node: v16.15.0

#### More detail

More detail like screenshot

**Comment by caoxiemeihao** [comment]
兄弟这么写提问题，你觉得我能掐指算出来你碰到了啥问题吗 🙄

**Comment by undancer** [comment]
我掐指一算，你一定是遇到了[git errno 4058](https://www.baidu.com/s?wd=git%20errno%204058)。

**Comment by caoxiemeihao** [comment]
初始化项目是依赖 git 的，不会开发人员不装 git 吧 😅
