### ISSUE TITLE
[Help] demo 项目打包完整个项目就200M，请问还能减少打包后的体积吗

### ISSUE THREAD

**Issue by enjoy-liu** [electron-vite/electron-vite-vue#131]
#### Describe the problem you Confuse

vue create 创建的项目

npm install

npm run build 

打包后的体积是202MB

请问还可以减小体积吗

还有一个小问题就是 打包后的exe 图标是如何替换

**Comment by caoxiemeihao** [comment]
推荐你用 [tauri](https://github.com/tauri-apps/tauri)

**Comment by enjoy-liu** [comment]
@caoxiemeihao 还是用electron 不是专业前端不想在折腾了，感谢解答
