### ISSUE TITLE
[Help] Can't import global sass

### ISSUE THREAD

**Issue by UnTalPeluca** [electron-vite/electron-vite-vue#133]
![image](https://user-images.githubusercontent.com/67773102/168827389-13bb98d2-ddf2-414a-becc-fb5fa5bb74c1.png)
I'm trying to import a style sheet but I can't "find" it, I'm really confused, am I typing the path wrong? Any help is appreciated

**Comment by oceanlvr** [comment]
https://github.com/vitejs/vite/issues/5682#issuecomment-968713998

>  If you don't load any .scss file (or <style lang="scss"> blocks) in your project, there's no place for it to insert in.

Please check your `Header.vue` file.

**Comment by UnTalPeluca** [comment]
> [vitejs/vite#5682 (comment)](https://github.com/vitejs/vite/issues/5682#issuecomment-968713998)
> 
> > If you don't load any .scss file (or <style lang="scss"> blocks) in your project, there's no place for it to insert in.
> 
> Please check your `Header.vue` file.

I have a <style lang="scss"> in my Header
![image](https://user-images.githubusercontent.com/67773102/168948889-d810a022-7c8f-4b15-a556-99b986099be0.png)

I have a project with Vue, Vite and Sass up and running with the same configuration 😔

**Comment by caoxiemeihao** [comment]
In practice, your file may not be at the same directory-level as `src`.  
So `@import "./src/xxx"` may be wrong. You can try configuration `resolve.alias` to resolve the problem.  

**e.g**

```ts
// renderer/vite.config.ts
{
  resolve: {
    alias: {
      '~assets': path.join(__dirname, 'src/assets'),
    },
  },
}
```

And then modify your code

`@import "./src/assets/sass/main.scss"` to `@import "~assets/sass/main.scss"`

**Comment by UnTalPeluca** [comment]
> In practice, your component-file may not be at the same directory-level as `src`. So `@import "./src/xxx"` may be wrong. You can try to configure `resolve.alias` to resolve the problem.
> 
> **e.g**
> 
> ```ts
> // renderer/vite.config.ts
> {
>   resolve: {
>     alias: {
>       '~assets': path.join(__dirname, 'src/assets'),
>     },
>   },
> }
> ```
> 
> And then modify your code
> 
> `@import "./src/assets/sass/main.scss"` to `@import "~assets/sass/main.scss"`

It works, thank you very much
