### ISSUE TITLE
加入vue-router后build提示exports is not defined

### ISSUE THREAD

**Issue by mqllin** [electron-vite/electron-vite-vue#135]
加入vue-router后build提示exports is not defined，且dev环境下运行正常。

我尝试了google中能搜到的一切方法。都没有效果。[code demo](https://github.com/mqllin/electron-vite-vue)
大佬们能否指点一下？
网上绝大多数都是说vite.config中加入「format: 'cjs'」 选项。但我看在vite中已经存在该项配置。
build后运行截图：
<img width="1113" alt="QQ20220525-112913@2x" src="https://user-images.githubusercontent.com/24357436/170174027-523c3348-f233-4b0a-9701-ad7f56331c23.png">
<img width="1113" alt="QQ20220525-112945@2x" src="https://user-images.githubusercontent.com/24357436/170174047-2d15589e-685d-4fb0-9a1c-1d8704625919.png">

**Comment by caoxiemeihao** [comment]
兄弟！不是有个 issues 贴在那嘛 😓

**Comment by mqllin** [comment]
> 兄弟不是贴问题贴嘛！😓

哎呀不好意思 看到了。现在问题解决了😂
