### ISSUE TITLE
Set icon not to be displayed

### ISSUE THREAD

**Issue by Tyh2001** [electron-vite/electron-vite-vue#136]
[here](https://github.com/electron-vite/electron-vite-vue/blob/main/packages/main/index.ts#L21) Change to：

```ts
icon: join(__dirname, './icon.png'),
```

Icon is configured but will not take effect

**Comment by caoxiemeihao** [comment]
文件需要 copy 下

**Comment by Tyh2001** [comment]
下面是配置

```ts
win = new BrowserWindow({
    icon: join(__dirname, './icon.png'),
    title: '715',
    autoHideMenuBar: true, // 隐藏菜单栏
    // fullscreen: true, // 全屏
    show: false, // 最大化
    webPreferences: {
      preload: join(__dirname, '../preload/index.cjs'),
      nodeIntegration: true,
      contextIsolation: false,
    },
  })
```

目录结构为：
![a0add021c0c1ac05df94f78798e94c9](https://user-images.githubusercontent.com/73180970/170402698-0ae4e596-4f38-4529-98a5-d4dfadc6edcc.png)

**Comment by caoxiemeihao** [comment]
build 命令并不会把你的 packages/main/icon.png 复制到 dist/main/icon.png 这个需要你自己完成，懂？

**Comment by Tyh2001** [comment]
我试试看
