### ISSUE TITLE
[Help] style don't works after build | build 后，style全部丢失了，在控制台也没有看到报错提示，开发环境一切正常

### ISSUE THREAD

**Issue by mx623303468** [electron-vite/electron-vite-vue#150]
#### Describe the problem you Confuse

A clear and concise description of what you are confusing about.

#### More detail (optional)

Add any other context or screenshots.

**Comment by caoxiemeihao** [comment]
Demo 丢出来看看？

**Comment by mx623303468** [comment]
> 

老哥，给个联系方式，我发给你看看
