### ISSUE TITLE
[Help] 请教一下腾讯音视频trtc-electron-sdk修改webpack配置，vite要怎么修改

### ISSUE THREAD

**Issue by lijun1243939149** [electron-vite/electron-vite-vue#153]
我们使用了腾讯音视频的trtc-electron-sdk，需要修改webpack配置，配置native-ext-loader插件，加载.node文件。
请教一下本项目使用vite，怎么修改这个配置呢？
 ![image](https://user-images.githubusercontent.com/13789967/173731395-e846b6b6-f1a0-47c8-a3e2-cd4d5d21c9d1.png)

**Comment by lijun1243939149** [comment]
腾讯音视频 trtc-electron-sdk 介入文档： https://cloud.tencent.com/document/product/647/38549

**Comment by caoxiemeihao** [comment]
用 C++ 模块可以参考下 README 中贴出的 Serialport 使用 Demo

**Comment by hhcgq** [comment]
找到了这个
https://github.com/tencentyun/TUIRoom/tree/main/Electron

**Comment by caoxiemeihao** [comment]
> 找到了这个 https://github.com/tencentyun/TUIRoom/tree/main/Electron

这个是个很好的案例 👍
