### ISSUE TITLE
[Help] the title of Help_Want report  v2.0.0

### ISSUE THREAD

**Issue by RayCssjmt** [electron-vite/electron-vite-vue#155]
v2.0.0 npm 什么时候出呢

**Comment by caoxiemeihao** [comment]
v2.0.0 今晚会出来，不是 npm 😅

**Comment by RayCssjmt** [comment]
> v2.0.0 今晚会出来，不是 npm 😅
> 
> ---
> 
> v0.2.0 had come | https://github.com/electron-vite/electron-vite-vue/pull/156 🎉

那我现在拉2.0.0分支的直接用 即可是吧

**Comment by caoxiemeihao** [comment]
主分支就是 2.0.0

**Comment by RayCssjmt** [comment]
> 主分支就是 2.0.0

好呢  谢谢大佬
