### ISSUE TITLE
[Help] Debugging with JetBrains WebStorm

### ISSUE THREAD

**Issue by DallasP9124** [electron-vite/electron-vite-vue#158]
Wondering if anyone has ever been able to setup debugging configurations in WebStorm using this setup? I am a JetBrains guy so don't use VS Code and don't intend to.

Any help is appreciated.

**Comment by watonyweng** [comment]
Please refer to [How to debug a vite project on Webstorm](https://github.com/vitejs/vite/discussions/6511)
