### ISSUE TITLE
请教下 electron13 和 vue3 devtools 配置

### ISSUE THREAD

**Issue by tjx666** [electron-vite/electron-vite-vue#16]
老哥我最近在整一个 vue + electron 项目，搭项目框架的时候参考了这个项目不少代码，但是在配置 vue3 devtools 的碰到一些问题。
第一个是使用 `electron-devtools-installer` 加载 vue3 devtools 时会有下面的警告：

```
(node:39242) ExtensionLoadWarning: Warnings loading extension at /Users/yutengjing/Library/Application Support/app/extensions/ljjemllljcmogpfapbkkighbhhppjdbg:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'update_url'.
  Permission 'contextMenus' is unknown or URL pattern is malformed.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

(Use `Electron --trace-warnings ...` to show where the warning was created)
```

第二个是打开 vue devtools tab 和 electron app 后点击窗口，控制台报错：

```
[39242:0715/170333.702784:ERROR:CONSOLE(2)] "Uncaught (in promise) TypeError: chrome.tabs.captureVisibleTab is not a function", source: chrome-extension://onimmhnncoodiojfaeonajhfdipemkoi/build/devtools.js (2)
```

不知道你有没有碰到过这些问题。

**Comment by caoxiemeihao** [comment]
能贴点配置啥地看看嘛，`electron-devtools-installer` 这玩意儿我没装过

**Comment by tjx666** [comment]
@caoxiemeihao https://github.com/tjx666/electron-vue-vite-boilerplate/blob/master/packages/app/src/main/src/index.ts#L22

**Comment by coooo77** [comment]
vue3 devTool我是参考这篇官方去设定 https://www.electronjs.org/docs/latest/tutorial/devtools-extension
可以显示vue3 devTool，但会node会跳警告

```node
(node:21480) ExtensionLoadWarning: Warnings loading extension at USER\AppData\Local\Google\Chrome\User Data\Default\Extensions\ljjemllljcmogpfapbkkighbhhppjdbg\6.0.0.21_0:
  Permission 'contextMenus' is unknown or URL pattern is malformed.
```

**Comment by icepole-jon** [comment]
可以试试这样添加，对我有用
```js
if (app.isPackaged) {
    win.loadFile(join(__dirname, "../renderer/index.html"));
  } else {
    // 🚧 Use ['ENV_NAME'] avoid vite:define plugin
    const url = `http://${process.env["VITE_DEV_SERVER_HOST"]}:${process.env["VITE_DEV_SERVER_PORT"]}`;

    win.loadURL(url);
    win.webContents.openDevTools();
    import("electron-devtools-installer").then((installer) => {
      installer
        .default(installer.VUEJS3_DEVTOOLS.id)
        .then((name) => console.log(`已安装: ${name}`))
        .catch((err) => console.log("无法安装 vue-devtools: \n", err));
    });
    console.log("中文测试");
    console.log("\u4E2D\u6587\u6D4B\u8BD5");
  }
```
顺便问下你们会遇到log中文乱码的问题吗？
上面的log都会显示乱码

**Comment by coooo77** [comment]
@icepole-jon  试了一下你的代码，遇到同样的错误讯息，顺带一提log中文也是乱码

**Comment by icepole-jon** [comment]
```js
app
    .whenReady()
    .then(() => import("electron-devtools-installer"))
    .then(({ default: installExtension, VUEJS3_DEVTOOLS }) =>
      installExtension(VUEJS3_DEVTOOLS.id, {
        loadExtensionOptions: {
          allowFileAccess: true,
        },
      })
    )
    .catch((e) => console.error("Failed install extension:", e));
```
```
[20984:0214/083934.803:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read properties of undefined (reading 'instance')", source: devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@2bee2cb92d553708966882df183bb533ac105e7c/&can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (1)
```
我的node端也会报警告，插件倒是可以正常使用，就无视掉了😂
顺便，unicode问题是spawn options.stdio配置的原因

**Comment by jiumengs** [comment]
> vue3 devTool我是参考这篇官方去设定 https://www.electronjs.org/docs/latest/tutorial/devtools-extension 可以显示vue3 devTool，但会node会跳警告
> 
> ```js
> (node:21480) ExtensionLoadWarning: Warnings loading extension at USER\AppData\Local\Google\Chrome\User Data\Default\Extensions\ljjemllljcmogpfapbkkighbhhppjdbg\6.0.0.21_0:
>   Permission 'contextMenus' is unknown or URL pattern is malformed.
> ```

这个是vue3 devTool扩展的问题。可以打开插件去修改下

**Comment by coooo77** [comment]
> > vue3 devTool我是参考这篇官方去设定 https://www.electronjs.org/docs/latest/tutorial/devtools-extension 可以显示vue3 devTool，但会node会跳警告
> > ```js
> > (node:21480) ExtensionLoadWarning: Warnings loading extension at USER\AppData\Local\Google\Chrome\User Data\Default\Extensions\ljjemllljcmogpfapbkkighbhhppjdbg\6.0.0.21_0:
> >   Permission 'contextMenus' is unknown or URL pattern is malformed.
> > ```
> 
> 这个是vue3 devTool扩展的问题。可以打开扩展文件夹去修改下

这个问题的普遍作法是删除dev tool的manifest中的contextMenus，尝试一下的确没显示了，但不确定是不是好事情。不过对开发没有什么影响，所以还是先保留不更动了

```json
{
  "permissions": ["\u003Call_urls>", "contextMenus", "storage"]
}
```

**Comment by SharerMax** [comment]
可以试试
```
installExtension(VUEJS_DEVTOOLS.id)
      .then((name) => console.log(`Added Extension:  ${name}`))
      .catch((err) => console.log('An error occurred: ', err))
```
根据源码可知 ```VUEJS_DEVTOOLS ```指向的是最新版的 devtools,  而```VUEJS3_DEVTOOLS``` 指向的是之前的 beta 版，已经许久不更新了

https://github.com/MarshallOfSound/electron-devtools-installer/blob/65ffa894bf635745d9399e79fb38682ccfd9c6e0/src/index.ts#L164

**Comment by aolyang** [comment]
我直接把devtools 放项目里，浏览器的更新，变动什么的都不会有影响到 项目正在使用的 扩展，如果嫌弃，可以gitignore。 

之前也有写 根据扩展 id去检查扩展在不在，然后 install的代码， 没有直接放项目里丝滑。然而有些人用Chrome， 有人用Edge， 国内下载插件还需要代理，多麻烦。

没有必要单独使用 **electron-devtools-installer** 这个库，之前因为有一次 这个包更新不及时 就弃用了。

![image](https://user-images.githubusercontent.com/72056179/177074021-6ddeffbb-f2d9-4ed1-9f68-b43e605b5f92.png)

```typescript
      const extensionDir = path.join(process.cwd(), "./extensions/react-devtools")

      await session.defaultSession.loadExtension(
        path.join(extensionDir, fs.readdirSync(extensionDir)[0])
      )
```
