### ISSUE TITLE
请问 在package.json 加入build配置 报错，怎么解决呢 

### ISSUE THREAD

**Issue by RayCssjmt** [electron-vite/electron-vite-vue#160]
![image](https://user-images.githubusercontent.com/56436894/174545132-1cd7c9b4-22e5-4412-a65c-597c179dc576.png)
![image](https://user-images.githubusercontent.com/56436894/174545502-0597c031-5516-46b1-a9a5-4f5a40e35def.png)

**Comment by caoxiemeihao** [comment]
入口文件找不到，看不懂英语？看不懂不有百度翻译吗？

**Comment by RayCssjmt** [comment]
@caoxiemeihao 我翻译了，我不知道加入了build就出现这个情况，是什么原因导致，我该怎么处理，麻烦了

**Comment by caoxiemeihao** [comment]
看看构建后的 dist 文件夹的目录结构；build 阶段会找 pakcage.json 中的 main 字段。  
main 字段配置的是 dist/electron/main/index.js 要和构建后的文件路径保持一致，不一致改改。
