### ISSUE TITLE
[Help]没有办法使用vue-router,基础使用也会报错！

### ISSUE THREAD

**Issue by mJunLiang** [electron-vite/electron-vite-vue#169]
安装了 vue-router@4 根据官网“入门”  main.ts 正常引入了 vue-router 

在APP.vue内加入router-link或router-view就会报错。

router-view报错:Uncaught TypeError: Cannot read properties of null (reading 'parent')

router-link报错:Uncaught TypeError:Cannot destructure property 'options' of 'vue.inject(...)' as it is undefined.

度娘已经搜索过无数次，找不到任何解决方法。自己通过vite创建的项目没有这个问题。 有没有人遇过此问题，已经解决的！麻烦告知一下。

**Comment by mJunLiang** [comment]
已经找到问题了，vue 3.2.36 有此问题，升级到3.2.37 就正常了 郁闷死了 浪费一下午时间！！！

**Comment by mJunLiang** [comment]
补充一下，不是升级vue的问题，vue 在devDependencies下 就会报错，vue安装到dependencies下就正常。不知道什么原因！

**Comment by caoxiemeihao** [comment]
你确定你看了 REAMME?

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-vue#-dependencies-vs-devdependencies
