### ISSUE TITLE
[Bug] 构建问题

### ISSUE THREAD

**Issue by Jiaocz** [electron-vite/electron-vite-vue#173]
目前来看，在 `electron/main/index.ts` 文件里有两个小问题：

一是，在 [Line 42](https://github.com/electron-vite/electron-vite-vue/blob/e51eccb41b248f6d6338f80b45f56552887bd6bc/electron/main/index.ts#L42) 中使用了 `indexHtml` 变量但实际没有定义，可以添加一行
```typescript
const indexHtml = join(__dirname, '../../index.html')
```

二是，[Line 27](https://github.com/electron-vite/electron-vite-vue/blob/e51eccb41b248f6d6338f80b45f56552887bd6bc/electron/main/index.ts#L27) 的preload的路径可能不太对，加载不到，可能应该是这样
```typescript
const preload = join(__dirname, '../../electron/preload/index.js')
```

还有就是 vite 打包问题，刚刚克隆的仓库也会出现打包完 `Failed to construct 'URL': Invalid URL` 的情况，具体可以使用
```shell
npx vite build
live-server dist
```
的方式复现，希望可以得以解决

---

以下是进度记录（如果有用的话）
- [x] electron 配置文件问题  #176 
- [x] vite 打包问题 #176

**Comment by Jiaocz** [comment]
基于 commit: f65ed8f4866111f2ebc87407e4efc99bd32ba866 
另外提一嘴就是 GitHub Actions 配置有问题，每次都报错，因为 npm ci 依赖于package-lock.json，但是本仓库没有提交这个文件（甚至gitignore了）

**Comment by 2020wym** [comment]
遇到了相同的问题

**Comment by youngleish** [comment]
你可以拉一下最新代码试一下

**Comment by Jiaocz** [comment]
@youngleish 构建问题已经没有了，dev server 的问题提在 #178 了
