### ISSUE TITLE
[Bug] 构建失败

### ISSUE THREAD

**Issue by Rain20199** [electron-vite/electron-vite-vue#177]
#### What did I do
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/56431955/176867468-bfeb63ac-1713-4d20-8e98-751723c8b79f.png">

Something you have done.

#### What happened

Get an error.

#### Expected

What is the expected result.

#### Environment

- OS: OS version, e.g. macOS Big Sur 11.1
- electron-vue-vite version (or commit hash), e.g. v1.0.0

#### More detail

More detail like screenshot

**Comment by caoxiemeihao** [comment]
You can provide a minimize Demo?

**Comment by caoxiemeihao** [comment]
The BUG has fixed. You can pull the latest code to try resolve it.
https://github.com/electron-vite/electron-vite-vue/commit/77acb0a5b05748970ed7ba082080246094ccaf1d
