### ISSUE TITLE
[Bug] dev 模式失效

### ISSUE THREAD

**Issue by Jiaocz** [electron-vite/electron-vite-vue#178]
#### What did I do

使用当前最新代码 0bcaa99bda82b7505fe79c2d6ebf420c68772450
安装依赖 `pnpm i`
开启调试服务器 `pnpm dev`

#### What happened

白屏
![image](https://user-images.githubusercontent.com/14857984/176922602-6535ae13-8007-4ff0-9191-2b9b7fdee2a1.png)

通过打log的方式，确认是 `electron/main/index.ts` 中的 `win.loadURL(url)` 中的url参数为 `http://undefined:undefined`

#### Expected

显示 vite 的 dev server
（直接打开 `http://127.0.0.1:3344/` 没有问题）

#### Environment

包管理器：pnpm
OS: Windows 10
其他均为仓库默认

#### More detail

url log
![image](https://user-images.githubusercontent.com/14857984/176923231-2e5cd58c-a569-4d6e-a5ea-00b38cd8a856.png)

明明环境变量是没有问题的，但是最后生成就是undefined
![image](https://user-images.githubusercontent.com/14857984/176924302-05556bd3-fdd3-42ce-8ea9-19919020d19f.png)
是不是个人问题导致的

**Comment by caoxiemeihao** [comment]
已经修复
https://github.com/electron-vite/electron-vite-vue/commit/77acb0a5b05748970ed7ba082080246094ccaf1d

我来解释下这个问题；
`process.env.VITE_DEV_SERVER_HOST` 这种写法会被 Vite 内置的 `vite:define` 插件给干掉；然后吧我发现了 Vite 最新代码在判断是 `build.lib` 的模式下会绕过 `vite:define` 插件。  

```ts
// 万恶之源
  if (!isBuildLib) {
    const nodeEnv = process.env.NODE_ENV || config.mode
    Object.assign(processEnv, {
      'process.env.': `({}).`,
      'global.process.env.': `({}).`,
      'globalThis.process.env.': `({}).`
    })
    Object.assign(processNodeEnv, {
      'process.env.NODE_ENV': JSON.stringify(nodeEnv),
      'global.process.env.NODE_ENV': JSON.stringify(nodeEnv),
      'globalThis.process.env.NODE_ENV': JSON.stringify(nodeEnv)
    })
  }
```
https://github.com/vitejs/vite/commit/908c9e4cdd2cceb0f01495e38066ffe33c21ddb8#diff-d90a7c21c9fb9222e557704bd906ea5671d5fe384c8fb105459eea8c36fdb4f0R18

于是乎为了这个写法，于是 Vite 就升级到了最新的 `3.0.0-beta5`；然后看似这个问题解决了，但是构建后产物出问题了。属于是 “按倒葫芦瓢又起” 😅。  
这回不作了，代码还原回来了；请放心食用 :)

**Comment by Rain20199** [comment]
泪流满面 终于成功运行了

**Comment by caoxiemeihao** [comment]
> 泪流满面 终于成功运行了

别太鸡冻，实在不行给我发个红包也行的 🙃
