### ISSUE TITLE
[Help] 请教如何在electron/main中使用axios与设定环境变数

### ISSUE THREAD

**Issue by coooo77** [electron-vite/electron-vite-vue#183]
如题，在使用这新版的template时，axios我依照readme安装到devDependencies了，但是在electron/main下会报错。

```console
(node:23156) UnhandledPromiseRejectionWarning: ReferenceError: XMLHttpRequest is not defined
```

另外请教要在设定环境变数时，同样在electron/main下要如何设定?看起来vite没有使用到.env的设定，这部分我用dotenv安裝到dependencies是可行的

**Comment by caoxiemeihao** [comment]
1. https://github.com/electron-vite/vite-plugin-electron/issues/13
2. https://github.com/electron-vite/electron-vite-vue/blob/e5e341b041d082703686d247dd8836596a895a41/electron/main/index.ts#L28

**Comment by coooo77** [comment]
谢谢回应，关于第二点，可以麻烦再详细吗? 我的是用process.env['ENV_NAME']这种写法取值没错，但process.env内并没.env内设定的值

**Comment by caoxiemeihao** [comment]
> 但process.env内并没.env内设定的值
你说的 `.env` 是你自己设置了一个 `.env.xxx` 文件么？就是 Vite 官网的推荐的写法？

**Comment by caoxiemeihao** [comment]
主进程可以使用 dotenv 的，如果拿不到值，贴下代码

**Comment by coooo77** [comment]
> > 但process.env内并没.env内设定的值
> 
> 你说的 `.env` 是你自己设置了一个 `.env.xxx` 文件么？就是 Vite 官网的推荐的写法？ <img alt="image" width="783" src="https://user-images.githubusercontent.com/26263658/178170973-7cc4f545-9d08-49b2-ba30-6ea4d2664953.png">

是的，用的是Vite 官网的推荐的写法，之前在template未使用vite-plugin-electron时，使用做法可行(虽然取法不同)

**Comment by caoxiemeihao** [comment]
`.env` 文件的取值是 Vite 内置的 `vite:define` 通过的功能，通过正则替换实现的；  
主进程目前是用的是 `build.lib` 模式构建，Vite 最新版本发现如果是 `build.lib` 构建方式，会绕开 `vite:define` 插件。  
所以就目前情况来看，是在主进程中使用 `dotenv` 比较稳妥。

https://github.com/vitejs/vite/blob/53799e1cced7957f9877a5b5c9b6351b48e216a7/packages/vite/src/node/plugins/define.ts#L18
```ts
  if (!isBuildLib) {
    const nodeEnv = process.env.NODE_ENV || config.mode
    Object.assign(processEnv, {
      'process.env.': `({}).`,
      'global.process.env.': `({}).`,
      'globalThis.process.env.': `({}).`
    })
    Object.assign(processNodeEnv, {
      'process.env.NODE_ENV': JSON.stringify(nodeEnv),
      'global.process.env.NODE_ENV': JSON.stringify(nodeEnv),
      'globalThis.process.env.NODE_ENV': JSON.stringify(nodeEnv),
      __vite_process_env_NODE_ENV: JSON.stringify(nodeEnv)
    })
  }
```

**Comment by coooo77** [comment]
> 主进程可以使用 dotenv 的，如果拿不到值，贴下代码

发现在尚未打包情况下(electron.app.isPackaged为false时)，dotenv有效，但打包过后会无法使用；测试方式是调整主进程读取网址(如下)，打包过后会显示electron的官方网站

```typescript
// electron/main/index.ts
import { app, BrowserWindow, shell, ipcMain } from 'electron'
import { release } from 'os'
import { join } from 'path'
import dotenv from 'dotenv'

dotenv.config()

...

const createWindow = async () => {

  ...

  if (app.isPackaged) {
    win.loadURL(process.env['TEST'] || 'https://www.electronjs.org/')
  } else {
    win.loadURL(process.env['TEST'] || 'https://www.electronjs.org/')
  }

  ...
}
```

**Comment by caoxiemeihao** [comment]
你可能需要把 `.env` 打包到 `asar` 文件中

**Comment by coooo77** [comment]
用了asar解压缩工具把app.asar解压缩，有确认到.env存在于app/dist底下；查了electron-builder可以设定electron-builder.env处理环境变数，但实际上无效。

之前使用script写build.mjs的版本倒是没有这个问题

**Comment by caoxiemeihao** [comment]
确定 asar 中的 `.env` 文件路径是对的？
开发期和构建后，路径是不一样的，

**Comment by coooo77** [comment]
app.asar文件结构如下，所以正确位置应该与package.json同层?
```
|-- dist
     |-- electron
          |-- main
          |-- preload
     |--.env
     |--index.html
|-- node_modules
     |-- .package-lock
|-- package.json
```

**Comment by caoxiemeihao** [comment]
`../../.env`

**Comment by coooo77** [comment]
axios使用adaper：require('axios/lib/adapters/http')在打包过后会无法使用

```console
MODULE_NOT_FOUND

Cannot find module 'axios/lib/adapters/http' Require stack: D:\\path-to-project\\electron-vite-vue\\release\\2.0.0\\win-unpacked\\resources\\app.asar\\dist\\electron\\main\\index.js\
```

查到一种解决方式是修改node_modules目录下的axios设定，但觉得不是很好；用node-fetch是可以处理这个问题。请问这个有什么办法解决吗？
