### ISSUE TITLE
vue3的模板，build完成之后打开应用sass样式丢失

### ISSUE THREAD

**Issue by linqian02** [electron-vite/electron-vite-vue#184]
vue3的模板，build完成之后打开应用样式丢失？有遇见过的小伙伴吗？

这样简单的写build之后也无效

![image](https://user-images.githubusercontent.com/29908531/178172090-b27e25dd-57b6-4943-b9c5-423c525fc36d.png)

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-vue/issues/107

**Comment by linqian02** [comment]
> [[🐞] Styles loading failure #107](https://github.com/electron-vite/electron-vite-vue/issues/107)
> 
> ```diff
>  build: {
>     // 异步路由加载css有问题,所以暂时禁用
>     // It works!
> +   cssCodeSplit: false,
>   },
> ```

解决了， 感谢！
