### ISSUE TITLE
开发环境的包在哪里配置，才能不会被打包进生产环境中呢？

### ISSUE THREAD

**Issue by Qwqw127** [electron-vite/electron-vite-vue#185]
#### Describe the problem you confuse
目前文档中介绍的是，devDependencies与dependencies分别都是有用的依赖。
那么开发环境的包如："eslint": "^8.17.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-vue这些在哪里配置，才能被打包进生产环境中呢？

**Comment by caoxiemeihao** [comment]
dependencies

**Comment by caoxiemeihao** [comment]
devDependencies
