### ISSUE TITLE
[Help] 额外建立electron资料夹底下ts档案会造成build错误

### ISSUE THREAD

**Issue by coooo77** [electron-vite/electron-vite-vue#189]
在template的eletron资料夹下，不论是在main或是preload额外建立ts档案引用时，编译都会显示错误
<br>
例如在preload建立test.ts，并引用到preload/index.ts中，显示错误：

```console
error TS6305: Output file 'PROJECT_PATH/electron-vite-vue/electron/preload/test.d.ts' has not been built from source file 'PROJECT_PATH/electron-vite-vue/electron/preload/test.ts'.
  The file is in the program because:
    Matched by include pattern '**/*' in 'PROJECT_PATH/electron-vite-vue/tsconfig.json'
 ```
 
在架构上是只能用单一index.ts档案吗?

<br>

另外请教在渲染进程如果需要取得专案位置，有什么好取法呢? 目前是取process.env.PWD

**Comment by caoxiemeihao** [comment]
台湾的兄台？“专案位置” 这个啥意思？理解不了 :(

**Comment by spianmo** [comment]
> 台湾的兄台？“专案位置” 这个啥意思？理解不了 :(

我也遇到这个问题，也就是写个util文件夹下面写个index.ts之后编译时提示对应的index.d.ts未生成，就得手动写undex.d.ts，可index.d.ts应该是自动生成的

**Comment by spianmo** [comment]
index.d.ts不是undex.d.ts，打错了

**Comment by caoxiemeihao** [comment]
不知道你们想干嘛，比如有如下文件结构；我说下插件实际行为；
```tree
├── electron
└─┬ main
  ├── foo.ts
  └── index.ts
```
`main/` 和 `preload/` 无论哪个文件夹，只会有一个 “入口文件”。其余文件如果被入口文件引入(如foo.ts)，那么会被 Vite 构建的 `dist/electron/main/index.js` 中 -- 这种行为叫 `bundle`。

你们想要的是不是 `index.ts`、`foo.ts` 原木原样的生成 `dist/electron/main/index.js` + `dist/electron/main/index.d.ts` 、`dist/electron/main/foo.js` + `dist/electron/main/foo.d.ts` -- 这种行为这个叫 `non-bundle`。

目前插件走的是 `bundle` 行为。不确定 `non-bundle` 的使用场景大不大。后期考虑提供 `non-bundle` 能力。

> 顺带说一句 `non-bundle` 只需要 `tsc` 这种工具转换即可，

**Comment by coooo77** [comment]
关于专案位置，之前看大老文章是做vite lib方式处理electron打包部分，所以在渲染进程使用__dirname时会取到
```console
D:\PROJECT_PATH\electron-vite-vue\node_modules\electron\dist\resources\electron.asar\renderer
```
如果要取根目录，有比较好的建议吗? 或是直接使用electron的app.getAppPath()就好?
```console
D:\PROJECT_PATH\electron-vite-vue
```
<br>

> 不知道你们想干嘛，我说下插件实际行为。比如有如下文件结构：
> 
> ```
> ├─┬ electron
> │ └─┬ main
> │   ├── foo.ts
> │   └── index.ts
> ```
> 
> `main/` 和 `preload/` 无论哪个文件夹，只会有一个 “入口文件”。其余文件如果被入口文件引入(如foo.ts)，那么会被 Vite 构建的 `dist/electron/main/index.js` 中 -- 这种行为叫 `bundle`。
> 
> 你们想要的是不是原木原样的生成？
> 
> * `index.ts` --> `dist/electron/main/index.js` + `dist/electron/main/index.d.ts`
> * `foo.ts`  --> `dist/electron/main/foo.js` + `dist/electron/main/foo.d.ts`
> 
> 这种行为这个叫 `non-bundle`。
> 
> 目前插件走的是 `bundle` 行为；不确定 `non-bundle` 的使用场景大不大，如果确实有需求量，后期考虑提供 `non-bundle` 能力。
> 
> > 顺带说一句 `non-bundle` 只需要 `tsc` 转换即可

因為打算做個登入系統，會使用到OAuth另開視窗，所以在主进程另外寫份ts檔案處理

**Comment by caoxiemeihao** [comment]
@coooo77 渲染进程取当前项目路径，可以考虑在 `vite.config.ts` 中配置 `define`。

- vite.config.ts

```diff
+ define: {
+   'process.env.ROOT': JSON.stringify(__dirname)
+ }
```

- src/main.ts

```diff
+ console.log(process.env.ROOT)
```

**Comment by caoxiemeihao** [comment]
这个 PR 暂时先关闭，如果需真的会有需求量；我将会在另一个仓库中完成。
👉 [electron-vite-typescript](https://github.com/caoxiemeihao/electron-vite-typescript)

**Comment by dongivan** [comment]
关于楼主的第一个问题，我也有类似的疑问。
对于`electron/main/index.ts`、`electron/preload/index.ts`中使用`import`引入的**同级**代码文件，如在`preload/index.ts`中
```ts
import test from "./foo" // import file `electron/preload/foo.ts`
```
这样在执行`vue-tsc --noEmit`时没有问题。

但是对于**非同级**的代码，如在`preload/index.ts`中
```ts
import test from "./bar/index" // import file `electron/preload/bar/index.ts`
```
就会报楼主这样的错误。

我的目的是打开`contextIsolation`，这样的话需要在preload中载入一些模块通过`contextBridge`暴露到渲染进程，这些模块的代码不应该都放在`electron/preload/index.ts`的同级目录里啊~

期待@caoxiemeihao 大佬讲解

**Comment by hoganjobs** [comment]
关于楼主的第一个问题，我也有一样的问题。
```bash
error TS6305: Output file '\PROJECT_PATH\electron-vite-vue/electron/main/event/ipcList.d.ts' has not been built from source file '\PROJECT_PATH\electron-vite-vue/electron/main/event/ipcList.ts'.
  The file is in the program because:
    Matched by include pattern '**/*' in '\PROJECT_PATH\electron-vite-vue/tsconfig.json'
```
期待@caoxiemeihao 大佬帮忙看看

**Comment by caoxiemeihao** [comment]
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/26263658/181661479-9e14c60a-8a3f-4013-bd1f-10c3969493c0.png">

**Comment by fanlion** [comment]
如何在electron和src目录中共享代码呢？例如：可在渲染进程和主进程中同时使用的enum枚举值

**Comment by dongivan** [comment]
> 如何在electron和src目录中共享代码呢？例如：可在渲染进程和主进程中同时使用的enum枚举值

试试修改`tsconfig.json`和`tsconfig.node.json`中的`includes`，把你需要在对应环境引入的代码加进去。
前者对应renderer，后者对应main。
