### ISSUE TITLE
[Help] 开发环境正常，打包安装后报错。

### ISSUE THREAD

**Issue by hezc** [electron-vite/electron-vite-vue#190]
#### 本地视频文件放在 public 目录
![image](https://user-images.githubusercontent.com/7135453/179129769-0ce54892-c156-4df7-8274-9d19197bdc6c.png)
```
const dir = fs.readdirSync('./public/book1'); 
//通过这个来读取文件目录
<video :src="/book1/' + dir[i]"></video>
<img src="/img/icon.png" />

```
本地开发正常运行，打包安装后，运行报错
![image](https://user-images.githubusercontent.com/7135453/179130600-9120ff4c-308f-4349-b0f3-04bcf4206084.png)

图片能正常加载出来

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-vue/blob/bbf38e3a16b945e1a492453a5470037d4978ed10/electron/main/index.ts#L22

**Comment by hezc** [comment]
谢谢

**Comment by hezc** [comment]
谢谢
