### ISSUE TITLE
vue-router 报错   No match found for location with path "/F:/Node.js/oned/release/1.0.0/win-unpacked/resources/app.asar/dist/index.html"

### ISSUE THREAD

**Issue by 3DMXM** [electron-vite/electron-vite-vue#191]
我不太会ts，不知道是不是我写的有问题。

我的代码：https://git.aoe.top/aoe.top/OneD

首先，在开发Dev环境没有问题，
![](https://tva1.sinaimg.cn/large/005PVVAugy1h4cae30mi1j313i0dfn42.jpg)

但使用 npm run build 打包之后，运行时路由会报错

![](https://tva1.sinaimg.cn/large/005PVVAugy1h4cajhwvv9j30yd0dwdkk.jpg)

有大佬能帮忙看看吗

**Comment by caoxiemeihao** [comment]
放到 devDependenices 中

**Comment by 3DMXM** [comment]
> 放到 devDependenices 中

emmmm，啥放到 devDependencies  里面， vue-router 吗？如果放进去的话，直接报错了
![](https://tva1.sinaimg.cn/large/005PVVAugy1h4cepx0nwmj315e0m8h21.jpg)

**Comment by 3DMXM** [comment]
> 

丢到GitHub上了  https://github.com/3DMXM/OneD

**Comment by caoxiemeihao** [comment]
我这跑起来好的呀

**Comment by 3DMXM** [comment]
您是怎么打包的？ npm run build 还是其他打包工具

**Comment by caoxiemeihao** [comment]
npm run build

**Comment by 3DMXM** [comment]
问题解决了，将 vue-router 模式改成 Hash 就行了。。。

**Comment by Kenhuey** [comment]
> 问题解决了，将 vue-router 模式改成 Hash 就行了。。。

是的 刚刚我也遇到了，而且还要转换成loadUrl， # 或者 / 会导致 loadFile 也会报错

**Comment by 18272351104** [comment]
#或者/会导致loadFile 报错这个怎么解决的 大佬们
