### ISSUE TITLE
[Bug] Include package-lock.json

### ISSUE THREAD

**Issue by stefnotch** [electron-vite/electron-vite-vue#192]
#### Describe the bug

Adding the `package-lock.json` file to the `.gitignore` is probably not what users of the template expect. Essentially, an Electron app is an application, and not a library. And with an application, one definitely wants to be able to recreate it anytime.

However, if there's not package-lock.json, it's possible that some dependencies change, and suddenly, the previously-working application cannot be built anymore.

**Comment by caoxiemeihao** [comment]
The earlier version `v1.0.0` included `pacakge-lock.json`, but many people don't like `npm` they prefer `pnpm` `yarn`, which makes `package-lock.json` controversial.

**Comment by stefnotch** [comment]
I still don't think that it should be in the `.gitignore` file, that's essentially setting oneself up for trouble.

**Comment by caoxiemeihao** [comment]
Right now, the project contains only 8 dependencies. Remove `package-lock.json` and keep it consistent with the [official vite-ts template](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-vue-ts).

**Comment by caoxiemeihao** [comment]
You are right, you can submit a PR to remove `*.lock` from `.gitignore`.

**Comment by caoxiemeihao** [comment]
putting `*.lock` in `.gitignore` is more useful to prevent the `*.lock` file from being carried when submitting PR.
