### ISSUE TITLE
[Help] dev 正常，build后启动报错， Cannot find module '@electron/remote/main'

### ISSUE THREAD

**Issue by xemxx** [electron-vite/electron-vite-vue#194]
## 将 @electron/remote 放到 devDep

就是dev正常，打包报错

dev
![image](https://user-images.githubusercontent.com/26523062/179763990-47952a6d-d71d-4c03-b77d-c97734abc806.png)

build
![image](https://user-images.githubusercontent.com/26523062/179764137-13c14857-7ca5-4147-a9ad-338613d95db0.png)

## 如果将 @electron/remote 放到 dep 里面就会出现 dev 无法找到common模块报错，build报错说js和css无法找到文件
dev
![image](https://user-images.githubusercontent.com/26523062/179764514-bc896a2d-1d5f-47c9-be2a-0d3f2d81b7a2.png)
build
![image](https://user-images.githubusercontent.com/26523062/179764853-eab8bf35-5a89-4890-8ca4-85ee2337d7f9.png)

本人对前端的加载不是特别了解，麻烦大佬看看这个是不是就是某个配置的问题

代码地址 https://github.com/xemxx/markman/tree/vite vite分支

之前用的另外一个人的vue2模板没出现什么问题，是dev分支

**Comment by xemxx** [comment]
补充一下，是这样使用的
主线程
![image](https://user-images.githubusercontent.com/26523062/179766974-2f67ec99-199d-4943-9eb0-a75c376242a9.png)
![image](https://user-images.githubusercontent.com/26523062/179767041-674d88a5-bcd8-4a5c-9396-3e6ba5acad7e.png)
渲染线程
![image](https://user-images.githubusercontent.com/26523062/179767125-a05f9c0f-b3cd-4a05-b5ba-9d80ead775ed.png)

**Comment by caoxiemeihao** [comment]
@xemxx  提了个 PR 修了下问题 https://github.com/xemxx/markman/pull/4
