### ISSUE TITLE
开发环境正常运行，打包后出现报错信息。页面空白

### ISSUE THREAD

**Issue by wdzyy** [electron-vite/electron-vite-vue#196]
![image](https://user-images.githubusercontent.com/22287693/179917853-aea0f4fa-b9d6-4a39-accc-4b67aee09d7b.png)
在这个报错之前有提示找不到模块@vue/shared 、 @babel/parser、@vue/compiler-core、@vue/compiler-dom我依次安装之后，出现了上图的报错。我尝试继续安装source-map后，还会有其他的报错信息。大佬能帮忙看看为什么么
![image](https://user-images.githubusercontent.com/22287693/179919954-72616ab4-073e-4101-9c57-6b0db54e2fa7.png)

**Comment by wdzyy** [comment]
git@github.com:wdzyy/vite-vue3-ts-pinia-temp.git

**Comment by caoxiemeihao** [comment]
升级下 `vite-plugin-electron`  ![](https://img.shields.io/npm/v/vite-plugin-electron.svg)

**Comment by wdzyy** [comment]
> 升级下 `vite-plugin-electron` ![](https://camo.githubusercontent.com/9e50fcea46920c307d3f7e33edda0018ff4eee04cc0f985f136aa06ef928072f/68747470733a2f2f696d672e736869656c64732e696f2f6e706d2f762f766974652d706c7567696e2d656c656374726f6e2e737667)

感谢大佬，这个可行！
