### ISSUE TITLE
win环境下编译报错

### ISSUE THREAD

**Issue by HKMV** [electron-vite/electron-vite-vue#206]
> 报错信息如图

![image](https://user-images.githubusercontent.com/26456469/180631686-7226daa9-e398-49d7-989f-0a421b18bc58.png)

![image](https://user-images.githubusercontent.com/26456469/180631669-53a867f4-a6af-4300-8d11-008d804343e0.png)

**Comment by caoxiemeihao** [comment]
配置下 electron 镜像，自行百度

**Comment by HKMV** [comment]
> 

确定是镜像的问题吗? 运行是正常的.

**Comment by HKMV** [comment]
> 配置下 electron 镜像，自行百度

@caoxiemeihao 

![image](https://user-images.githubusercontent.com/26456469/180633400-413ea794-0735-4e29-ba03-ac20e3f224fa.png)

输出目录已经生产可执行文件了,但是编译终端一直报错

**Comment by HKMV** [comment]
> > 配置下 electron 镜像，自行百度
> 
> @caoxiemeihao
> 
> ![image](https://user-images.githubusercontent.com/26456469/180633400-413ea794-0735-4e29-ba03-ac20e3f224fa.png)
> 
> 输出目录已经生产可执行文件了,但是编译终端一直报错

已解决: 编译环境默认下载解压后的目录是随机目录名称,需要自己修改成对应版本的名称

**Comment by HKMV** [comment]
> > > 配置下 electron 镜像，自行百度
> > 
> > 
> > @caoxiemeihao
> > ![image](https://user-images.githubusercontent.com/26456469/180633400-413ea794-0735-4e29-ba03-ac20e3f224fa.png)
> > 输出目录已经生产可执行文件了,但是编译终端一直报错
> 
> ## 已解决:
> > 编译环境默认下载解压后的目录是随机目录名称, 导致执行时找不到指定的执行文件; 需要自己修改成对应版本的名称;
> > 应该是编译器的问题, 期待后期修复!!!
