### ISSUE TITLE
[Help] 在 electron/main 下对 process.env 使用点运算符导致编译后文件异常

### ISSUE THREAD

**Issue by SaberA1ter** [electron-vite/electron-vite-vue#210]
想给项目装上 eslint，在开启了 dot-notaion 下发现了一个编译上的问题。

原代码（electron/main/index）
``` const url = `http://${process.env['VITE_DEV_SERVER_HOST']}:${process.env['VITE_DEV_SERVER_PORT']}` ```

修改为
``` const url = `http://${process.env.VITE_DEV_SERVER_HOST}:${process.env.VITE_DEV_SERVER_PORT}` ```

编译过后（dist/electron/main/index）变成了
``` const url = `http://${{}.VITE_DEV_SERVER_HOST}:${{}.VITE_DEV_SERVER_PORT}`; ```

关于这块有什么解决办法吗，目前处理是关闭了 dot-notaion 保持原先 a['value'] 这类写法

**Comment by caoxiemeihao** [comment]
This behavior is caused by the `vite:define` plugin inside Vite.
A PR on this issue is currently under discussion.
https://github.com/vitejs/vite/pull/8843

*这个行为是由于 Vite 内部的 vite:define 插件引起的。关于这个问题的 PR 目前正在讨论中*
