### ISSUE TITLE
[Help] 2.0 template with vite3 build error

### ISSUE THREAD

**Issue by dongivan** [electron-vite/electron-vite-vue#211]
#### Describe the problem you confuse
I updated `vite@3`(and `plugin-vue@3`) on version 2.0 of this template, and everything works well in development environment.
However in production environment (which means built by electron-builder), the output index.js is broken. There would be a line like this
```js
const nl = "" + new URL("electron.fe1dfbad.png",Wn.url).href
```
And `Wn.url` would be `undefined`, so `new URL()` would throw an error.

FYI, I has updated `vite` and `plugin-vue` to version 3 on `electron-vite-vue@1.0`, and it works well in production environment.

**Comment by caoxiemeihao** [comment]
Thanks feedback :)
This is really a BUG in Vite 3.0. I'm considering submit an Issues or PR to Vite.

**Comment by dongivan** [comment]
Thx!

**Comment by dongivan** [comment]
Actually I "have updated vite and plugin-vue to version 3 on an **early version** electron-vite-vue@**2.0**, and it works well in production environment."
On that version the file `electron/preload/splash.ts` was like this (at the end of file):
```ts
const { appendLoading, removeLoading } = useLoading()
window.removeLoading = removeLoading
domReady().then(appendLoading)
```
And on current version the file is renamed to `electron/preload/index.ts` and the last few lines of codes are:
```ts
const { appendLoading, removeLoading } = useLoading()
domReady().then(appendLoading)

window.onmessage = ev => {
  ev.data.payload === 'removeLoading' && removeLoading()
}

setTimeout(removeLoading, 4999)
```

I don't know whether there were some other differences, but on that version `vite@3` works in production environment.

**Comment by dongivan** [comment]
Remove the `renderer: {}` in the config of `vite-plugin-electron` will fix this.
I would open another issue for this.

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-vue#-be-aware
