### ISSUE TITLE
[Bug] Error while tsconfig hot update

### ISSUE THREAD

**Issue by SaberA1ter** [electron-vite/electron-vite-vue#218]
## Reproduce

1. npm run dev
2. modify `tsconfig.json`
3. `ctrl + s` save file

Make sure the `tsconfig.json` file is OK. (e.g. add a newline at the end of the file, or remove a newline)

## Error

```
E:\code\electron-vite-vue\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:19958
        server.config.logger.info(`changed tsconfig file detected: ${changedFile} - Clearing cache and forcing full-reload to ensure typescript is compiled with updated config values.`, { clear: server.config.clearScreen, timestamp: true });
               ^

TypeError: Cannot read properties of null (reading 'config')
    at FSWatcher.reloadOnTsconfigChange (E:\code\electron-vite-vue\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:19958:16)
    at FSWatcher.emit (node:events:402:35)
    at FSWatcher.emitWithAll (E:\code\electron-vite-vue\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:47127:8)
    at FSWatcher._emit (E:\code\electron-vite-vue\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:47219:8)
    at listener (E:\code\electron-vite-vue\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:45779:20)
error Command failed with exit code 1.
```

**Comment by caoxiemeihao** [comment]
问题不大，我去给 Vite 提个 PR 😅

**Comment by caoxiemeihao** [comment]
**Here is a top-level server variable**

[vite/src/node/plugins/esbuild.ts#L34](https://github.com/vitejs/vite/blob/cd69358177dd3d93bc19084ad0ee09f6b85c047c/packages/vite/src/node/plugins/esbuild.ts#L34)

```ts
let server: ViteDevServer
```

**But it will be recycled**

[vite/src/node/plugins/esbuild.ts#L206-L209](https://github.com/vitejs/vite/blob/cd69358177dd3d93bc19084ad0ee09f6b85c047c/packages/vite/src/node/plugins/esbuild.ts#L206-L209)

```ts
    buildEnd() {
      // recycle serve to avoid preventing Node self-exit (#6815)
      server = null as any
    },
```

**When this is executed again, an error will occur**

[vite/src/node/plugins/esbuild.ts#L445-L448](https://github.com/vitejs/vite/blob/cd69358177dd3d93bc19084ad0ee09f6b85c047c/packages/vite/src/node/plugins/esbuild.ts#L445-L448)
```ts
    server.config.logger.info(
      `changed tsconfig file detected: ${changedFile} - Clearing cache and forcing full-reload to ensure TypeScript is compiled with updated config values.`,
      { clear: server.config.clearScreen, timestamp: true }
    )
```

---

Let' assume you're only building an App with calls to Vite, that's work fine.
But our App(electron-vite-vue) will build `electron/main/index.ts` and `electron/preload/index.ts` at the same time, which is equivalent to tow App.

When `electron/main/index.ts` is built, the `server` variable will be recycled, which will cause an error in reading properties on `server` when `electron/preload/index.ts` building

[vite.config.ts](https://github.com/electron-vite/electron-vite-vue/blob/main/vite.config.ts#L15-L27)

```ts
    electron({
      // First App
      main: {
        entry: 'electron/main/index.ts',
      },
      // Second App
      preload: {
        input: {
          index: join(__dirname, 'electron/preload/index.ts'),
        },
    }),
```

**Comment by caoxiemeihao** [comment]
Fixed by https://github.com/vitejs/vite/pull/11747
