### ISSUE TITLE
QQ/微信交流群 ٩(๑>◡<๑)۶

### ISSUE THREAD

**Issue by iiemos** [electron-vite/electron-vite-vue#222]
![image](https://user-images.githubusercontent.com/38515723/182793471-40c3f860-53b8-424a-940d-ef5deb571248.png)

**Comment by caoxiemeihao** [comment]
开放式建群，有想要建群讨论的均可在这个 issues 贴二维码！
*~~作者是个死宅，喜欢安静 🥺~~*
