### ISSUE TITLE
生产环境下pnpm run dev 页面空白

### ISSUE THREAD

**Issue by Allez-Gdy** [electron-vite/electron-vite-vue#226]
生产环境下页面空白，不报错，`win.loadURL(url)`也正确。build 打包之后项目如预期运行页面也正常，请问这是哪里出现问题？希望能得到帮助，谢谢~

> 项目接近尾声，想测试完整性，就从仓库重新拉取代码，pnpm install， pnpm run dev 后页面空白，pnpm run build 页面正常。
同样的代码，一直在开发者手中的代码生产环境下正常运行，从仓库拉取的代码有以上问题
直接没有渲染dom， 测试不是router 路由模式 问题，
![image](https://user-images.githubusercontent.com/64739670/183329243-e65a2133-47b2-44a8-af71-efdef0675ad7.png)

**Comment by yi-Xu-0100** [comment]
1. 是不是开了一些类似GPU加速/软件加速的工具
2. powershell 输入 `node --eval="console.log(process.env.NODE_ENV)"` 看下输出是不是 `development`

**Comment by Allez-Gdy** [comment]
> 1. 是不是开了一些类似GPU加速/软件加速的工具
> 2. powershell 输入 看下输出是什么？`node --eval="console.log(process.env.NODE_ENV)"`

输出undefined

**Comment by yi-Xu-0100** [comment]
@Allez-Gdy 个人只是看到有 electron 应用出现白屏的 issue ，可能不是这个原因，你可以试试分别使用 `SET NODE_ENV=production` 和 `SET NODE_ENV=development`，这两种情况下试试软件情况。

**Comment by caoxiemeihao** [comment]
试试这个
https://pnpm.io/zh/npmrc#shamefully-hoist

**Comment by Allez-Gdy** [comment]
试了下这个，还是不行。现在还不清楚是哪里的问题，没有显式地报错 无从下手，没有遇到过类似情况，我想应该就是vite 或者 依赖包 的问题（大概率是依赖包），想用最笨的办法新建个项目，一点一点移植。

**Comment by caoxiemeihao** [comment]
不行就用 npm、yarn。别给自己找麻烦

**Comment by Allez-Gdy** [comment]
@caoxiemeihao 试过npm、yarn 了，还是不行，应该是我自己代码的低级问题，谢谢你的回答～
