### ISSUE TITLE
两天前更新的版本有npm install 之后跑不起来

### ISSUE THREAD

**Issue by ike-HJ** [electron-vite/electron-vite-vue#227]
![image](https://user-images.githubusercontent.com/38515723/183336521-39c17ddc-f5ad-4939-a78c-844079d04504.png)

**Comment by caoxiemeihao** [comment]
😅 问题不大。下午修复

**Comment by ike-HJ** [comment]
Ojbk



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 草鞋没号 ***@***.***&gt;
发送时间: 2022年8月8日 12:44
收件人: electron-vite/electron-vite-vue ***@***.***&gt;
抄送: ike ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [electron-vite/electron-vite-vue] 两天前更新的版本有npm install 之后跑不起来 (Issue #227)





 
😅 问题不大。下午修复

**Comment by caoxiemeihao** [comment]
You can upgrading to `v0.8.6`
