### ISSUE TITLE
[Help] build后应用白屏

### ISSUE THREAD

**Issue by DDDHL** [electron-vite/electron-vite-vue#229]
#### Describe the problem you confuse
history模式白屏无报错，hash白屏报错如下，怎么解决？
![image](https://user-images.githubusercontent.com/71803866/183618954-a6b29137-0b7c-43ed-8358-cccbc8a153a4.png)

**Comment by DDDHL** [comment]
DataExchange是路由‘/’的组件

**Comment by caoxiemeihao** [comment]
给下 Demo

**Comment by DDDHL** [comment]
路径和组件名字没出错，只有一个组件，在dev下正常显示，在build后打开应用出现上述问题。
![image](https://user-images.githubusercontent.com/71803866/183792114-4e061e12-b3ef-4377-aae2-61a6f94f9c13.png)

**Comment by caoxiemeihao** [comment]
推个仓库到 github 上来可好？

**Comment by HaoAu3** [comment]
同样报了类似的错

Error: Cannot find module './home.af855b02.js'
Require stack:
- C:\Users\Administrator\AppData\Local\Programs\electron-vue-vite\resources\app.asar\dist\index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at i._resolveFilename (node:electron/js2c/renderer_init:33:1095)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at index.b8ba64b0.js:12:22647

**Comment by DDDHL** [comment]
> 推个仓库到 github 上来可好？

https://github.com/DDDHL/electron-vite-ts-demo

**Comment by HaoAu3** [comment]
解决了，是vue-router动态加载的问题，
只需要把
router/index.ts中，
component: () => import('@/views/home.vue')
 
改为
import home from '@/views/home.vue'
component: home
 
另外，我因为 pinia的缘故，
所以只做了上面的一步还不能解决问题，
第二步是，把main.ts拆分成下面两个文件，
pre.ts
import { createApp } from 'vue'
import App from './App.vue'
// import './samples/node-api'

import { createPinia } from 'pinia'
import 'element-plus/theme-chalk/el-message.css'
import 'element-plus/theme-chalk/el-message-box.css'

export const data = createApp(App).use(createPinia())

 
main.ts
import { data } from './pre'
import router from './router'
data
  .use(router)
  .mount('#app')
  .$nextTick(() => {
    postMessage({ payload: 'removeLoading' }, '*')
  })

**Comment by caoxiemeihao** [comment]
> 解决了，是vue-router动态加载的问题，

`import('@/views/home.vue')` 还是要解决的，很多人喜欢这么写。我下午看一下，感谢你的代码 👍

**Comment by caoxiemeihao** [comment]
@DDDHL 先按照图片的方式配置下，BUG 我下午会修复
<img width="152" alt="image" src="https://user-images.githubusercontent.com/26263658/183827905-0be9a168-df33-4a05-b8c3-204627745d78.png">
