### ISSUE TITLE
[Help] vue-i18n 打包出错 file name too long

### ISSUE THREAD

**Issue by Liszt-Fly** [electron-vite/electron-vite-vue#230]
在安装了vue-i18n之后，直接进行打包，会出现错误，报错信息如下:

![dIpISn](https://mikes.oss-cn-beijing.aliyuncs.com/uPic/dIpISn.png)

**Comment by caoxiemeihao** [comment]
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/26263658/183780274-44ce37fa-1ece-426e-8162-75ffef8a7778.png">
你用了什么包管理工具，看起来安装包有问题啊。

**Comment by Liszt-Fly** [comment]
已经解决 我使用的cnpm打包工具 换成了pnpm了之后就没问题了，非常感谢！
