### ISSUE TITLE
build以后子页面图片路径不正确

### ISSUE THREAD

**Issue by ESOOOOOOOO** [electron-vite/electron-vite-vue#232]
静态图片资源放在src/assets中，App.vue页面取图片资源用'./assets/imageName.png'能取到，components中的vue页面不管用什么方式都获取不到，包括将图片放在public下。

**Comment by caoxiemeihao** [comment]
提供个 Demo 到 github 上来可好？

**Comment by ESOOOOOOOO** [comment]
问题解决了，就是createRouter的位置，之前是
history: process.env.IS_ELECTRON ? createWebHashHistory(process.env.BASE_URL) : createWebHashHistory(process.env.BASE_URL),
现在改成了
history: createWebHashHistory(process.env.BASE_URL),

**Comment by ESOOOOOOOO** [comment]
之前是history: process.env.IS_ELECTRON ? createWebHashHistory(process.env.BASE_URL) : createWebHistory(process.env.BASE_URL),
打错
