### ISSUE TITLE
vite使用fs模块功能

### ISSUE THREAD

**Issue by wdzyy** [electron-vite/electron-vite-vue#234]
![image](https://user-images.githubusercontent.com/22287693/183840084-da5b9f46-e149-422f-be2e-d2a12f79655d.png)
  我看39行有配置node API的能力，请问该怎么配置呢？

**Comment by wdzyy** [comment]
![image](https://user-images.githubusercontent.com/22287693/183840898-70c68f0e-5d1c-4248-acfe-6d3ba5208411.png)
大佬，这个报错，需要怎么配呢？

**Comment by wdzyy** [comment]
我使用了fs.proms的擦件，用了原生的fs就行。

**Comment by caoxiemeihao** [comment]
`fs.promise` 可以用 `fs/promise` 代替
自定义 Node.js 包可以配置
```js
renderer: {
  resolve: () => ['fs.promise'],
},
```
