### ISSUE TITLE
build 之后空白页面，dev环境正常

### ISSUE THREAD

**Issue by wdzyy** [electron-vite/electron-vite-vue#235]
#229 按照这个升级"vite-plugin-electron": "^0.8.7" 还是打包白屏，还是只能以下图的方式打包才能有正常。
![image](https://user-images.githubusercontent.com/22287693/184050815-c8c26cca-03da-448e-b93f-d1c8f8e4e524.png)

**Comment by caoxiemeihao** [comment]
#236
