### ISSUE TITLE
mqtt打包后报错

### ISSUE THREAD

**Issue by wdzyy** [electron-vite/electron-vite-vue#236]
mqtt 安装在dependencies，dev环境正常，打包后报错。
![image](https://user-images.githubusercontent.com/22287693/184051021-5ac64150-9a84-49ab-b80e-2090b1696e5b.png)

**Comment by caoxiemeihao** [comment]
```
renderer: {
  resolve: () => ['mqtt'],
}
```

**Comment by wdzyy** [comment]
> ```js
> renderer: {
>     resolve: () => ['mqtt'],
>   },
> ```

也是一样不行呢

**Comment by wdzyy** [comment]
#235 这个问题应该怎么处理呢？我也升级到0.8.7了的

**Comment by caoxiemeihao** [comment]
不行就给个 Demo

**Comment by wdzyy** [comment]
> 不行就给个 Demo

git@github.com:wdzyy/electon-demo.git

**Comment by caoxiemeihao** [comment]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/26263658/184077468-2c09d8f4-bf98-4158-ae80-4c2ee9c39644.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/26263658/184077499-404e7e8b-29d5-4897-9803-e8bac15388bf.png">

**Comment by wdzyy** [comment]
> <img alt="image" width="594" src="https://user-images.githubusercontent.com/26263658/184077499-404e7e8b-29d5-4897-9803-e8bac15388bf.png">
> 
> <img alt="image" width="795" src="https://user-images.githubusercontent.com/26263658/184077468-2c09d8f4-bf98-4158-ae80-4c2ee9c39644.png">
> 
> <img alt="image" width="786" src="https://user-images.githubusercontent.com/26263658/184077590-876805cb-2f93-4165-86dd-8ca5b164be9a.png">

打包之后还是提示mqtt的问题。

**Comment by caoxiemeihao** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/26263658/184084177-e1ff02d2-8e3e-4b90-ac72-db71b3b071df.png">

你排除下你写法错误吧，我这没有 mqtt 的问题

**Comment by wdzyy** [comment]
> <img alt="image" width="800" src="https://user-images.githubusercontent.com/26263658/184084432-77dcce3f-b293-440e-b5d8-a7999d9662a3.png">
> 
> 你排除下你写法错误吧，我这没有 mqtt 的问题

这个截图是打包之后的么？如果是的话我就自己检查下为什么吧。因为我这边打包之后都没法进入界面，直接报错提示了

**Comment by caoxiemeihao** [comment]
是打包后的截屏。
无法进入页面是主进程文件加载路径有问题。如果是渲染进程文件加载路径问题，错误会出现在 DevTools 中。

**Comment by wdzyy** [comment]
> 法进入页面是主进程文

谢谢哥，能否把改过的demo传到我的git呢？

**Comment by caoxiemeihao** [comment]
我给你提个 PR

**Comment by wdzyy** [comment]
> 我给你提个 PR

哥，PR提了么

**Comment by caoxiemeihao** [comment]
晚点，吃口饭

**Comment by wdzyy** [comment]
> 晚点，吃口饭

辛苦哥，感谢！

**Comment by caoxiemeihao** [comment]
https://github.com/wdzyy/electon-demo/pull/1

**Comment by wdzyy** [comment]
> [wdzyy/electon-demo#1](https://github.com/wdzyy/electon-demo/pull/1)

哥，你用的是什么版本的node？是mac系统吗？我windows和mac系统用的v16的node，打包还是一样报错。同样的demo，我就打包后报错呢。

**Comment by caoxiemeihao** [comment]
Mac
