### ISSUE TITLE
[Help] 项目添加 vue-router 使用路由懒加载，关闭nodeIntegration，打包后无法显示页面

### ISSUE THREAD

**Issue by ksBking** [electron-vite/electron-vite-vue#239]
项目添加 vue-router 使用路由懒加载，关闭electron的nodeIntegration，打包后无法显示页面，报错require未定义，但dev时正常，
打开electron的nodeIntegration就可以了，但我想关闭这个。

**Comment by caoxiemeihao** [comment]
关闭 `nodeIntegration` 就不要在渲染进程中使用 `import { ipcRenderer } from 'electron'`
