### ISSUE TITLE
[Help] 关于构建之后部分依赖发生异常的问题

### ISSUE THREAD

**Issue by xiaowuyaya** [electron-vite/electron-vite-vue#243]
目前在用electron-vite-vue重构之前的一个项目，其中有引入一个包 [league-connect](https://github.com/matsjla/league-connect)
其中有一个方法会创建一个websocket监听，在我之前的项目中是可以正常使用的。
但我在主进程中创建时，总是失效，debug后发现是其中的ws库抛出了个错误：ws does not work in the browser
这个是我从未见过的错误。
我查询资料后，在[这里](https://github.com/websockets/ws/issues/1459)，似乎可以了解到，这个方法中调到ws库后，被识别成在渲染进程中执行。
但我是在主进程中运行的，是否是我vite的配置有缺少，麻烦大大解答。

```js
// main.ts
app.whenReady().then(async () => {
  await initApp()
  const credentials = appConfig.get<any>('credentials');
  const r = await createWebSocketConnection(credentials);
  console.log(r);  
  app.on('activate', async () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      mainWindow = await createMainWindow(preload)
    }
  })
})
```

```js
// vite.config.ts
electron({
      main: {
        entry: 'app/main/index.ts',
        vite: withDebug({
          build: {
            outDir: 'dist/app/main',
          },
        }),
      },
      preload: {
        input: {
          // You can configure multiple preload here
          index: join(__dirname, 'app/preload/index.ts'),
        },
        vite: {
          build: {
            // For Debug
            sourcemap: 'inline',
            outDir: 'dist/app/preload',
          },
        },
      },
      renderer: {
        resolve() {
          return ['electron-store','league-connect']
        },
      },
    }),
    renderer({
      resolve() {
        return ['getmac','league-connect']
      }
    })
  ],
```

**Comment by caoxiemeihao** [comment]
提供下复现 Demo

**Comment by yxswy** [comment]
我猜测可能是 league-connect 这个包的问题，你尝试把他的包在你本地打包起来之后手动复制到 node_module 里面，看看可不可以，如果他的还是不可以，可以试试我的 https://github.com/yxswy/league-connect

最后：我想 league-connect 这个包的功能可以不需要放在你的 vue 项目里面，而是使用通信调用 ipcRenderer 触发 ipcMain.on

**Comment by caoxiemeihao** [comment]
你把 `league-connect` 放到 `dependenices` 中，然后再 Main 中调用试试。
https://github.com/electron-vite/vite-plugin-electron/blob/74cb63056c987e4d0961158e9544bb4ecd14b951/packages/electron/src/config.ts#L74-L77

**Comment by xiaowuyaya** [comment]
> 你把 `league-connect` 放到 `dependenices` 中，然后再 Main 中调用试试。
> 
> ```ts
> /**
>  * `dependencies` of package.json will be inserted into `build.rollupOptions.external`
>  */
> export function createWithExternal(runtime: Runtime) {
> ```
> 
> https://github.com/electron-vite/vite-plugin-electron/blob/74cb63056c987e4d0961158e9544bb4ecd14b951/packages/electron/src/config.ts#L74-L77

你好， 我将`league-connect`放到`dependences`中之后还是发生之前的问题。
项目demo在[这里](https://github.com/xiaowuyaya/tik/tree/v_3.2.0_beta)，但是这个项目需要在 `英雄联盟游戏客户端`启动的时候才回调用这个方法

**Comment by xiaowuyaya** [comment]
> 我猜测可能是 league-connect 这个包的问题，你尝试把他的包在你本地打包起来之后手动复制到 node_module 里面，看看可不可以，如果他的还是不可以，可以试试我的 https://github.com/yxswy/league-connect
> 
> 最后：我想 league-connect 这个包的功能可以不需要放在你的 vue 项目里面，而是使用通信调用 ipcRenderer 触发 ipcMain.on

感谢您的回答，我将源代码复制到我项目中后通过编译可以正常执行了，但是有个小插曲，在项目运行时会报错`self signed certificate in certificate chain`，可以通过process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"， 但这种方法似乎并不安全，是否有别的方式解决。

另外，这个问题的发生是什么导致的呢，是我vite配置的有问题的吗？

**Comment by yxswy** [comment]
Nodejs 版本号是多少，跑起你的项目十分艰难

**Comment by yxswy** [comment]
![image](https://user-images.githubusercontent.com/44958959/186053289-1565109c-a0ea-4af7-8195-c201105a775f.png)
我想死

**Comment by xiaowuyaya** [comment]
> ![image](https://user-images.githubusercontent.com/44958959/186053289-1565109c-a0ea-4af7-8195-c201105a775f.png) 我想死

很抱歉，上面发的demo项目是在`v_3.2.0_beta`分支中， node版本为 v16.16.0， 我看你跑应该是主分支的代码，正是准备迁移到electron-vite-vue的项目...

**Comment by yxswy** [comment]
![image](https://user-images.githubusercontent.com/44958959/186063106-a25408d4-ae0e-4e52-aecf-bf6cc995ab16.png)
这台电脑没有 lol，所以我只能猜猜是这个空格的问题

**Comment by xiaowuyaya** [comment]
> ![image](https://user-images.githubusercontent.com/44958959/186063106-a25408d4-ae0e-4e52-aecf-bf6cc995ab16.png) 这台电脑没有 lol，所以我只能猜猜是这个空格的问题

目前这个分支的代码已经可以正常运行了，league-connect这个库在npm install的时候用不了，按你说的直接引入是可以使用的- - ，  这原本的代码是fs到根路径去readSync这个.pem文件，文件老是编译不到dist中，被我改写成了这样是能正常运行的。

**Comment by yxswy** [comment]
好吧，前面的空格去掉尝试过可以吗，是否还报这个错误 self signed certificate in certificate chain

**Comment by xiaowuyaya** [comment]
> 好吧，前面的空格去掉尝试过可以吗，是否还报这个错误 self signed certificate in certificate chain

谢谢 确实是这个空格的原因，去掉之后不会在显示这个问题了`self signed certificate in certificate chain`
