### ISSUE TITLE
[Help] contextIsolation设置为 true，报错 "require is not defined"

### ISSUE THREAD

**Issue by CzyYYDS** [electron-vite/electron-vite-vue#245]
大佬，我现在想在 preload.ts里给contextBridge添加一些全局事件，所以把contextIsolation设为 true，但是报错require is not defined，请问有解决方案吗

**Comment by CzyYYDS** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/20142847/185862135-7fdd36aa-3401-4974-a3ae-5740e772ff7d.png">

**Comment by CzyYYDS** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/20142847/185862219-f34fb362-17fd-4405-9410-b6cefa3c34e7.png">

**Comment by caoxiemeihao** [comment]
你没在主进程中开 `nodeIntegration: true`，你告诉我怎么再渲染进程中使用 `import {} from 'electron'`？

**Comment by CzyYYDS** [comment]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/20142847/185869349-1b757a9f-354d-4b8b-a42c-f18822c9d3f1.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/20142847/185869421-48f59831-294b-40c9-8ac1-de6cd657b27b.png">
感谢大佬回复   我看nodeIntegration已经设置了？  如图，我在 preload中使用contextBridge.exposeInMainWorld就会报错，大佬能救救弟弟吗

**Comment by caoxiemeihao** [comment]
渲染进程没有 `electron` 对象，你需要写 `contextBridge.exposeInMainWorld(window, { ipcRenderer })`

**Comment by 810505339** [comment]
![image](https://user-images.githubusercontent.com/50100966/222071770-107ae5db-30fc-44b5-894c-9baf148cd277.png)

只要修改```contextIsolation：true``` 或者修改 ```nodeIntegration:false``` 就会出现这个错误
