### ISSUE TITLE
[Help] crypto is not defined 在主进程(in main process)

### ISSUE THREAD

**Issue by Kenhuey** [electron-vite/electron-vite-vue#246]
![image](https://user-images.githubusercontent.com/57590797/186120875-962fad3a-f65f-438d-8290-a4ced3eae58f.png)

用 uuidv4/nanoid 这种库的话他们需要调用 crypto 都会报类似的错误
这个错误只会在主进程报，在渲染进程正常运行

[复现仓库 main 分支](https://github.com/Kenhuey/mas.tbt4w)

在原生 Electron 程序的主进程也是能正常使用的，这个是否跟 rollup plugin 或者 vite 的配置有关系，应该如何解决，万分感谢^ ^

**Comment by caoxiemeihao** [comment]
​    ​放到 dependencies 中

**Comment by Kenhuey** [comment]
> ​    ​放到 dependencies 中

这样做了还是会出现相同的问题 
```
"dependencies": {
    "@types/crypto-js": "^4.1.1",
    "crypto-js": "^4.1.1",
    "nanoid": "^4.0.0"
},
```

只用 crypto 不用库也会出现这个问题
```
console.log(crypto.randomUUID()); /* test */
```

如果是手动引用一下再调用就没问题了
```
import crypto from "crypto";
console.log(crypto.getHashes()); /* test */
```

解决方法1：手动造轮子
解决方法2：改本地库文件或者改好了frok一份再引用
