### ISSUE TITLE
[Help] electron 和 src 内都需要用到公共函数，放在同级目录，vue 内 import 引入报错

### ISSUE THREAD

**Issue by CzyYYDS** [electron-vite/electron-vite-vue#247]
#### 
<img width="595" alt="image" src="https://user-images.githubusercontent.com/20142847/186355521-e140328b-61ba-4158-847e-68157ddfbb6a.png">
<img width="783" alt="image" src="https://user-images.githubusercontent.com/20142847/186355881-7dc72089-61ba-43a1-be0f-7cb8a8b22288.png">

**Comment by CzyYYDS** [comment]
<img width="732" alt="image" src="https://user-images.githubusercontent.com/20142847/186355992-7b11f459-88f8-4fac-8d08-d3b6df1aff45.png">

**Comment by caoxiemeihao** [comment]
<img width="783" alt="image" src="https://user-images.githubusercontent.com/20142847/186355881-7dc72089-61ba-43a1-be0f-7cb8a8b22288.png">
渲染进程用到了 fs 模块
