### ISSUE TITLE
请教一下webview怎么通信

### ISSUE THREAD

**Issue by ike-HJ** [electron-vite/electron-vite-vue#249]
webview加载preload
    <webview
      height="100%"
      id="wikifxWeb"
      nodeintegration
      preload="D:\test-electron\dist\electron\preload\index.js"
      class="web_view"
      src="http://192.168.18.137:61593"
    />
-----------------------------------------------
preload.ts
import { ipcRenderer } from 'electron'
// Window拓展属性
declare global {
  interface Window {
    $ipcRenderer: any
  }
}
global.window.$ipcRenderer = ipcRenderer

webview上面打印window 没有 $ipcRenderer 这个属性，通信不了呀，有大佬用过吗，怎么整，求助

**Comment by caoxiemeihao** [comment]
模板默认可以在渲染进程用直接引入 ipcRenderer

**Comment by ike-HJ** [comment]
> 模板默认可以在渲染进程中直接引入 ipcRenderer
项目内的.vue可以直接使用，加载外部的网页怎么使用
    <webview
      height="100%"
      id="wikifxWeb"
      nodeintegration
      preload="D:\test-electron\dist\electron\preload\index.js"
      class="web_view"
      src="http://192.168.18.137:61593"
    />

**Comment by ike-HJ** [comment]
> 模板默认可以在渲染进程中直接引入 ipcRenderer

    \<\webview
      height="100%"
      id="wikifxWeb"
      nodeintegration
      preload="D:\wikifx-electron\dist\electron\preload\index.js"
      class="web_view"
      src="http://192.168.18.137:61593"
    \>\

**Comment by caoxiemeihao** [comment]
外部网页可以通过 postMessage 通讯，毕竟两个页面不是同一个 js 环境

**Comment by ike-HJ** [comment]
> 外部网页可以通过 postMessage 通讯，毕竟两个页面不是同一个 js 环境

额.....那就是webview 使用不了ipcRenderer了？

**Comment by caoxiemeihao** [comment]
硬模拟可以去百度一下
