### ISSUE TITLE
naive-ui打包报错

### ISSUE THREAD

**Issue by xxxace** [electron-vite/electron-vite-vue#250]
使用naive-ui开发环境正常使用，一打包就报错。
大佬帮帮忙看下是什么问题。
![image](https://user-images.githubusercontent.com/60084325/186855569-91590a3b-eee7-448a-ba61-0f79167318fa.png)

![~P@J3%_}Y73 1}7S M%$7ZJ](https://user-images.githubusercontent.com/60084325/186855355-57e50a6c-51c7-4b49-9954-a69eb466e003.png)

**Comment by caoxiemeihao** [comment]
提供下 Demo

**Comment by xxxace** [comment]
@caoxiemeihao 很感谢大佬第一时间回复，我在弄DEMO的时候发现没问题，我把出错项目的vite.config.ts中的resolve.extensions里面的 ['.d.ts'] 除掉就好了，很懵...

**Comment by caoxiemeihao** [comment]
> @caoxiemeihao 很感谢大佬第一时间回复，我在弄DEMO的时候发现没问题，我把出错项目的vite.config.ts中的resolve.extensions里面的 ['.d.ts'] 除掉就好了，很懵...

`'.d.ts'` 对于打包器来说是空文件
