### ISSUE TITLE
[Help] vite 引入动态图片打包后找不到资源，开发环境下可以

### ISSUE THREAD

**Issue by CzyYYDS** [electron-vite/electron-vite-vue#251]
<img :src="imgPath" />

const imgPath = new URL('../../assets/imgs/icon.png', import.meta.url).href

![image](https://user-images.githubusercontent.com/20142847/187142035-94af9357-b912-48d4-8753-85cca1e1d235.png)

**Comment by caoxiemeihao** [comment]
`assets` 中的任何资源都使用 `import` 导入
