### ISSUE TITLE
I can import electron-store in dev, but getting an error in prod.

### ISSUE THREAD

**Issue by fEyebrow** [electron-vite/electron-vite-vue#253]
I want to use electron-store in node and web.

I can use electron-store in dev, but getting an error in prod.

When I import it this way
```
renderer: {
      resolve() {
        return ['electron-store']
      }
   }

dependencies: {
   "electron-store": "^8.1.0"
}

```

I got an error in prod:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/18180417/188863539-44e8d52a-06c9-447a-bc04-621e31390d8b.png">

when I import it this way
```
renderer: {
      resolve() {
        return ['electron-store']
      }
   }

devDependencies: {
   "electron-store": "^8.1.0"
}

```
I got an error in prod:
Cannot find module 'electron-store'

**Comment by caoxiemeihao** [comment]
If you use `electron-store` in Electron Renderer

```js
renderer: {
    resolve(builtins) {
      return [...builtins, 'electron-store']
    }
 }
```

**Comment by fEyebrow** [comment]
Put electron-store in dependencies or devDependencies? @caoxiemeihao 
I put electron-store in devDependencies and edited the render.resolve follow you.
But I got this:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/18180417/189017838-5a0b4f05-6b74-4798-8920-edeeab3f2e8c.png">

**Comment by fEyebrow** [comment]
I put electron-store in dependencies and got this:
<img width="231" alt="image" src="https://user-images.githubusercontent.com/18180417/189018545-76826dcb-0858-4285-b1c4-568b0ce51d0d.png">

**Comment by caoxiemeihao** [comment]
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/26263658/189044029-cd581d9d-ecea-4e77-8f28-a6649449d425.png">

You can see 👉 [dependencies vs devDependencies](https://github.com/electron-vite/vite-plugin-electron/tree/main/packages/electron-renderer#dependencies-vs-devdependencies)

**Comment by fEyebrow** [comment]
this is a minimal reproduction demo:
https://github.com/fEyebrow/notification-electron
@caoxiemeihao

**Comment by caoxiemeihao** [comment]
```sh
npm i
# or
yarn
# or
pnpm i --shamefully-hoist
```

**Comment by fEyebrow** [comment]
thanks @caoxiemeihao
