### ISSUE TITLE
[Help] Use Pinia

### ISSUE THREAD

**Issue by GuoBoy** [electron-vite/electron-vite-vue#254]
#### Error
When I use the Pinia, the vscode tell me that it can't find pinia declare file.

I try to run 

> pnpm i @types/pinia

but it's not found.

**Comment by caoxiemeihao** [comment]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/26263658/188882156-a79d0071-20d1-4648-8123-5bc8ad4c7f71.png">
Everything looks OK!

**Comment by GuoBoy** [comment]
> <img alt="image" width="549" src="https://user-images.githubusercontent.com/26263658/188882156-a79d0071-20d1-4648-8123-5bc8ad4c7f71.png">
> 
> Everything looks OK!

Oh,yes. I recreate the project and it become OK!  Mybe something is wrong!
Thank you!
