### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by vikt20** [electron-vite/electron-vite-vue#256]
Hello!
First of all thank You for the great package.
I got problem when I run command `npm run dev`
The electron window loads and everything is fine, but when I try to access through browser by http://localhost:5173/ I got this error: Uncaught ReferenceError: require is not defined.

my code is default:

```
win = new BrowserWindow({
  title: 'Main window',
  icon: join(ROOT_PATH.public, 'favicon.ico'),
  webPreferences: {
    preload,
    // Warning: Enable nodeIntegration and disable contextIsolation is not secure in production
    // Consider using contextBridge.exposeInMainWorld
    // Read more on https://www.electronjs.org/docs/latest/tutorial/context-isolation
    nodeIntegration: true,
    contextIsolation: false
    
  },
```

**Comment by caoxiemeihao** [comment]
Doesn't work in the browser because you use
```js
import { ipcRenderer } from 'electorn'
```
This means you are using the NodeJs API.
