### ISSUE TITLE
[Help] hope electron can use different env file by different stage

### ISSUE THREAD

**Issue by ChangeDavidD** [electron-vite/electron-vite-vue#261]
您好，我的专案从vue cli+electron 转成 vite+electron 遇到了关于环境变数档案的问题。
问题是如果我输入 ```vite --mode beta``` 的话：
结果在renderer中可以吃到 .env.beta档案，但是 main中吃不到 .env.beta。

所以我想到另一种解决问题的方式:
我在 main 手动加入特定的 env.stage
```dotenv.config({ path: join(process.env.DIST,`../.env.${ process.env.NODE_ENV }`) })```
并且输入```NODE_ENV=beta vite --mode beta``` 
结果可以在main中吃到 .env.beta

但是我打包```NODE_ENV=development vue-tsc --noEmit && vite build --mode development && electron-builder```完后
并开启档案发现 renderer 可以吃到 .env.development，不过main 还是吃不到.env.beta
原因是打包完 process.env.NODE_ENV 是 undefined。

请问有办法顺利 在main跟renderer 中吃到 .env.stage 档案吗？
谢谢你，以下是我最简洁的范本
https://github.com/ChangeDavidD/vite-electron-env
![截圖 2022-09-20 上午11 26 22](https://user-images.githubusercontent.com/113867114/191160841-07842cba-cf7e-44f6-876e-96c6b28ee08b.png)

**Comment by caoxiemeihao** [comment]
在 `vite.config.ts` 中添加下

```diff
electron({
  main: {
    entry: 'electron/main/index.ts',
    vite: {
+     mode: 'beta',
      build: {
        // For Debug
        sourcemap: true,
        outDir: 'dist/electron/main',
      },
      // Will start Electron via VSCode Debug
      plugins: [process.env.VSCODE_DEBUG ? onstart() : null],
    },
  },
})
```

**Comment by ChangeDavidD** [comment]
我照您的方式在 ```vite.config.ts``` 中添加 ```mode: 'beta'```
並且執行 ```npx vite --mode beta```
在 main 中的 process.env.NODE_ENV 還是 undiefined
github demo:https://github.com/ChangeDavidD/vite-electron-env/commit/0f7ada8ec00a20aba15aaee0a53a305e521f813a

**Comment by ChangeDavidD** [comment]
我有方法解决我的问题(虽然不太好看)
使用```@rollup/plugin-replace``` 套件 把 ```'process.env.NODE_ENV'``` 转换成 ```'development/beta/production'```
如
```
import replace from "@rollup/plugin-replace";

rmSync('dist', { recursive: true, force: true }) // v14.14.0

// https://vitejs.dev/config/
export default ({ mode }) => {
  return defineConfig({
    plugins: [
      vue(),
      electron({
        main: {
          entry: 'electron/main/index.ts',
          vite: {
            mode: 'beta',
            build: {
              // For Debug
              sourcemap: true,
              outDir: 'dist/electron/main',
            },
            // Will start Electron via VSCode Debug
            plugins: [process.env.VSCODE_DEBUG ? onstart() : null,
            replace({
              "process.env.NODE_ENV": JSON.stringify(mode),
              preventAssignment: true,
            }),
            ],
          },
```
经过测试使用以下两种指令
```
vite --mode beta
or
NODE_ENV=development vue-tsc --noEmit && vite build --mode beta && electron-builder
```
可以顺利得到我想要的结果(process.env.NODE_ENV 有值)
![截图 2022-09-21 下午5 12 43](https://user-images.githubusercontent.com/113867114/191465148-67360abb-745b-41dd-b6c6-4ba385962951.png)

不过希望之后可以不透过这些处理并且可以在main 引用 .env. stage(像是使用``` vite --mode beta``` 可以在 renderer 跟 main 中引入 .env.beta档案)
谢谢^^
