### ISSUE TITLE
[Bug] Blank screen when renderer process files have breakpoints before starting debug session

### ISSUE THREAD

**Issue by FINDarkside** [electron-vite/electron-vite-vue#262]
I get blank window when I start debugging app while already having breakpoints in some renderer files. Debugging only works if I launch debugging without breakpoints and add them after starting the session. Reproducible with fresh project at least on my Windows 10 machine.

**Comment by FINDarkside** [comment]
Ok I was dumb, I was supposed to use the "debug app" I think. I did however notice that when I have breakpoints when launching debugging I get blank window with no errors in dev console nor debug console. But everything works when I add breakpoints after launch.

**Comment by caoxiemeihao** [comment]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/26263658/193162843-9ad36982-1bed-41c2-9682-31a73ccf18d2.png">

**Comment by FINDarkside** [comment]
To be clear I'm not hitting any breakpoints, the app just does not load if you have breakpoints anywhere. Even if the breakpoints are in dead code.

**Comment by FINDarkside** [comment]
> Are you sure enabled sourceMap？Or did you change something?

I can reproduce this in clean electron-vite-vue project by just adding this to `App.vue` and adding breakpoint inside the function before clicking "debug app".
```TypeScript
function asd(){
  console.log('this will never be called')
}
```
That function is never called so it's just the precence of breakpoint that causes the app that opens to look like this:
<img src="https://i.gyazo.com/2f10156dfa8f64d84d0a241b5773f161.png">

There's some error in renderer log about CSP and failing to fetch `devtools://devtools/bundled/entrypoints/main/main.js:1:4722` but those are logged also when the app works just fine. The only thing that differs in the logs is that this error is not logged when you have breakpoints and the app doesn't work:
```
Electron Security Warning (Node.js Integration with Remote Content) This renderer process has Node.js integration enabled
    and attempted to load remote content from 'http://127.0.0.1:3344/'. This
    exposes users of this app to severe security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.

```

**Comment by FINDarkside** [comment]
Might be just a Windows issue then, or even something more specific, I don't know 🤷‍♂️
