### ISSUE TITLE
win10打包，图片资源路径问题

### ISSUE THREAD

**Issue by Liupeng8** [electron-vite/electron-vite-vue#263]
请看下面两张图
![1](https://user-images.githubusercontent.com/23046680/192762839-93d65074-cb4d-436d-bd27-d9a5cae8e0a0.png)
![2](https://user-images.githubusercontent.com/23046680/192762901-32d66a07-10b7-4c3a-989d-25ca2869fbc6.png)

**Comment by caoxiemeihao** [comment]
去 electron-builder 那边看看有没有相关的 issues
