### ISSUE TITLE
[Bug] Missing electron env variables in VS Code debug mode

### ISSUE THREAD

**Issue by PackagedCat** [electron-vite/electron-vite-vue#264]
When running the application through debugging via Visual Studio Code, the application lacks some environment variables associated with electron, for example `process.env.INIT_CWD`. If run the application through `npm run dev`, then this variable is present.

**Comment by caoxiemeihao** [comment]
<img width="410" alt="image" src="https://user-images.githubusercontent.com/26263658/193162953-25eb065e-5553-493a-9792-5091b9253c00.png">

---

<img width="729" alt="image" src="https://user-images.githubusercontent.com/26263658/193162983-eb4859f4-d791-4f30-a037-ea36569edceb.png">
