### ISSUE TITLE
[Bug] The browser opened when [vite] page reload

### ISSUE THREAD

**Issue by simo-an** [electron-vite/electron-vite-vue#269]
#### The browser opened when [vite] page reload

The browser will open when [vite] page reload

``` typescript
下午2:42:15 [vite] hmr update /src/view/function/todo/todo-navigator.vue
下午2:42:16 [vite] hmr update /src/view/function/todo/todo-navigator.vue
下午2:42:25 [vite] page reload src/service/BaseService.ts
下午2:42:25 [vite] hmr update /src/view/function/todo/todo-navigator.vue
下午2:42:27 [vite] page reload src/service/BaseService.ts
```

When I change the non-vue file like `BaseService.ts`，the page will reload and open browser.
That is not a good experience in electron project, is there any suggestion to slove this problem? 

thx

**Comment by caoxiemeihao** [comment]
This feature is not available by default, did you change something?
