### ISSUE TITLE
[Help] Equivalent for process.env.IS_ELECTRON in vue-cli-plugin-electron-builder

### ISSUE THREAD

**Issue by yxyx-github** [electron-vite/electron-vite-vue#272]
Is there an equivalent in electron-vite-vue for the environment variable `IS_ELECTRON` in vue-cli-plugin-electron-builder (e.g. https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html)?
`import.meta.env.IS_ELECTRON` does not exist.

**Comment by caoxiemeihao** [comment]
```js
export default {
  define: {
    'import.meta.env.IS_ELECTRON': true,
  },
}
```
