### ISSUE TITLE
build 之后 主进程中的运行的child_process.spawn("npm publish") 提示npm 命令没有

### ISSUE THREAD

**Issue by wd2010** [electron-vite/electron-vite-vue#275]
#### 问题描述
electron的主进程中需要执行npm publish自动发包任务，本地开发环境时，由于使用了命令行的PATH，可以执行child_process.spawn("npm publish") 。但build之后此时的PATH是/usr/bin:/bin:/usr/sbin:/sbin，我的npm命令不在这个下面导致报错。
```bash
Command failed: cd /var/folders/rl/09xrnhwn6_5cp6mj709v_h_c0000gn/T/my_tmp && npm publish /bin/sh: npm: command not found
```
```bash
系统：M1 macos 12.6
node: v18.5.0
npm: 8.12.1
node bin location = /Users/viki/.nvm/versions/node/v18.5.0/bin/node
```
尝试将`npm i npm`安装到node_modules中，在main process中`require('npm')` 也没有效果

请问下可以怎么把npm包打包进app里面，build之后可以直接使用?

[npm-command-not-found-when-executing-commands-in-electron-app](https://stackoverflow.com/questions/55413900/npm-command-not-found-when-executing-commands-in-electron-app)

参考了上面的方法也没用

**Comment by caoxiemeihao** [comment]
`require('npm')` 然后你怎么使用的，别说还是用的 `child_process.spawn("npm publish")`.
提供下 Demo

**Comment by wd2010** [comment]
> `require('npm')` 然后你怎么使用的，别说还是用的 `child_process.spawn("npm publish")`. 提供下 Demo



> `require('npm')` 然后你怎么使用的，别说还是用的 `child_process.spawn("npm publish")`. 提供下 Demo


大佬，项目在这里，麻烦有空帮忙看下

https://github.com/wd2010/kzx_dg_ui

**Comment by caoxiemeihao** [comment]
<img width="883" alt="image" src="https://user-images.githubusercontent.com/26263658/211294900-c15817a4-a173-4cf3-ab8e-c3221a64f3a0.png">
<img width="540" alt="image" src="https://user-images.githubusercontent.com/26263658/211295023-9da9b50d-3de4-4228-b80e-b8bf9bcffe89.png">

---

我用原生的 `npm` 命令试了下，本地开发、生产都可以用的。
