### ISSUE TITLE
Git is a dependancy

### ISSUE THREAD

**Issue by zachwvk** [electron-vite/electron-vite-vue#276]
My company uses SVN, so I never had git installed.

Trying to follow the basic instructions in the Quick start I ran into some scary error messages such as:
`Project template: » Vuetron-vite node:events:491 throw er; // Unhandled 'error' event`

After I realized that wasn't the real problem I looked further down and saw this line
`Error: spawn git ENOENT`

After installing git the quick start now works correctly.

My suggestion is that the README should mention the prerequisites, or have a "Having Trouble?" link to another page that lists the prerequisites.

**Comment by caoxiemeihao** [comment]
Good idea 😂
