### ISSUE TITLE
[Bug] npm run dev后没有界面出现，也没有报错

### ISSUE THREAD

**Issue by Miracle6** [electron-vite/electron-vite-vue#278]
#### Describe the bug
![image](https://user-images.githubusercontent.com/61740563/196015546-10917d1d-3d47-4808-a913-bef1b3d03e6e.png)
好久没碰这个项目，今天一运行界面不显示了。但这个代码直接打包，软件可以运行。请问这个怎样解决？

**Comment by caoxiemeihao** [comment]
关掉已经开启的应用

**Comment by Miracle6** [comment]
> 关掉已经开启的应用

这个检查了的，任务管理器里面也没有进程

**Comment by Miracle6** [comment]
> 关掉已经开启的应用

解决啦，electron.exe好像有点问题，重新装了就好了
