### ISSUE TITLE
[Bug] vite-plugin-electron-renderer有bug

### ISSUE THREAD

**Issue by HaoAu3** [electron-vite/electron-vite-vue#280]
#### Describe the bug
1.npm create electron-vite
2.npm i
3.npm i -D vite-plugin-electron-renderer
4.在vite.config.ts配置renderer()
5.在main.ts解除注释import './samples/node-api'
6.npm run build 报错

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-vue/commit/d08921d6f69a601be69b29f9704a3959d6fde7a7
