### ISSUE TITLE
最新版本引入了ffi-napi 就客户端就报错打不开了

### ISSUE THREAD

**Issue by xuxuhui88** [electron-vite/electron-vite-vue#283]
之前版本没事，最新版本引入了ffi-napi 就客户端就报错打不开了
[5568:1018/193817.670:ERROR:node_bindings.cc(146)] Fatal error in V8: v8_ArrayBuffer_NewBackingStore When the V8 Sandbox is enabled, ArrayBuffer backing stores must be allocated inside the sandbox address space. Please use an appropriate ArrayBuffer::Allocator to allocate these buffers.

**Comment by caoxiemeihao** [comment]
看看最新代码，确保你正确的在渲染进程开启了 Node.js 支持。

**Comment by xuxuhui88** [comment]
async function createWindow() {
  win = new BrowserWindow({
    title: 'Main window',
    icon: join(process.env.PUBLIC, 'favicon.ico'),
    webPreferences: {
      preload,
      // Warning: Enable nodeIntegration and disable contextIsolation is not secure in production
      // Consider using contextBridge.exposeInMainWorld
      // Read more on https://www.electronjs.org/docs/latest/tutorial/context-isolation
      nodeIntegration: true,
      contextIsolation: false,
    },
  })
渲染进程脚手架不是默认已经开启了Nodejs的支持，就算不在渲染进程中引入，在主进程main.js 中require('ffi-napi') 一样报错

**Comment by cjyyyyyy** [comment]
解决了吗

**Comment by caoxiemeihao** [comment]
主进程直接 `require('ffi-napi')` 按理说不应该报错了，尤其是开发期。
目前 ffi-napi 最新版本也是两年前了，并且还是 CJS 格式的包。
<img width="391" alt="image" src="https://user-images.githubusercontent.com/26263658/209896640-c5d7c54f-d6cc-4c5f-992b-2cbad23c265f.png">
如果打包期报错，是否将 `ffi-napi` 加到了 `dependencies` 中？

**Comment by caoxiemeihao** [comment]
尝试在开一个子进程，然后在子进程中引入 `ffi-napi` 呢？
