### ISSUE TITLE
[🐞] After build, `assets` can not resolved correct. / 打包后，assets下资源路径不正确

### ISSUE THREAD

**Issue by BloodlustLR** [electron-vite/electron-vite-vue#287]
![A{6`KF{8T$YI$XWQADEL_8C](https://user-images.githubusercontent.com/26219522/196832283-aeecbc0b-a1f4-4c0b-86b7-a240fb7f0c17.png)

img标签引用assets下的图片后，打包后安装图片都无法显示，路径指向dist而不是dist/assets导致无法读取
![image](https://user-images.githubusercontent.com/26219522/196832401-0059d0e8-db16-4a4c-8f27-fdc4760e6520.png)

**Comment by realmx** [comment]
我也遇到同样的错误

**Comment by wx980416** [comment]
不知道咋怎么解决啊

**Comment by ezesalmon** [comment]
I'm having the same issue!!!
I saw in older projects that  I have with `@vue/cli` that static resource were load as:
`src="app://./assets/my_logo.dcfdbf89.png"`

Maybe the thing is to transform the output we're getting now, into something with like `app://./assets/...`
I had a quick look at [the electron plugin API](https://github.com/electron-vite/vite-electron-plugin#plugin-api), but I didn't try anything

**Comment by caoxiemeihao** [comment]
This may not be the right thing to do. 🤔
https://github.com/electron-vite/vite-plugin-electron/commit/7e76ca6f604a0b7516d3f1e08f278b5db768db8e#diff-e195609aee645f6b35c36a455c23123070147a97f2be4d6a70b7708293f320f8L18
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/26263658/198446209-cba05a72-9489-405c-a57c-8dbb7e71b78d.png">

---

However, we can avoid this problem by configuring Vite.

```diff
export default {
  build: {
+   assetsDir: '',
  },
}
```

**Comment by AslamHamdi** [comment]
You need to check the dist folder after release. Because the image will be read from there. 

I add this in index.ts: 

`process.env.isDev = process.env.npm_node_execpath ? 'true' : 'false'`

and then, use this to retrieve static files:

`let path = process.env.isDev == 'true' ? '/src/Assets/Video/test.mp4' : __dirname + '/assets/Video/test.mp4'`

the dist/ was generated from 'public' folder

**Comment by caoxiemeihao** [comment]
Upgrade `vite-plugin-electron-renderer` to `0.13.14`

**Comment by ltcooooooo** [comment]
我的打包之后也无法正常加载，后来发现是打包之后将图片转为了base64，在mate标签中添加
