### ISSUE TITLE
[Help] the title of help wanted report

### ISSUE THREAD

**Issue by zhishaofei3** [electron-vite/electron-vite-vue#290]
#### Describe the problem you confuse
请问electron怎么拿到.env.xxx中的配置
现在src喜爱的可以，但main的拿不到

**Comment by caoxiemeihao** [comment]
在 main 中考虑使用 `dot-env` 包。
`import.meta.env.VITE_XXX` 不适用于 `cjs` 格式构建，会报错，Electron-Main 只能构建 `cjs` 格式。
