### ISSUE TITLE
[Help] build打包后，assets文件夹下的资源无法正确加载

### ISSUE THREAD

**Issue by desstiony** [electron-vite/electron-vite-vue#291]
#### Describe the problem you confuse
`vite.config.ts`中`renderer({
            nodeIntegration: true,
})` 时，打包后资源无法加载，试过import引入资源也一样无法加载。将`true`改为`false`后正常，请问是什么原因导致的？

**Comment by jiumengs** [comment]
![image](https://user-images.githubusercontent.com/39983417/197970210-09110524-b988-4a76-abab-4366882e1cae.png)
差了一级目录

**Comment by caoxiemeihao** [comment]
这个路径是 `@vitejs/plugin-vue` 实生成的，貌似没有正确的指向 `assetsDir` 目录。
早期我通过插件内部默认了 `assetsDir = ''` 绕开了这个问题，不过最近我删除了这个预设。
果不其然，该来的还是来了，最近很忙！很忙！，持续观察看看如何更优雅的解决这个问题。
统一在 #287 中讨论这个问题。

```diff
export default defineConfig({
  build: {
+   assetsDir: '',
  },
})
```
