### ISSUE TITLE
[Bug] app.asar" does not exist

### ISSUE THREAD

**Issue by yangdezuan** [electron-vite/electron-vite-vue#293]
#### Describe the bug
 Application entry file "dist-electron\main\index.js" in the "I:\wm\web\dev\electron\pwlive-client\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "dist-electron\main\index.js" in the "I:\wm\web\dev\electron\pwlive-client\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
无法打包，前几天还可以用，这几天重新打包报这个错误。几台机器看了都有这个问题？麻烦看下原因，谢谢

**Comment by caoxiemeihao** [comment]
你当我是神？

**Comment by caoxiemeihao** [comment]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/26263658/198837223-990d030a-ad18-4959-8ef4-e776b8bc19bc.png">
