### ISSUE TITLE
[Bug] 将app.asar产物复制到electron官方打包的二进制程序中运行失败

### ISSUE THREAD

**Issue by PingKuNet** [electron-vite/electron-vite-vue#298]
#### Describe the bug

将打包时产生的  electron-vite-vue\release\2.1.0\win-unpacked\resources\app.asar

复制到electron官方的resources目录远行是空白的

将default_app.asar删除，再远行也是一样的

请问这个要怎么解决，还是说不支持这种方式，早期的版本应该是可行的
我想在Win上打包给Mac用户使用，所以测试了这种方式，而我没有Mac，如果这样不可行的话，就很不方便

![image](https://user-images.githubusercontent.com/48786066/199144098-172b0fd3-0e32-4b9c-b192-a592e5ad1514.png)

**Comment by caoxiemeihao** [comment]
Windows 打包不了 Mac，问题不属于 `electron-vite`

**Comment by PingKuNet** [comment]
> Windows 打包不了 Mac，问题不属于 `electron-vite`

你看我这是放在Win版中的，并不是Mac

**Comment by PingKuNet** [comment]
> Windows 打包不了 Mac，问题不属于 `electron-vite`

你可以自己测试一下

**Comment by caoxiemeihao** [comment]
我没 windows

**Comment by PingKuNet** [comment]
你这个回答和关闭有点草率喽，首先我并不是想在Win上打包出Mac应用，目前electron还做不到这一点，这我是知道的。

第二，这个问题确实可能并不是electron-vite本身的问题，我想很有可能是 vite build 的问题，但也是在使用electron-vite中发现的，使用旧版的electron-vite的确没有这个问题，所以我向作者提了issues，想得到支持和解决，而不是继续使用旧版的electron-vite。

我的目的是想要得到一个“正确”的  “app.asar”  ，因为正确的代码得到“正确”的  “app.asar”是可以跨平台的。

我们来引用一下electron的官方文档：
https://www.electronjs.org/docs/latest/tutorial/application-distribution

如果你使用的是Mac，我想也可以做同样的测试，运行时可能得到一个空白的屏幕。Linux也是同理。

**Comment by PingKuNet** [comment]
简单的说就是提前下载可以在本机运行的electron
https://github.com/electron/electron/releases
然后打包出“app.asar”
将“app.asar”复制到提前下载好的electron -> Resources目录下
远行提前下载的electron
然后没有得到想要的内容
以上操作不分平台

**Comment by caoxiemeihao** [comment]
草率了
直接下载构建好的 electron/release 我也没能正确运行，我之前没试过这种方式。
我能说明的是解压后的 app.asar 和之前是一致的

<img width="160" alt="image" src="https://user-images.githubusercontent.com/26263658/199169671-c6d83276-62f7-43c6-9810-d7dbba45d0fe.png">
<img width="134" alt="image" src="https://user-images.githubusercontent.com/26263658/199169703-f9401c08-eace-4ade-b625-9ab7841e223b.png">

**Comment by PingKuNet** [comment]
> 草率了 直接下载构建好的 electron/release 我也没能正确运行，我之前没试过这种方式。 我能说明的是解压后的 app.asar 和之前是一致的
> 
> <img alt="image" width="160" src="https://user-images.githubusercontent.com/26263658/199169671-c6d83276-62f7-43c6-9810-d7dbba45d0fe.png">
> 
> <img alt="image" width="134" src="https://user-images.githubusercontent.com/26263658/199169703-f9401c08-eace-4ade-b625-9ab7841e223b.png">

这就比较难测试了，Win版是正常的，其它版本好橡是有点问题。

**Comment by PingKuNet** [comment]
找到原因了，app.isPackaged 不以预想的值进行工作

![image](https://user-images.githubusercontent.com/48786066/199181713-53de4c6e-0dcb-48d2-89f0-a61565d8713b.png)

![image](https://user-images.githubusercontent.com/48786066/199181280-4be0c9e6-3179-4ba4-8968-da15e97f6f74.png)

**Comment by caoxiemeihao** [comment]
666

**Comment by PingKuNet** [comment]
可以考虑优化一下，应该还是有人会使用到这个场景的。
