### ISSUE TITLE
[Help] 这个模板可以提供可选的 Element-Plus 或 View-UI-Plus 支持吗？这样开发起来会更快一些

### ISSUE THREAD

**Issue by GlobalGayhub** [electron-vite/electron-vite-vue#300]
#### Describe the problem you confuse

View-UI-Plus: https://github.com/view-design/ViewUIPlus ( 老版 ViewUI: https://github.com/view-design/ViewUI)
Element-Plus: https://github.com/element-plus/element-plus

**Comment by caoxiemeihao** [comment]
不考虑
