### ISSUE TITLE
[Help]关于此项目preload结构的一些疑问

### ISSUE THREAD

**Issue by blogwy** [electron-vite/electron-vite-vue#301]
我之前使用过`Vue CLI Plugin Electron Builder`和`electron-react-boilerplate`这些样板都有preload.js/ts，里面都是用`contextBridge, ipcRenderer`这两个函数去“注入”函数。

但是，此项目的electron/preload/index.ts里面的内容让我和不解，都是运行在浏览器端代码，甚至还有css代码。真正的preload代码好像在`src/samples/node-api.ts`。但是，src目录不就是渲染进程吗？怎么又出现了proload代码？而且，居然在`src/main.ts`引入了。这node代码和渲染进程代码混了吧。

我没有看懂这个preload逻辑，作者或者哪位热心人可以讲解一下？十分感谢🙏

**Comment by caoxiemeihao** [comment]
这个模板很暴力，直接可以在 渲染进程 中使用 Electron/Node.js API
自从 electron@20 开始，preload 和 渲染进程 默认都不能使用 Electron/Node.js API

**Comment by mrooding** [comment]
Using Google Translate I was able to kind of understand what's being discussed here but I'm wondering how the contextBridge can be used. I've got an existing Vue3 + Electron project that I'm trying to migrate to align with the template used here but the contextBridge seems to be broken compared to before.

**Comment by caoxiemeihao** [comment]
> Using Google Translate I was able to kind of understand what's being discussed here but I'm wondering how the contextBridge can be used. I've got an existing Vue3 + Electron project that I'm trying to migrate to align with the template used here but the contextBridge seems to be broken compared to before.

For use `contextBridge`.

```diff
  win = new BrowserWindow({
    title: 'Main window',
    icon: join(process.env.PUBLIC, 'favicon.ico'),
    webPreferences: {
      preload,
-     nodeIntegration: true,
-     contextIsolation: false,
    },
  })
```

**Comment by liyang9331** [comment]
> 

我不想在渲染进程中使用Electron/Node.js API【为了安全考虑】，按照IPC进程通信的方式调用api，请问如何使用ipc通信正常工作呢？

**Comment by liyang9331** [comment]
> 这个模板很暴力，直接可以在 渲染进程 中使用 Electron/Node.js API 自从 electron@20 开始，preload 和 渲染进程 默认都不能使用 Electron/Node.js API，所以干脆直接在 渲染进程中 一把梭！

我不想在渲染进程中使用Electron/Node.js API【为了安全考虑】，按照IPC进程通信的方式调用api，请问如何使用ipc通信正常工作呢？
