### ISSUE TITLE
No loader is configured for ".node" files: node_modules/fsevents/fsevents.node

### ISSUE THREAD

**Issue by ch3n90** [electron-vite/electron-vite-vue#302]
因为在项目中使用了chokidar，而mac平台使用到fsevets 在启动时报：
No loader is configured for ".node" files: node_modules/fsevents/fsevents.node

**Comment by caoxiemeihao** [comment]
你再哪个进程中使用的？有参考文档解决 C++ 包如何使用嘛？

**Comment by ch3n90** [comment]
> 你再哪个进程中使用的？有参考文档解决 C++ 包如何使用嘛？

在主进程中使用，没有往使用动态连接库这个方向思考过，我想在optionDenpendencies中把这个fsevents加上试试

**Comment by ch3n90** [comment]
> 你再哪个进程中使用的？有参考文档解决 C++ 包如何使用嘛？

```javascript

export default defineConfig(({ mode }) => {

  return {
    optimizeDeps: {
      exclude: ['chokidar']  // exclude: ['fsevents']也可以 
    },
}

```
