### ISSUE TITLE
[Help] the title of help wanted report 打包后的图标怎么配置，为什么打包后 应用程序的图片还是默认的？

### ISSUE THREAD

**Issue by 82318179** [electron-vite/electron-vite-vue#303]
#### Describe the problem you confuse
打包后的图标怎么配置，为什么打包后 应用程序的图片还是默认的？

**Comment by 82318179** [comment]
不是安装包的图标 是 win-unpacked 文件夹里面的 程序的图标还是 electron的

**Comment by caoxiemeihao** [comment]
去看下 electron-vite-react 的配置
