### ISSUE TITLE
[Help] Icon not found in build release

### ISSUE THREAD

**Issue by luciano-work** [electron-vite/electron-vite-vue#305]
Hi,
Using ternary operator to display icon doesn't work in release app. All static files are storage in public folder. This is a bug or something that I need to config?
```vue
<inline-svg :src="!theme.darkMode ? 'icons/moon-stars.svg' : 'icons/sun-high.svg'" class="h-5 w-5" />
```

https://user-images.githubusercontent.com/12519008/202782016-0ace08f2-370a-450a-8e04-e48b740769f5.mp4

**Comment by caoxiemeihao** [comment]
Try adding `./` prefix path?
```diff
- <inline-svg :src="!theme.darkMode ? 'icons/moon-stars.svg' : 'icons/sun-high.svg'" class="h-5 w-5" />
+ <inline-svg :src="!theme.darkMode ? './icons/moon-stars.svg' : './icons/sun-high.svg'" class="h-5 w-5" />
```

https://github.com/electron-vite/electron-vite-vue/blob/77cda603befbbd7403bdac3e44c9887b55aa176b/src/App.vue#L14->17

**Comment by luciano-work** [comment]
Hi @caoxiemeihao,
Thankyou for your help.
I found a solution, the problem is vue router config, history needs to be createWebHashHistory().
https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve

All the best ;)
