### ISSUE TITLE
[Help] how to use shared entities between Electron and vue

### ISSUE THREAD

**Issue by aminechraibi** [electron-vite/electron-vite-vue#306]
Hello,

I want to use shared entities between Electron and Vue. 
Where should I put them and how to configure that?

Thank you.

**Comment by caoxiemeihao** [comment]
The location of the placement is not the point.
You have to make it clear that the Renderer-Process and the Main-Process are two processes, there is no common entity, just simply use the same copy of the code.

**Comment by alisherafat01** [comment]
@caoxiemeihao  Imagine you are defining a `types.ts` file for declaring types and interfaces in typescript and you should probably be able to access this file in main and renderer process. so how to achieve this?

**Comment by caoxiemeihao** [comment]
@alisherafat01 You can try see this https://github.com/electron-vite/electron-vite-vue/issues/429

**Comment by alisherafat01** [comment]
@caoxiemeihao I can't read that language
