### ISSUE TITLE
[Bug] App doesn't work after packaging (get blank screen)

### ISSUE THREAD

**Issue by oussama-he** [electron-vite/electron-vite-vue#307]
I have created a project using the instructions in the README.md of the repo.
```
npm create electron-vite
cd electron-vite-vue/
npm i
```
After installing the dependencies I run `npm run dev`, and the app worked with no problem.
I have tried to package it running `npm run build` and after the process of packaging I opened the `electron-vue-vite` file in `linux-unpacked`:

![image](https://user-images.githubusercontent.com/18425315/203064565-e71f6411-457c-4bf1-baf6-4c9b6328fe1a.png)

And I get a black screen with this error in the console.
```
Not allowed to load local resource: file:///home/oussama/Desktop/new/electron-vite-vue/dist/linux-unpacked/resources/app.asar/dist/index.html
```
![image](https://user-images.githubusercontent.com/18425315/203064190-c0b39ba5-d305-40c4-980e-f2dc0fae4d9e.png)

I have the same problem (blank screen and nothing working) with another project that I packaged for Windows with a docker image.

Please can someone help me to fix this?
I could share more if necessary.

**Comment by caoxiemeihao** [comment]
What have you changed that you probably shouldn't build the app into the dist folder.

**Comment by oussama-he** [comment]
Nothing. 
I have tried to package the fresh project that I got with instructions listed above without changing a line of code.

**Comment by yooouuri** [comment]
@caoxiemeihao im having the same problem here, after unpacking the .asar, the index.html is missing.

![image](https://user-images.githubusercontent.com/12934957/209121339-cc7d5c31-6533-4e11-8b66-e4b30c59b4ba.png)

My vite config.

```
electron({
  entry: 'src/electron.ts',
  vite: {
    build: {
      rollupOptions: {
        external: [
          'usb',
        ],
      },
    },
  },
}),
renderer(),
```

**Comment by yooouuri** [comment]
Hmm the index.html is moved into the dist folder, what is kinda obvious.

![image](https://user-images.githubusercontent.com/12934957/209123008-9181424f-0f16-4f97-adbd-8d257eca7699.png)

@oussama-he So you need to update your path were you load the index.html in your electron main

**Comment by soylomass** [comment]
This seems to happen when you add a "build" section in the package.json file. I added it to change the appId and name, and it changed how and where the executable is created, also the size.
Went back to normal after removing the build section.
