### ISSUE TITLE
[Help] rtc-electron-sdk

### ISSUE THREAD

**Issue by hzzly** [electron-vite/electron-vite-vue#308]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/16360684/203814170-aae836ea-ba7d-49b8-925e-0d08a3ad12cf.png">
请问这种如何解决呢

**Comment by HaoAu3** [comment]
https://cloud.tencent.com/document/product/647/75694

**Comment by caoxiemeihao** [comment]
在渲染进程中用的，还是主进程。
主进程放到 `dependencies` 中即可
渲染进程放 `optimizeDeps` 中 https://github.com/electron-vite/vite-plugin-electron/blob/14684ba108beec305edf4c9d8865527f6508f987/examples/nodeIntegration/vite.config.ts#L17-L26
