### ISSUE TITLE
[Bug] 添加vue-router后main.ts文件会执行两遍，开发环境没问题，打包后会执行两遍

### ISSUE THREAD

**Issue by crazy-max-js** [electron-vite/electron-vite-vue#311]
#### Describe the bug
添加vue-router后main.ts文件会执行两边，控制台输出内容会有两边，不知道什么原因

**Comment by crazy-max-js** [comment]
![QQ截图20221130005143](https://user-images.githubusercontent.com/27037918/204592013-187c990e-db4a-4692-b5ca-07ff7d4a0112.png)

**Comment by crazy-max-js** [comment]
开发环境没问题  打包后会如上所示
测试了一下 使用vue-router会执行两次，具体原因不清楚

**Comment by zhanghu12138** [comment]
我这边也遇到这个问题，有啥解决办法

**Comment by caoxiemeihao** [comment]
要人帮忙解决问题的，提供下最小复现 Demo

**Comment by crazy-max-js** [comment]
> 要人帮忙解决问题的，提供下最小复现 Demo

https://github.com/crazy-max-js/electron-vite-vue-router
demo如上，我项目用的2.1.0的  Demo是2.0.0的  也有相同bug，thx

**Comment by caoxiemeihao** [comment]
Vite 会将 node_modules、公用代码 构建到入口文件(`index.js`)中。其次通过 `import()` 导入的路由页面(`page.js`)也会使用到公用代码，然后 Vite 会在路由页面(`page.js`)中会引用入口文件(`index.js`)中的公用代码 -- **造成入口文件多次执行**。
目前这个 BUG 还需要研究下 Vite 底层的处理机制，可能可以通过合理的 `rollupOptions.manualChunks` 避开，探索中！

暂时的解决办法，将 `import()` 导入写法改成直接引入的形式：

```diff
  import { createRouter, createWebHashHistory } from "vue-router";
+ import TestView from '../views/TestView.vue';

  const router = createRouter({
    history: createWebHashHistory(import.meta.env.BASE_URL),
    routes: [
      {
        path: "/",
        name: "Test",
-       component: () => import("../views/TestView.vue"),
+       component: TestView,
        meta: {
          title: "测试",
        },
      },
    ],
  });

  export default router;
```

**Comment by caoxiemeihao** [comment]
`v0.13.17+` 默认使用 ESM 格式构建，避开了 CJS 构建造成的 vue-router 问题
https://github.com/electron-vite/vite-plugin-electron-renderer/pull/45
