### ISSUE TITLE
[Help] 打包出来的exe，不能和本地开发的同时运行吗

### ISSUE THREAD

**Issue by A-snow** [electron-vite/electron-vite-vue#313]

**Comment by caoxiemeihao** [comment]
改下 appId
https://github.com/electron-vite/electron-vite-vue/blob/c43f6484b9affac3bcc252e7ea14dab29c6478ab/electron-builder.json5#L5

**Comment by A-snow** [comment]
改了appId的，然后打包，运行打包的exe，然后本地npm run dev ，终端自动结束
![image](https://user-images.githubusercontent.com/27356588/205562460-9fbf5a9a-fc08-4814-90f1-1c7b7adc8326.png)
