### ISSUE TITLE
[Menu ] import { Menu } from 'electron' get a error.

### ISSUE THREAD

**Issue by RSS1102** [electron-vite/electron-vite-vue#318]
当我想创建一个自定义菜单栏的时候，我通过import引入Menu，产生了这个错误。
```ts
import { Menu } from 'electron'

/**
 * @desc 自定义菜单栏
 * @docs [Menu](https://www.electronjs.org/zh/docs/latest/api/menu#class-menu)
 */
// const isMac = process.platform === 'darwin'
const menuTemplate = [
    { id: '1', label: 'one' },
    { id: '2', label: 'two' },
    { id: '3', label: 'three' },
    { id: '4', label: 'four' }
  ]


  const menu = Menu.buildFromTemplate(menuTemplate)
  Menu.setApplicationMenu(menu)
```
获得了一个错误：
`
Uncaught SyntaxError: The requested module '/node_modules/.pnpm/registry.npmmirror.com+vite-plugin-electron-renderer@0.11.3_esbuild@0.16.4/node_modules/vite-plugin-electron-renderer/electron-renderer.js?v=70852ef6' does not provide an export named 'Menu' (at menu.ts:1:10)
`
我第一次开发electron，请问如何自定义一个菜单栏呢，基于https://github.com/electron-vite/electron-vite-vue

**Comment by HaoAu3** [comment]
不要用pnpm，用npm。

**Comment by RSS1102** [comment]
[代码片段](https://github.com/RSS1102/electron-markdown-notepad/blob/5f6aa3baacbfdaaaf345c9948e9b18075105fc32/electron/main/index.ts#L74) 是我写错了地方，应该在create windows内就进行初始化菜单。
