### ISSUE TITLE
[Help] 请问怎么更新安装程序图标。

### ISSUE THREAD

**Issue by kl2426** [electron-vite/electron-vite-vue#321]
请问怎么更新安装程序图标？
1，安装程序图标。
![image](https://user-images.githubusercontent.com/12854042/207548172-2195a7cc-509d-4a40-adfa-edf859b5646f.png)
2，桌面快捷方式图标。
![image](https://user-images.githubusercontent.com/12854042/207548392-e02aac08-cd8e-465b-87d2-12379df12604.png)
3，桌面底部任务栏右键显示图标
![1671007816433](https://user-images.githubusercontent.com/12854042/207549587-bec5b4ce-986f-4331-99a4-1f7b780b14ca.jpg)

**Comment by caoxiemeihao** [comment]
看看这个项目的配置哈
https://github.com/electron-vite/electron-vite-react

**Comment by UzumakiHan** [comment]
electron-builder.json5中配置
![image](https://github.com/electron-vite/electron-vite-vue/assets/52144920/ede3da62-4c48-41ba-9be8-77ad879556c7)
