### ISSUE TITLE
[Help] 引入环境变量文件后,build不同环境后的问题

### ISSUE THREAD

**Issue by LeToNode** [electron-vite/electron-vite-vue#323]
比如我有多个.env环境,分别指定不同的环境配置.
```
    "build": "vite build && electron-builder",
    "build:qa": "vite build --mode qa && electron-builder  ",
```
执行后会发现web进程相关的文件中引用环境变量相关的地方改变了,但是dist-electron的内容却是production环境变量的内容.怀疑是loadEnvPlugin没有正确识别.env.qa文件引起的electron编译时未正确替换环境变量相关内容

**Comment by caoxiemeihao** [comment]
其实好简单的东西被我想复杂了
vite-plugin-electron 下个版本会修复这个问题，目前代码在 v0.11.0 分支上。
可以参考下

**Comment by caoxiemeihao** [comment]
升级下 vite-plugin-electron@0.11.0
