### ISSUE TITLE
请问：如果要在index.html里面引入文件还需要怎么配置吗 ?打包出来报错

### ISSUE THREAD

**Issue by A-snow** [electron-vite/electron-vite-vue#325]
![image](https://user-images.githubusercontent.com/27356588/208609126-e553b9b0-2f82-433c-8277-2100278504eb.png)
![image](https://user-images.githubusercontent.com/27356588/208609196-f84cd6ef-3457-42ce-a775-4654bd213aad.png)

**Comment by caoxiemeihao** [comment]
用 `./` 路径
