### ISSUE TITLE
[Help] What are the meanings of these two warnings?

### ISSUE THREAD

**Issue by Imaginativeone** [electron-vite/electron-vite-vue#332]
#### Describe the problem you confuse

**Warning 1**
![Possible-Warning-01](https://user-images.githubusercontent.com/1640067/210139536-7c2e0ccf-3a98-4566-9dee-d8eccd07feb3.png)

**Warning 2**
![Possible-Warning-02](https://user-images.githubusercontent.com/1640067/210139563-35b022dc-39e5-4a8c-b765-70b57777d04a.png)

**Comment by xhayper** [comment]
All warnings are safe to ignore.

**Comment by caoxiemeihao** [comment]
The correct path should be: `http://localhost:5173/dist-electron/preload/index.js.map`
This is really a bug 🤔

**Comment by xhayper** [comment]
I am thinking that it was caused by it looking for an absolute path and not a relative path...

**Comment by xhayper** [comment]
Current workaround is to set the sourcemap option to 'inline' for now.

**Comment by rzg2022** [comment]
> The correct path should be: `http://localhost:5173/dist-electron/preload/index.js.map` This is really a bug 🤔

What can be done now to solve this problem?
