### ISSUE TITLE
[Help] Please provide a full example of how to create multiple windows

### ISSUE THREAD

**Issue by martinszeltins** [electron-vite/electron-vite-vue#333]
If I want to create an app where I open multiple windows - how do I do that? It seems that Vite only takes `index.html` and `main.ts` but if I had 10 windows, how to do that?

**Comment by caoxiemeihao** [comment]
[vite-plugin-electron/examples/multiple-windows](https://github.com/electron-vite/vite-plugin-electron/tree/main/examples/multiple-windows)

**Comment by SuperPlatipus** [comment]
Hello!

I checked the examples and I see one vite config file every window renderer instance

Are multiple vite config files necesary for multiple html + multiple windows? or the example follows this formula to distinguish node access permisions?

**Comment by caoxiemeihao** [comment]
@SuperPlatipus  No No No!
The example only one Vite config file 👉 https://github.com/electron-vite/vite-plugin-electron/tree/main/examples/multiple-renderer

**Comment by ianoble** [comment]
@caoxiemeihao The examples are gone. Where are they moved to?
