### ISSUE TITLE
[Bug] 运行npm i提示高危漏洞 6 high severity vulnerabilities

### ISSUE THREAD

**Issue by Generalize** [electron-vite/electron-vite-vue#334]
E:\project\electron-vite-vue>npm i
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different

added 279 packages, and audited 280 packages in 33s

33 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by caoxiemeihao** [comment]
1. `magic-string` 依赖 `sourcemap-codec`
2. `@electron/universal` 依赖 `asar`
