### ISSUE TITLE
[Help] the title of help wanted report

### ISSUE THREAD

**Issue by sophiezzhou** [electron-vite/electron-vite-vue#335]
#### Describe the problem you confuse

Our project integrates version 1.0.0. How to update us to version 2.0.0 in a simple way? I tried it myself and found it very difficult. The file directory is quite different.

**Comment by caoxiemeihao** [comment]
v2.0 is plugin-based and does not offer a migration solution.
v1.0 will continue to be maintained at [electron-vite-boilerplate](https://github.com/electron-vite/electron-vite-boilerplate).
