### ISSUE TITLE
[Help] 请教，run dev启动后，更改任意ts文件，会触发浏览器打开网页

### ISSUE THREAD

**Issue by yuanhongyu123** [electron-vite/electron-vite-vue#344]
#### Describe the problem you confuse
run dev启动后，更改任意ts文件，都会触发浏览器打开网页，这个需要怎么解决呢

**Comment by caoxiemeihao** [comment]
默认没这个功能

**Comment by UoToGK** [comment]
> #### Describe the problem you confuse
> run dev启动后，更改任意ts文件，都会触发浏览器打开网页，这个需要怎么解决呢

没错,而且永远都是打开默认这个地址http://127.0.0.1:5173/,更改vite配置也无法避免,很烦

**Comment by caoxiemeihao** [comment]
要是没改动任何配置，那应该是 Vite 自带的 BUG 了。提供下 package.json 的版本，方便的话提供下复现仓库。

**Comment by yuanhongyu123** [comment]
就是本仓库的代码，没有改动任何东西，dev启动后，随便给main.ts修改一下就会触发打开浏览器网页

**Comment by UoToGK** [comment]
> 就是本仓库的代码，没有改动任何东西，dev启动后，随便给main.ts修改一下就会触发打开浏览器网页

main.ts不用修改什么,就是按下CTRL+S,他就可以复现了,更改外面的配置倒是不会,就是改ts文件就会,非常神奇

**Comment by UoToGK** [comment]
> 要是没改动任何配置，那应该是 Vite 自带的 BUG 了。提供下 package.json 的版本，方便的话提供下复现仓库。

我尝试用js搭了一个,修改任意js也会这样

**Comment by rico0808** [comment]
+1 目前存在这个问题

**Comment by roymina** [comment]
+1, 配置了也没用
过一会就成这样了
![image](https://user-images.githubusercontent.com/9797833/221065851-5bd943a5-90f7-41d9-95b7-dca137525b0c.png)

```js
    server: process.env.VSCODE_DEBUG && (() => {
      const url = new URL(pkg.debug.env.VITE_DEV_SERVER_URL);
      return {
        host: url.hostname,
        port: +url.port,
        open: false
      };
    })(),
```

**Comment by caoxiemeihao** [comment]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/26263658/221146937-744bcb22-225f-4ab0-b527-0ae86336245c.png">
很魔性，开发模式下哪怕打开一个和项目毫不相干的地址，在控制台执行 `location.reload()` 都会导致打开浏览器！
打包后在控制台输入 `location.reload()` 失效，不知道这个 BUG 是否是 Electron 包的问题，换了版本也无济于事！

**Comment by yuanhongyu123** [comment]
https://github.com/umbrella22/electron-vite-template
我看这个架子就没有这个问题，我不懂原理哎。

**Comment by caoxiemeihao** [comment]
随便换个架子都没问题 `vite-plugin-electron`、`vite-electron-plugin` 提供的 `quick-start`、`electron-vite-react` 统统都没问题

**Comment by caoxiemeihao** [comment]
稍安勿躁，拉下最新代码就行了。
是这个 PR 引起的：https://github.com/electron-vite/electron-vite-vue/pull/343
