### ISSUE TITLE
[Help] Running postinstall script...

### ISSUE THREAD

**Issue by 6ag** [electron-vite/electron-vite-vue#345]
#### Installation log
electron-vite-vue pnpm install
 WARN  deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
 WARN  deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
Packages: +61
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
node_modules/.pnpm/electron@22.3.0/node_modules/electron: Running postinstall script...
Progress: resolved 299, reused 278, downloaded 0, added 0, done

I have been stuck at Running postinstall script... and cannot complete the installation

**Comment by caoxiemeihao** [comment]
Create `.npmrc` at root dir and type the following snippets

```sh
shamefully-hoist=true
electron_mirror=https://npmmirror.com/mirrors/electron/
```
