### ISSUE TITLE
[Help] 请教如何配置source-map

### ISSUE THREAD

**Issue by yuanhongyu123** [electron-vite/electron-vite-vue#346]
![d7f9d2f7d28535e7cc3eef59b192ade](https://user-images.githubusercontent.com/48054829/220680944-16717eb3-dab8-4707-be85-83b05d92ee6f.jpg)
如图，我模拟抛出异常，控制台输入的还是编译后的main.js的报错位置，如何才能显示原始的ts文件位置，
我看了dist目录编译后的main.js.map文件也已经生成了

**Comment by caoxiemeihao** [comment]
- [ ] [Support Node.js Source Map](https://github.com/evanw/node-source-map-support)

**Comment by yuanhongyu123** [comment]
感谢，想起来了，忘了这个配置了
