### ISSUE TITLE
[Help] create a shared folder for `electron` and `src`

### ISSUE THREAD

**Issue by binyu1231** [electron-vite/electron-vite-vue#347]
hi~ 

i want to create a folder to share some `types` between `/electron` & `/src`. 

before, I created folders in packages:

``` diff
   /packages
+  |- core   
   |- main
   |- preload
   |- renderer
+  |- types 
``` 

but now I can not get a configure correctly in `tsconfig.json` and `tsconfig.node.json`.

give me some suggestions. Thanks~

**Comment by caoxiemeihao** [comment]
tsconfig.json

```diff
{
- "include": ["src"],
}
```
