### ISSUE TITLE
在electron-vue-vite 中如何使用代理来请求后端数据接口？？

### ISSUE THREAD

**Issue by yoke0104x** [electron-vite/electron-vite-vue#349]
在electron-vue-vite 中如何使用代理来请求后端数据接口？？

**Comment by caoxiemeihao** [comment]
直接用住主进程请求不就行了？

**Comment by yoke0104x** [comment]
@caoxiemeihao 那怎么吧请求返回的数据传递到页面上呢？

**Comment by daizhiyu** [comment]
vite.config.js 里面 配置下代理就行了 
  server: {
    host: pkg.debug.env.VITE_DEV_SERVER_HOSTNAME,
    port: pkg.debug.env.VITE_DEV_SERVER_PORT,
    proxy: {
      "^/api": {
        target: xxx,
        rewrite: (path) => path.replace(/^\/api/, ""),
        changeOrigin: true,
      },
    },
  },

**Comment by yoke0104x** [comment]
不太行啊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月08日 16:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [electron-vite/electron-vite-vue] 在electron-vue-vite 中如何使用代理来请求后端数据接口？？ (Issue #349) |

vite.config.js 里面 配置下代理就行了
server: {
host: pkg.debug.env.VITE_DEV_SERVER_HOSTNAME,
port: pkg.debug.env.VITE_DEV_SERVER_PORT,
proxy: {
"^/api": {
target: xxx,
rewrite: (path) => path.replace(/^/api/, ""),
changeOrigin: true,
},
},
},
