### ISSUE TITLE
麻烦问下index.html引入的静态资源没打包出来

### ISSUE THREAD

**Issue by 1236987456** [electron-vite/electron-vite-vue#353]
![image](https://user-images.githubusercontent.com/27341863/224879839-ad786b5d-cec6-44b0-811a-1f6305a118e3.png)

**Comment by caoxiemeihao** [comment]
静态资源放到 public 中

**Comment by 1236987456** [comment]
感谢，如果打包后想通过修改静态文件里面的配置后端地址可以实时调试exe文件可以做到吗

**Comment by caoxiemeihao** [comment]
自己去研究下
