### ISSUE TITLE
[Help] the dist-electron package can’t be generated suddenly

### ISSUE THREAD

**Issue by SKT1yang** [electron-vite/electron-vite-vue#354]
#### I failed to package during the iterative process. I don’t know why the dist-electron package can’t be generated suddenly. The following is a screenshot of my packaging error. Can you see the reason? ?
![help](https://user-images.githubusercontent.com/34095649/226222158-5c84368e-c1eb-4278-b16d-e1ce55b3f824.png)

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?
