### ISSUE TITLE
[Help] 请教下主进程如何使用import.meta.glob

### ISSUE THREAD

**Issue by MrChildrenHY** [electron-vite/electron-vite-vue#356]
之前用webpack的require.context获取某个文件夹下所有的ts文件，做批量引入，
现在改用import.meta.glob，编译直接报错，应该给是electron不支持esm？
那应该怎么改写这个呢，大佬能给个思路吗

**Comment by so1ve** [comment]
electron代码走vite编译吗？

**Comment by caoxiemeihao** [comment]
> electron代码走vite编译吗？

走的，按理说支持 `import.meta.glob` 的，这么个小东西自己多研究研究哈。(*除非给我扫码捐赠 🤣*)
