### ISSUE TITLE
No native build was found for platform=darwin arch=arm64 runtime=electron abi=113 uv=1 armv=8 libc=glibc node=18.12.1 electron=23.1.1

### ISSUE THREAD

**Issue by huangzh278** [electron-vite/electron-vite-vue#357]
#### 
I used the serial port plug-in serialport to report an error in the render process now.
我使用了serialport这个串口插件在render进程中现在报错
<img width="571" alt="image" src="https://user-images.githubusercontent.com/125860274/226809378-213114c9-6dff-4318-b1da-61ebd1b57ef4.png">
I configure it in vite.config.ts as follows.
我在vite.config.ts 配置如下
`
<img width="805" alt="image" src="https://user-images.githubusercontent.com/125860274/226811080-fe57ac6c-b908-46b1-86f1-b915074a1863.png">

`
Has this brother ever appeared? How to solve it?
这个兄弟出现过么 怎么解决，谢谢

[A solution has been found](https://github.com/electron-vite/vite-plugin-electron-renderer#dependency-pre-bundling)

**Comment by caoxiemeihao** [comment]
这里有 Demo 哈！
https://github.com/electron-vite/vite-plugin-electron-renderer/blob/v0.13.11/examples/quick-start/vite.config.ts#L12
