### ISSUE TITLE
安装electron-store，后台热更新失败并且不重启

### ISSUE THREAD

**Issue by meedfine** [electron-vite/electron-vite-vue#359]
#### Describe the bug
https://github.com/meedfine/electron-hmr-fail

只有一个提交记录
安装electron-devtools-installer electron-store
npm run dev,然后修改main进程的配置，如title或宽高等等，只要触发hmr即可，然后进程就卡住了，无法自动重启app

**Comment by meedfine** [comment]
emmm,我这放dependencies，dev时候控制台就报错了TypeError: installExtension is not a function，我就没试build了

**Comment by meedfine** [comment]
electron-devtools-installer 
放devDependencies，dev环境编译变慢，但正常运行，控制台有Vue Tab
放dependencies， dev环境很快，但vscode控制台 报TypeError: installExtension is not a function

electron-store
放devDependencies，dev编译变慢，且无法热编辑main.ts了，会卡死，需要自己退出重新run dev
放dependencies，dev编译很快，但是没尝试功能是否正常

我后续看看electron-store放dependencies，功能正常不

**Comment by meedfine** [comment]
难道我环境问题 。。。我回去换个电脑试试

**Comment by caoxiemeihao** [comment]
不行换到 Vite@4.1.x 试试看，可能是 4.2.x 带来的问题说不定。敢肯定的是 `vite-plugin-electron` 已经三个月没法新版了！

**Comment by ewigl** [comment]
> 不行换到 [Vite@4.1.x](mailto:Vite@4.1.x) 试试看，可能是 4.2.x 带来的问题说不定。敢肯定的是 `vite-plugin-electron` 已经三个月没发新版了！

移动依赖未解决，vite降级到4.1X问题解决，多谢

**Comment by caoxiemeihao** [comment]
有空我去翻翻 Vite@4.2.x 的更新日志看看。。。

**Comment by meedfine** [comment]
谢谢，降回4.1.x可用，4.2&4.3beta都卡死
