### ISSUE TITLE
${version} folder is generated in release folder

### ISSUE THREAD

**Issue by itsnwa** [electron-vite/electron-vite-vue#36]
A folder with the variable is generated before the release folder is generated. It only contains the `.icon-icns` file.

https://github.com/caoxiemeihao/electron-vue-vite/blob/e522cf352d2c2d2fa4cae4c38e361e05997bd01d/configs/electron-builder.config.mjs#L9

**Comment by caoxiemeihao** [comment]
This is my generated folder. What operating system do you use?

![image](https://user-images.githubusercontent.com/26263658/142536867-a9f73762-549a-47ca-a021-2f82e921ec52.png)

**Comment by billdai998** [comment]
在上面如何打包win的安装包？

**Comment by caoxiemeihao** [comment]
> 在上面如何打包win的安装包？

You can add `win: ['nsis']` options to below code.

https://github.com/caoxiemeihao/electron-vue-vite/blob/e522cf352d2c2d2fa4cae4c38e361e05997bd01d/scripts/build.mjs#L26

**Comment by itsnwa** [comment]
@caoxiemeihao macOS Monterey
Looks like it won't affect your build, because you're not packing a custom app icon.

This is what my release folder looks like after build:
<img width="713" alt="CleanShot 2021-11-19 at 11 24 58@2x" src="https://user-images.githubusercontent.com/19958806/142607372-0b881199-b73f-4dd0-80c7-8c3765548826.png">

This is my `electron-builder.config.mjs` which is slightly modified.
The `buildResources` folder only contains that one app icon in png format.
```js
const config = {
  productName: "Daily Note",
  appId: "com.itsnwa.note",
  asar: true,
  directories: {
    output: "release/${version}",
    buildResources: "buildResources"
  },
  files: ["dist"],
  ...
}
```

**Comment by WaynePluto** [comment]
I ran into the same problem on Windows, which was solved by using administrator privileges before packaging.

**Comment by ConteMan** [comment]
macOS Monterey
Packing a custom app icon with `.icns`. 
Looks like `electron-builder` convert other icon format to `.icns`.

**Comment by caoxiemeihao** [comment]
This may explain the reason 👉 https://github.com/electron-vite/electron-vite-vue/issues/103#issuecomment-1096940315
