### ISSUE TITLE
使用serialport 报错No native build was found for platform[Help] the title of help wanted report,是哪里需要配置嘛?

### ISSUE THREAD

**Issue by zxklovetml** [electron-vite/electron-vite-vue#362]

**Comment by zxklovetml** [comment]
renderer({
      resolve: {
        serialport: () => ({ platform: 'node' }),
      },
    }),

已解决!

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/vite-plugin-electron-renderer/blob/v0.13.11/examples/quick-start/vite.config.ts#L12

**Comment by FarmersReact** [comment]
> https://github.com/electron-vite/vite-plugin-electron-renderer/blob/v0.13.11/examples/quick-start/vite.config.ts#L12

您好，我配置了这个还是报错，请问是哪里有问题？

**Comment by caoxiemeihao** [comment]
@FarmersReact 这个和主进程没关系，这个配置是给渲染进程使用的
主进程配置：

```diff
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    electron([
      {
        // 主进程入口文件
        entry: 'electron/main.ts',
+       vite: {
+         build: {
+           rollupOptions: {
+             external: ['serialport'],
+           },
+         },
+       },
      },
    ]),
  ],
})
```
