### ISSUE TITLE
移除示例代码

### ISSUE THREAD

**Issue by houxg** [electron-vite/electron-vite-vue#364]
首先非常感谢作者提供了如此便捷的插件，让我可以快速创建创建vite+electron工程。

但是作为面向正式生产使用的插件，还有一些建议，希望采纳：

1. 移除package.json中`author`字段。这对于生产使用者来说变成了一个必须的修改项。
2. 移除ipc示例代码。这对于新手来说非常友好，但是对于需要使用该插件快速搭建项目（这也是手脚架的意义所在），示例代码又变成了不可不删的部分，建议作为单独的demo repo提供。

**Comment by caoxiemeihao** [comment]
我考虑将 ipc 部分变成注释，说明 ipc 的使用方法可好

**Comment by houxg** [comment]
从脚手架来看，可能还是不要放在模板代码里比较好，写在插件readme中作为使用指引的扩展部分如何？

您可以这样试试，从一个老手的角度出发，使用这个插件去创建一个工程，如果有哪里需要修改/删除的，那可能就是需要要模板改动的地方了。参看electron-forge使用官方模板创建出来的工程，都是非常简洁的。

**Comment by caoxiemeihao** [comment]
forge 官方那个 Vite 模板也是我做的 🤣

**Comment by houxg** [comment]
看到了~本来还想等着forge vite正式版本出来，现在项目等不及了...

总之，非常感谢您的付出~

> forge 官方那个 Vite 模板也是我做的 🤣 那个 Vite 模板确实没啥基础代码，后面看情况不行把最基础的模板功集成到 create-electron-vite 中，和 forge 那么简单

**Comment by Elias-cug** [comment]
> 
请问作者 forge 的这个有链接吗
