### ISSUE TITLE
linux 打包后 ，执行安装包报错

### ISSUE THREAD

**Issue by zhangxiliang** [electron-vite/electron-vite-vue#365]
执行命令 ./electron-vue-vite-2.0.2.AppImage --no-sandbox --disable-gpu

报错异常如下
[3265:0404/154318.602755:ERROR:gpu_memory_buffer_support_x11.cc(49)] dri3 extension not supported.

同时在electron index.js
也加上了 app.disableHardwareAcceleration();
把硬件加速关闭了，还是报同样的异常

**Comment by caoxiemeihao** [comment]
这个可能你需要去 Electron 仓库提下 issues
