### ISSUE TITLE
在vue组件中引入assets里的图片失败

### ISSUE THREAD

**Issue by liyang9331** [electron-vite/electron-vite-vue#368]
#### Describe the problem you confuse
![image](https://user-images.githubusercontent.com/70904270/230883517-b8919d7c-5e17-4b01-8452-7867a07ef9aa.png)
![image](https://user-images.githubusercontent.com/70904270/230883779-5e022f21-a986-4ec6-b0c3-8c52c012d2bd.png)

**Comment by caoxiemeihao** [comment]
用 `import` 或者 `import.meta.glob`
