### ISSUE TITLE
css热重载编译错误

### ISSUE THREAD

**Issue by YI-ARCE** [electron-vite/electron-vite-vue#370]
[10024:0417/161556.844:ERROR:CONSOLE(0)] "[formatjs Error: MISSING_VALUE] The intl string context variable "REASON_PROPERTY_DECLARATION_CODE" was not provided to the string "请尝试移除 {REASON_PROPERTY_DECLARATION_CODE} 
或更改其值。"", source:  (0)

实测是使用了css处理器(less,scss...其余未知)的问题,会导致某个class下的属性添加后报以上错误,注释或不添加则正常,属性并不是固定的,测试下来报错的有user-select,font-size,align-items,align-content等

**Comment by YI-ARCE** [comment]
<style lang='less' scoped>
.yi-table-page {
  display: flex;
  background-color: var(--background-color);
  height: 60px;
  flex-direction: row-reverse;
  border-radius: 0 0 var(--theme-border-radius) var(--theme-border-radius);
  position: relative;

  .yi-table-page-action{
    display: flex;
    justify-content: center;
    align-items: center;

    .page-view{
      display: flex;
      justify-content: center;
      align-items: center;
      flex-direction: row;
      height: 100%;
      font-size: 14px;
      margin-right: -7.5px;
    }
  }
}
</style>
这是一段会报错的css
启动命令 electron-vite dev --watch

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by YI-ARCE** [comment]
> Can you provide a minimal reproduction repo?

7z package comes with a video demonstration of how to find the problem, trouble you
[electron-vite-file](https://resource.yiarce.cn/electron.zip)

**Comment by CafuChino** [comment]
It only happens on Electron 22.x,  when the dev tools language is set to Chinese. Upgrade Electron 23+ or set Chrome dev tools language to English can solve this problem. Related: https://chromium.googlesource.com/devtools/devtools-frontend/+/d7bbaba2b82bb3b8c90e8d47c1f36fba2182c5e5%5E%21/

**Comment by CafuChino** [comment]
And this was caused by setting "width" or "height" to the inline element on the current page, inline-block is also affected.

**Comment by YI-ARCE** [comment]
@CafuChino okay, thank you
