### ISSUE TITLE
 6 high severity vulnerabilities

### ISSUE THREAD

**Issue by bryaan** [electron-vite/electron-vite-vue#371]
Running `npm install` warns of vulns in packages.  Is it safe to run `  npm audit fix --force` to upgrade or will that cause breaking changes?  I don't see this issue with standard vue/vite templates so im assuming this is related to this repo.

```
6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

**Comment by caoxiemeihao** [comment]
Have a `package-lock.json` in you locally?
