### ISSUE TITLE
electron-vite 项目如何使用 ffi-napi

### ISSUE THREAD

**Issue by vanchain** [electron-vite/electron-vite-vue#372]
1.根据 ffi-napi 文档，使用了如下方法引入
**const ffi = require('ffi-napi');**
报错如下：
Uncaught ReferenceError: require is not defined
安装了 @types/node之后依旧报该错误
是否vite不支持require？如果支持，需要引入什么包？

2.require不行，改为import尝试
**import ffi from 'ffi-napi'**
报错如下：
index.js:1 Uncaught ReferenceError: process is not defined
该错误指向ffi.js本身，暂时没有找到解决方案

请问我该如何在项目中支持 **ffi-napi** ？
项目构成是：electron-vite1x   vite4x   vue3x

**Comment by caoxiemeihao** [comment]
去主进程中用

**Comment by delayhsiao** [comment]
主进程中require 然后提供一个方法给web交互

**Comment by vanchain** [comment]
主进程是否为 electron 项目中 app.whenReady() 所在的代码部分？
我尝试过在 **app.whenReady()** 里面使用 require，报如下错误：
Error: Error in native callback
&nbsp;&nbsp;&nbsp;&nbsp;at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
&nbsp;&nbsp;&nbsp;&nbsp;at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
&nbsp;&nbsp;&nbsp;&nbsp;at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1810)
&nbsp;&nbsp;&nbsp;&nbsp;at Module.load (node:internal/modules/cjs/loader:988:32)
&nbsp;&nbsp;&nbsp;&nbsp;at Module._load (node:internal/modules/cjs/loader:829:12)
&nbsp;&nbsp;&nbsp;&nbsp;at c._load (node:electron/js2c/asar_bundle:5:13343)
&nbsp;&nbsp;&nbsp;&nbsp;at Module.require (node:internal/modules/cjs/loader:1012:19)
&nbsp;&nbsp;&nbsp;&nbsp;at require (node:internal/modules/cjs/helpers:102:18)
&nbsp;&nbsp;&nbsp;&nbsp;at load (E:\w07820\web\electron-vite\node_modules\node-gyp-build\node-gyp-build.js:22:10)
&nbsp;&nbsp;&nbsp;&nbsp;at Object.<anonymous> (E:\w07820\web\electron-vite\node_modules\ref-napi\lib\ref.js:8:53)
我之前尝试过在vue总入口 main.ts 中加入了require，会报如下错误：
Uncaught ReferenceError: require is not defined
如果这两处都不是所说的主进程，能不能告知一下需要加在哪？
我是新手，请帮助一下，谢谢

**Comment by vanchain** [comment]
> 主进程中require 然后提供一个方法给web交互

主进程是否为 electron 项目中 app.whenReady() 所在的代码部分？
我尝试过在 **app.whenReady()** 里面使用 require，报如下错误：
Error: Error in native callback
&nbsp;&nbsp;&nbsp;&nbsp;at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
&nbsp;&nbsp;&nbsp;&nbsp;at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
&nbsp;&nbsp;&nbsp;&nbsp;at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1810)
&nbsp;&nbsp;&nbsp;&nbsp;at Module.load (node:internal/modules/cjs/loader:988:32)
&nbsp;&nbsp;&nbsp;&nbsp;at Module._load (node:internal/modules/cjs/loader:829:12)
&nbsp;&nbsp;&nbsp;&nbsp;at c._load (node:electron/js2c/asar_bundle:5:13343)
&nbsp;&nbsp;&nbsp;&nbsp;at Module.require (node:internal/modules/cjs/loader:1012:19)
&nbsp;&nbsp;&nbsp;&nbsp;at require (node:internal/modules/cjs/helpers:102:18)
&nbsp;&nbsp;&nbsp;&nbsp;at load (E:\w07820\web\electron-vite\node_modules\node-gyp-build\node-gyp-build.js:22:10)
&nbsp;&nbsp;&nbsp;&nbsp;at Object.<anonymous> (E:\w07820\web\electron-vite\node_modules\ref-napi\lib\ref.js:8:53)
我之前尝试过在vue总入口 main.ts 中加入了require，会报如下错误：
Uncaught ReferenceError: require is not defined
如果这两处都不是所说的主进程，能不能告知一下需要加在哪？
我是新手，请帮助一下，谢谢

**Comment by so1ve** [comment]
Error in native callback应该是你ffi用法不对吧

**Comment by Coder-XJ** [comment]
你是不是使用了vite-plugin-electron这个插件

**Comment by lizhen789** [comment]
我也是报这错
