### ISSUE TITLE
[Help] Install and use vue devtools

### ISSUE THREAD

**Issue by dcaldessa** [electron-vite/electron-vite-vue#373]
How do I install and use The Vue Devtools with this template? I would like to have them to debug my vue side of the app and store functions?

Is there a way I can use them or do I just debug through VSCode ( new to vscode btw) 

any help would be great 

thanks 
David

**Comment by delayhsiao** [comment]
maybe you can run your vue project in browser, then build and run based by electron when your project was well

**Comment by dcaldessa** [comment]
> maybe you can run your vue project in browser, then build and run based by electron when your project was well

not sure how to run vue in the browser with this template, when I use npm run dev it launches in an electron window. If I could do that run them at different times I would. If there is a way with out changing a bunch of stuff let me know otheriwse I need to know how to install the dev tools :)

**Comment by dcaldessa** [comment]
Doing some further research I found instructions on the electron documentation on how to install the vue dev tools. It work I now have access to the vue instance. Thanks for your suggestions. Ill close this issue now.

**Comment by delayhsiao** [comment]
yeah, i rememeber another way to link the vue app. you can use vue-devtools standalone mode to manage the vue app. document link -> [there](https://devtools.vuejs.org/guide/installation.html#using-global-package) 
to other guys who have same problem :)
