### ISSUE TITLE
[Help] 打包后如何在主进程中加载静态资源

### ISSUE THREAD

**Issue by whoeverimf5** [electron-vite/electron-vite-vue#379]
#### Describe the problem you confuse

public文件夹下放了一张图片，主进程中调用了子窗口win.loadFile()方法想要加载这张图片，但是图片加载失败了

**Comment by caoxiemeihao** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/26263658/236752698-a091eeeb-5081-4238-bd6b-fa35c1dff3b7.png">
这里有个现成的 `public` 文件夹访问路径
