### ISSUE TITLE
[Help] build 后的安装包在安装时会去升级由“另一个项目打包完成的安装包安装的程序”

### ISSUE THREAD

**Issue by 3DMXM** [electron-vite/electron-vite-vue#380]
听起来有点绕，就比如说：
我上一个项目“seo_ai_tools”, 
使用`yarn run build`,打包后生成了一个安装包，
然后我当前电脑使用安装包来安装程序。

接着，我现在的这个项目“gmm”,
同样使用`yarn run build`打包生成一个安装包，
在运行安装包安装时，会提示“已存在一个安装到当前用户的安装，即将进行升级”，

也就是说“gmm”的安装包会把“seo_ai_tools”安装的程序替换掉。

请问是需要修改哪个标识符吗

**Comment by 3DMXM** [comment]
补一张图片
[](https://mod.3dmgame.com/static/upload/mod/202305/MOD645c49c39401e.jpg)

**Comment by vipsunwei** [comment]
```
"build": {
    "appId": "com.ground.app",
    "asar": true,
    "files": [
      "out",
      "package.json"
    ],
    "productName": "天",
    "mac": {
      "icon": "build/512.png"
    },
    "win": {
      "icon": "build/512.png"
    },
    "nsis": {
      "oneClick": false,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "createDesktopShortcut": true,
      "createStartMenuShortcut": true
    }
  },
```


你检查一下package.json中  build-> appId  ,试试使用不同的appId

**Comment by HaoAu3** [comment]
electron-builder.json5或者package.json，里面的appId
https://www.electron.build/configuration/configuration

**Comment by caoxiemeihao** [comment]
你们一个个都是人才，说话又好听 😄

**Comment by 3DMXM** [comment]
感谢各位的指导，修改 `electron-builder.json5`文件里面的`appId`解决问题了
