### ISSUE TITLE
不同的打包渠道怎么输出不同的文件名称？

### ISSUE THREAD

**Issue by iQuick** [electron-vite/electron-vite-vue#381]
项目里配置了打包多个渠道，如何在打包的时候根据不同的渠道输出不同的名称呢？

**Comment by caoxiemeihao** [comment]
<img width="700" alt="image" src="https://github.com/electron-vite/electron-vite-vue/assets/26263658/be53b232-eef8-4659-8c39-8a3e02156fec">
你可以动态改变 `env.XXX_NAME` 达到目的。详情看 electron-builder 文档
https://www.electron.build/configuration/configuration#artifact-file-name-template
https://www.electron.build/file-patterns#file-macros
https://github.com/motdotla/dotenv-expand/blob/1cc80d02e1f8aa749253a04a2061c0fecb9bdb69/tests/.env

**Comment by iQuick** [comment]
![image](https://github.com/electron-vite/electron-vite-vue/assets/7509014/e9166027-8171-478d-9f98-f20542afa5f7)
我之前是放在这里处理的，但是我不知道 vite 的 chainWebpack 在哪里。
@caoxiemeihao

**Comment by caoxiemeihao** [comment]
你可以尝试配置多个 `electron-builder.json5` 举个例子：

```json
  "scripts": {
    "build": "npm run build:renderer && npm run build:name1 && npm run build:name2 && npm run build:name3",
    "build:renderer": "vue-tsc --noEmit && vite build",
    "build:name1": "electron-builder -c electron-builder-name1.json5",
    "build:name2": "electron-builder -c electron-builder-name2.json5",
    "build:name3": "electron-builder -c electron-builder-name3.json5"
  }
```

**Comment by iQuick** [comment]
@caoxiemeihao 感谢，我现在已经改成多配置编译了，也可以满足需求。
