### ISSUE TITLE
[Help] 我想知道热更新是怎么实现的

### ISSUE THREAD

**Issue by Ya-hui** [electron-vite/electron-vite-vue#386]
#### Describe the problem you confuse
我使用mac开发，开发工具vscode。

在我使用这个插件的时候，文件并没有显式的 common+s 保存， 同时也热更新了

比如我刚输入个空格 或者 换行 或者在敲代码还没敲完的情况下  就会热更新

https://github.com/electron-vite/electron-vite-vue/assets/13138164/e9ffad28-0e55-4fee-b4f1-f9066d5f25d5

**Comment by caoxiemeihao** [comment]
你 VSCode 开了自动保存吧

**Comment by Ya-hui** [comment]
没开，其他项目都不是这样的

**Comment by Ya-hui** [comment]
可能确实跟插件没关系， 跟我这边的前端脚手架的问题  跟 这个插件没有融合好

**Comment by caoxiemeihao** [comment]
HMR 用的是 Vite 自带的，文件一旦被 Vite 扫到被改了就会 HMR，插件默认只负责 Electron 主进程修改的重启
