### ISSUE TITLE
[Help] 打包图标设置问题

### ISSUE THREAD

**Issue by Ya-hui** [electron-vite/electron-vite-vue#387]
#### Describe the problem you confuse
实在是找了一圈也没找到解决方案，在mac平台上 我设置了一个1024x1024的icns

打包出来后在程序坞和启动栏中都比其他应用图标要大一圈

**Comment by Ya-hui** [comment]
我可以把图标设置小一点，外面填充一层透明解决，  
我想知道 这个是通病  还是有单独的配置

**Comment by caoxiemeihao** [comment]
https://www.electron.build/icons.html
<img width="470" alt="image" src="https://github.com/electron-vite/electron-vite-vue/assets/26263658/2f4df188-0b21-4111-a1f9-1b5ac24c63fd">
