### ISSUE TITLE
[Help] 如何动态的加载一些文件

### ISSUE THREAD

**Issue by Ya-hui** [electron-vite/electron-vite-vue#388]
#### Describe the problem you confuse
hello 我又来了 非常不好意思

碰到的一个问题 

我想遍历整个ipc目录下的controller模块 文件，  然后获取每个方法 进行批量 注册ipcmain.handle

我看dist-electron中没有生成controller目录 所以找不到文件

<img width="628" alt="image" src="https://github.com/electron-vite/electron-vite-vue/assets/13138164/56059bc3-0669-4a0f-8b35-2eb97d5a7179">
<img width="365" alt="image" src="https://github.com/electron-vite/electron-vite-vue/assets/13138164/87063ad0-3d7f-496a-95a9-4074af6092d0">

**Comment by caoxiemeihao** [comment]
`vite-plugin-electron` 使用的是 Bundle 方案，所有文件必须被 main.js 通过 import 引入且被构建成一个文件 main.js
1. 如果想构建多个入口，可以在 vite.config.ts 中配置 electron([]) 数组选项中增加对应的 entry
2. 如果 Bundle 方案不适合你，可以考虑使用 [vite-electron-plugin](https://github.com/caoxiemeihao/vite-electron-plugin)

**Comment by Ya-hui** [comment]
import.meta.glob 可以解决 我先这样使用吧

**Comment by Ya-hui** [comment]
对了 说一个题外话， 第一次使用electron  不太了解哈 ，我打完包之后300多M是 正常体积吗？  主进程基本上没啥代码， 渲染进程build之后 也就2M多

**Comment by caoxiemeihao** [comment]
你可能把 node_modules 给打包进去了
尝试放到 devDependencies 中能优化一下大小
如果有帮到你可以请我喝一杯☕

**Comment by Ya-hui** [comment]
好的，安排

**Comment by caoxiemeihao** [comment]
个人首页有二维码 (˵¯͒〰¯͒˵)

**Comment by Ya-hui** [comment]
已安排，别嫌少哈

你可能把 node_modules 给打包进去了
这句话我没太理解
我的electron-builder.json  

files:
    dist-electron
    dist

还是说electron-builder打包的时候会去找.package.json里的dependencies  依赖都给全部打包了？

如果是把dependencies依赖都给打包了， 那么需要双package.json解决？

**Comment by caoxiemeihao** [comment]
devDependencies 不会被打包

**Comment by Ya-hui** [comment]
我尝试这样去改动，但是build之后 不知道为什么  加载白屏了
<img width="1384" alt="image" src="https://github.com/electron-vite/electron-vite-vue/assets/13138164/c3195045-f6bd-45bd-b17d-c56dada23ec6">
文件地址不对了

<img width="596" alt="image" src="https://github.com/electron-vite/electron-vite-vue/assets/13138164/e772bec9-56e7-4733-b141-35bfdaa67fe5">

**Comment by caoxiemeihao** [comment]
别一下全都搬过去，可以一个个试下
在你没完全掌握它的运行机制之前

**Comment by so1ve** [comment]
> 已安排，别嫌少哈
> 
> 你可能把 node_modules 给打包进去了 这句话我没太理解 我的electron-builder.json
> 
> files: dist-electron dist
> 
> 还是说electron-builder打包的时候会去找.package.json里的dependencies 依赖都给全部打包了？
> 
> 如果是把dependencies依赖都给打包了， 那么需要双package.json解决？

意思是说，如果你把依赖装在dependencies里头的话，会额外把node_modules打包进去，当成开发依赖就不会
