### ISSUE TITLE
[Help] 如何打包 ./src/assets 這包資料夾

### ISSUE THREAD

**Issue by rong-huang** [electron-vite/electron-vite-vue#389]
#### Describe the problem you confuse
不好意思打擾了，
我在npm run build 後，執行檔案，發現我在main底下的function沒有讀 ./src/assets 這包資料夾底下的檔案外，vue也有一樣的狀況
![image](https://github.com/electron-vite/electron-vite-vue/assets/64836423/42aa82f4-11ff-4775-b19b-bde035e20221)

![image](https://github.com/electron-vite/electron-vite-vue/assets/64836423/e2af85a3-7946-4f72-bce7-11435175c6a9)

![image](https://github.com/electron-vite/electron-vite-vue/assets/64836423/c4600381-30f7-4821-a47c-5c46b548101e)

![image](https://github.com/electron-vite/electron-vite-vue/assets/64836423/2cf12520-f5ca-4724-abd5-506e806fb170)

![image](https://github.com/electron-vite/electron-vite-vue/assets/64836423/68f3f741-7695-417d-a723-cb1878f1edc9)

![image](https://github.com/electron-vite/electron-vite-vue/assets/64836423/e30e0583-35d4-40af-994f-ef567a68232c)

請我該如何將 ./src/assets/ 這包資料夾也打包進執行檔呢?

**Comment by caoxiemeihao** [comment]
放到 public 中

**Comment by rong-huang** [comment]
不好意思又打擾了，
我已將資料移動到public，但打包後仍然讀不到檔案，請問我需要更改electron-builder.json5嗎
![image](https://github.com/electron-vite/electron-vite-vue/assets/64836423/8d521273-0d35-4d27-959b-8f07bd230666)

![image](https://github.com/electron-vite/electron-vite-vue/assets/64836423/99cf5ee7-c1f0-4257-96c0-e2cddfe4e31c)

![image](https://github.com/electron-vite/electron-vite-vue/assets/64836423/69bef8fb-d6c6-4219-a18d-50fee4d7b87d)
