### ISSUE TITLE
[Help] 需要什么环境啊，比如node版本

### ISSUE THREAD

**Issue by hormers** [electron-vite/electron-vite-vue#390]
####  需要node版本几？
mac没有问题
我的是：
windows11
node：v18.15
yarn：v1.22.19
打包一直不动，请问是什么原因
![image](https://github.com/electron-vite/electron-vite-vue/assets/44894251/e0cc2fea-004f-40be-9f7f-398c64b77972)

**Comment by caoxiemeihao** [comment]
1. 配置 electron 镜像
2. 明天早上就好了，因为国外网速早上最快

**Comment by hormers** [comment]
> 1. 配置 electron 镜像
> 2. 明天早上就好了，因为国外网速早上最快

配置了镜像，现在又不动了，到了哪一步
![image](https://github.com/electron-vite/electron-vite-vue/assets/44894251/a2253269-1d39-4038-83c9-be64490d5b0c)
