### ISSUE TITLE
main.js我引入了puppeteer-core,开发环境正常，打包却报错！我该怎么配置打包项~

### ISSUE THREAD

**Issue by yaoshengli** [electron-vite/electron-vite-vue#392]

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by xianbinKit** [comment]
您好

`const puppeteer = require('puppeteer')

function createWindow() {
  puppeteer.launch().then(async (browser) => {
    const page = await browser.newPage()
    await page.goto('https://www.google.com')
    await page.screenshot({
      path: 'screenshot.jpg'
    })
    console.log('i am here')
    await browser.close()
  })`

其他都不改，错误截图，dev没问题， build:mac之后就出现：

<img width="505" alt="image" src="https://github.com/electron-vite/electron-vite-vue/assets/11937466/b7cd935b-1b58-4751-8388-b2bdbb0f0556">

**Comment by caoxiemeihao** [comment]
@xianbinKit 
把 `puppeteer` 放到 `dependenices` 中就好了

**Comment by yaoshengli** [comment]
external: [...Object.keys('dependencies' in pkg ? pkg.dependencies : {})].filter(
                  (v) =>
                    v != 'puppeteer-core' &&
                    v != 'pinia' &&
                    v != 'get-port' &&
                    v != 'uuid' &&
                    v != 'async-retry' &&
                    v != 'vue' &&
                    v != '@nestjs/common' &&
                    v != '@nestjs/core' &&
                    v != 'reflect-metadata' &&
                    v != 'rxjs',
                )
最后我好像是这么处理puppeteer-core结果就通过了

**Comment by xianbinKit** [comment]
@yaoshengli 请问这个是在哪个文件里设置的？

**Comment by wumingluren** [comment]
puppeteer-core 使用这个启动的时候需要一个浏览器路径，你是怎么设置的？
