### ISSUE TITLE
[Bug] 启用全局沙箱后 BrowserWindow.loadURL 时崩溃

### ISSUE THREAD

**Issue by yuyuko233** [electron-vite/electron-vite-vue#395]
在 `app.whenReady().then()` 之前启用全局沙箱会导致 Electron 应用崩溃, 错误信息为 ` ELIFECYCLE  Command failed with exit code 3221225477.` 但是在为单个进程启用沙箱没有问题

----

Before the `app.whenReady().then()`  the global sandbox can cause the Electron application to collapse, and the error message is ` ELIFECYCLE  Command failed with exit code 3221225477`. But there is no problem with enabling a sandbox for a single process.

---

相关复现流程如下:
1. 在 [electron-vite-vue](https://github.com/electron-vite/electron-vite-vue) 仓库的 `electron/main/index.ts` 文件内启用全局进程沙箱
2. 应用崩溃并在控制台提示错误信息 ` ELIFECYCLE  Command failed with exit code 3221225477.`

我的 `electron/main/index.ts` 文件: [链接](https://gist.github.com/yuyuko233/b6517a622c552fd76747850c6c52a5cf)

-----

The related duplication process is as follows:

1. Enable the global process sandbox in the `electron/main/index.ts` file of  [electron-vite-vue](https://github.com/electron-vite/electron-vite-vue) repo.

2. Application collapse and prompt error message on the console `ELIFECYCLE  Command failed with exit code 3221225477.`

My `electron/main/index.ts` file: [Link](https://gist.github.com/yuyuko233/b6517a622c552fd76747850c6c52a5cf)

**Comment by yuyuko233** [comment]
win.loadFile也不行也是一样的报错

**Comment by caoxiemeihao** [comment]
http://man.hubwiz.com/docset/electron.docset/Contents/Resources/Documents/docs/api/sandbox-option.html
你看下文档，沙盒模式下渲染进程无法使用 Node.js API
<img width="1095" alt="image" src="https://github.com/electron-vite/electron-vite-vue/assets/26263658/61bd2870-afee-4e9f-9c6c-05e728e76639">
