### ISSUE TITLE
[Help] 银河麒麟系统npm run dev 报错

### ISSUE THREAD

**Issue by wpbjiuy** [electron-vite/electron-vite-vue#396]
/home/user/ZDXSoftbox/node_modules/electron/dist/electron: /usr/lib/aarch64-linux-gnu/libnss3.so: version `NSS_3.30' not found (required by /home/user/ZDXSoftbox/node_modules/electron/dist/electron)

**Comment by caoxiemeihao** [comment]
这个你得去 electron 仓库提 issue

**Comment by wpbjiuy** [comment]
好的
