### ISSUE TITLE
[Bug] preload.js 文件不拆分 

### ISSUE THREAD

**Issue by ggymm** [electron-vite/electron-vite-vue#397]
### vite.config.ts配置
```javascript
{
  entry: 'electron/preload/view.ts',
  vite: {
    build: {
      outDir: 'build/dist-electron/preload',
      minify: true,
      sourcemap: false,
      rollupOptions: {
        output: {
          manualChunks: undefined
        }
      }
    }
  },
  onstart(options) {
    options.reload()
  }
}
```

### preload文件夹输出
![image](https://github.com/electron-vite/vite-plugin-electron/assets/20694755/7787dc18-d6c3-4907-9bfe-dc4ce07397ed)

想让electron/preload/view.ts的输出文件为单个build/dist-electron/preload/view.js

因为在electron的在开启了sandbox开启时，preload不能require除了electron，node之外的包。所以打包拆分之后会导致
view-a17d7368.js文件无法加载

### 重现仓库
[地址](https://github.com/ggymm/electron-vite-vue-test)

**Comment by jellytrue** [comment]
same issue here

**Comment by spianmo** [comment]
same issue here

**Comment by ggymm** [comment]
try this
https://github.com/electron-vite/vite-plugin-electron/issues/141

**Comment by caoxiemeihao** [comment]
Docs here.
https://electron-vite.github.io/guide/preload-not-split.html
