### ISSUE TITLE
macos 输入框内 中文输入法没有提示框

### ISSUE THREAD

**Issue by wiilruo** [electron-vite/electron-vite-vue#399]
#### Describe the problem you confuse
macos 输入框内 中文输入法没有提示框

<img width="643" alt="image" src="https://github.com/electron-vite/electron-vite-vue/assets/130130871/ec841878-4f3c-4f2b-9e0c-4bde2eff3591">
尝试过 去除所有样式  使用原生输入框 依旧没有中文输入法提示

**Comment by caoxiemeihao** [comment]
换个 Electron 版本试试
