### ISSUE TITLE
[Help] how to use electron-forge build app

### ISSUE THREAD

**Issue by AnkerLeng** [electron-vite/electron-vite-vue#403]
how to use electron-forge in this tool build app

**Comment by caoxiemeihao** [comment]
- [ ] TODO
https://electron-vite.github.io/build/electron-forge.html

**Comment by brandonxiang** [comment]
why not this template use electron-forge?

**Comment by caoxiemeihao** [comment]
Just because `electron-builder` only focused on packaging Electron App.
There maybe plans for `electron-forge` in the future. I am working hard to make forge more friendly and support Vite.
