### ISSUE TITLE
[Help] `npm create electron-vite` behave weird

### ISSUE THREAD

**Issue by MagicalBomb** [electron-vite/electron-vite-vue#408]
#### Describe the problem you confuse
The created `vite.config.ts` is not same as docs

For example:
the main process entry file, my vite.config.ts file finds it at 'electron/main.ts', but your docs says it should locate at 'electron/main/index.ts'

```shell
❯ npm create electron-vite
✔ Project name: … test
✔ Project template: › Vue

Scaffolding project in /Users/wangzhipeng/Desktop/Code/test...

Done. Now run:

  cd test
  npm install
  npm run dev
```

```
# vite.config.ts

import { defineConfig } from 'vite'
import electron from 'vite-plugin-electron'
import renderer from 'vite-plugin-electron-renderer'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    electron([
      {
        // Main-Process entry file of the Electron App.
        entry: 'electron/main.ts',
      },
      {
        entry: 'electron/preload.ts',
        onstart(options) {
          // Notify the Renderer-Process to reload the page when the Preload-Scripts build is complete, 
          // instead of restarting the entire Electron App.
          options.reload()
        },
      },
    ]),
    renderer(),
  ],
})

```

```
test/
├── README.md
├── electron
│   ├── electron-env.d.ts
│   ├── main.ts
│   └── preload.ts
├── electron-builder.json5
├── index.html
├── package.json
├── public
│   ├── electron-vite.animate.svg
│   ├── electron-vite.svg
│   └── vite.svg
├── src
│   ├── App.vue
│   ├── assets
│   │   └── vue.svg
│   ├── components
│   │   └── HelloWorld.vue
│   ├── main.ts
│   ├── style.css
│   └── vite-env.d.ts
├── tsconfig.json
├── tsconfig.node.json
└── vite.config.ts
```

**Comment by MagicalBomb** [comment]
> You can submit a PR for fix it!

I am new to frontend developing, so I am not sure it's bug or not.  So It's a bug?

**Comment by caoxiemeihao** [comment]
`create electron-vite` just provide a boilerplate, but it not limit waht `entry` path of a project.
You event use others likes `electron/foo.ts`, `electron/bar/index.ts`.

**Comment by MagicalBomb** [comment]
> `create electron-vite` just provide a boilerplate, but it not limit waht `entry` path of a project. You even use other path, likes `electron/foo.ts`, `electron/bar/index.ts`.

Yeah, I know there is no limit on entry path. Actually, I mean the project created by command `npm create electron-vite` is not same as main branch of this repo.

# For example
The tsconfig.node.json file in this repo is something like following
```json
{
  "compilerOptions": {
    ...
  },
  "include": ["vite.config.ts", "package.json", "electron"]
}
```

But the actual tsconfig.node.json in project created by `npm create electron-vite` like following:
```json
{
  "compilerOptions": {
    ...
  },
  "include": ["vite.config.ts"]
}
```

So what I mean is that it is clearly stated on the document that we can use 'npm create electron-vite' to create boilerplate , but the final creation is different from this repo. I wonder if this is a bug or something I made mistaken
