### ISSUE TITLE
[Bug] Ucaught Error: Dynamic require of "electron" is not supported  

### ISSUE THREAD

**Issue by bigBron** [electron-vite/electron-vite-vue#409]
创建新项目，直接在App.vue中导入ipcRenderer即可复现。
然后打开控制台显示报错：Ucaught Error: Dynamic require of "electron" is not supported  
```vue
<script setup>
import HelloWorld from './components/HelloWorld.vue'
import {ipcRenderer} from 'electron'
ipcRenderer.send("ok")
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/electron-vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

```

**Comment by caoxiemeihao** [comment]
样板代码不是能用吗？你改了东西？

**Comment by bigBron** [comment]
用法搞错了，不好意思

**Comment by suka233333** [comment]
> 用法搞错了，不好意思

我也遇到了  具体是引入vue-router后，使用 window.open(`/自定义路由`)后，打开的窗口显示为空白，报错提示为这个
Dynamic require of "electron" is not supported

请问层主咋解决的？

**Comment by History-1024** [comment]
> > 用法搞错了，不好意思
> 
> 我也遇到了 具体是引入vue-router后，使用 window.open(`/自定义路由`)后，打开的窗口显示为空白，报错提示为这个 Dynamic require of "electron" is not supported
> 
> 请问层主咋解决的？

我也遇到了 ……你解决了吗……

**Comment by RSS1102** [comment]
> > > 用法搞错了，不好意思
> > 
> > 
> > 我也遇到了 具体是引入vue-router后，使用 window.open(`/自定义路由`)后，打开的窗口显示为空白，报错提示为这个 Dynamic require of "electron" is not supported
> > 请问层主咋解决的？
> 
> 我也遇到了 ……你解决了吗……

查看了你的repo，你使用vite插件不是本组织的插件。

**Comment by redisviewer** [comment]
我也遇到了, 请问如何解决 @bigBron @caoxiemeihao

**Comment by RSS1102** [comment]
> 我也遇到了, 请问如何解决 @bigBron @caoxiemeihao
请提供你的最小复现，或者electron相关的依赖名称和版本。

**Comment by RSS1102** [comment]
> 我也遇到了有人解决了吗

请提供你的最小复现，或者electron相关的依赖名称和版本。

**Comment by RSS1102** [comment]
提出这个问题的楼主使用的是另一个electron相关依赖，如果有相似问题的，请重新打开新的issue并且附上自己的最小复现，或者是`package.json`的相关依赖和版本，谢谢。

**Comment by caoxiemeihao** [comment]
`vur-router` 可能引起的一种报错可能 👉 https://github.com/electron-vite/vite-plugin-electron/issues/220
