### ISSUE TITLE
【打包错误】打包出差+import报错

### ISSUE THREAD

**Issue by illusionGD** [electron-vite/electron-vite-vue#410]
#### Describe the problem you confuse
1、运行打包命令出差：npm run build
![image](https://github.com/electron-vite/electron-vite-vue/assets/72918346/6f8f8a3b-302e-4971-81bd-198c4be43e35)
2、import错误：已经设置了moduleResolution：node，但是没用，搜索不到对应模块
![image](https://github.com/electron-vite/electron-vite-vue/assets/72918346/545b31d5-0f96-4cdd-8e09-ff5de906cf3e)

tsconfig.json:
{
    "compilerOptions": {
        "target": "ES2020",
        "useDefineForClassFields": true,
        "module": "ESNext",
        "lib": [
            "ES2020",
            "DOM",
            "DOM.Iterable"
        ],
        "skipLibCheck": true,
        /* Bundler mode */
        "moduleResolution": "Node",
        "resolveJsonModule": true,
        "isolatedModules": false,
        "noEmit": true,
        "jsx": "preserve",
        /* Linting */
        "strict": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noFallthroughCasesInSwitch": true
    },
    "include": [
        "src/**/*.ts",
        "src/**/*.d.ts",
        "src/**/*.tsx",
        "src/**/*.vue",
        "electron"
    ],
    "paths": {
        "@/*": [
            "src/*"
        ],
        "~/*": [
            "public/*"
        ]
    },
    "references": [
        {
            "path": "./tsconfig.node.json"
        }
    ],
    "exclude": [
        "node_modules"
    ],
    "ts-node": {
        "esm": true
    }
}

**Comment by caoxiemeihao** [comment]
你这个问题非模板代码问题

**Comment by illusionGD** [comment]
> 你这个问题非模板代码问题

所以请问要怎么解决

**Comment by caoxiemeihao** [comment]
所以付费解决
