### ISSUE TITLE
[Help] electron-vite Puppeteer project

### ISSUE THREAD

**Issue by xianbinKit** [electron-vite/electron-vite-vue#411]
#### Describe the problem you confuse

大家好，

可不可以提供一个electron-vite 安装了puppeteer的模板 ？ 

目前是在mac下，可以build:mac, 但是打开软件的时候报错。 

希望可以有一个直接clone下来就能build的project.

感谢

**Comment by caoxiemeihao** [comment]
V我50￥？

**Comment by xianbinKit** [comment]
puppeteer 搞定了， 在Mac下build的windows办法无法打开。。。

全是问题，从入门到放弃。。。

**Comment by caoxiemeihao** [comment]
多百度百度，实在不行用 elecctron 官方的 forge

**Comment by wumingluren** [comment]
怎么解决的？
