### ISSUE TITLE
[Help] Enable contextIsolation and use contextBridge

### ISSUE THREAD

**Issue by luciano-work** [electron-vite/electron-vite-vue#412]
How to enable [contextBridge](https://www.electronjs.org/docs/latest/api/context-bridge)  for more secure app?
I have created a new app using `npm create electron-vite` and enable contextIsolation, after that I get this error message:
```log
chunk-NAVY3LVQ.js?v=7d12685a:6 Uncaught Error: Dynamic require of "fs/promises" is not supported
    at chunk-NAVY3LVQ.js?v=7d12685a:6:9
    at promises.mjs:1:50
```
 
![image](https://github.com/vuejs/language-tools/assets/12519008/27fba4bb-b633-4216-8b1f-9300e365517a)

```javascript
win = new BrowserWindow({
    title: 'Main window',
    icon: join(process.env.PUBLIC, 'favicon.ico'),
    webPreferences: {
      preload,
      // Warning: Enable nodeIntegration and disable contextIsolation is not secure in production
      // Consider using contextBridge.exposeInMainWorld
      // Read more on https://www.electronjs.org/docs/latest/tutorial/context-isolation
      nodeIntegration: true,
      // contextIsolation: false,
    },
  })
  ```
  
  All the best ;)

**Comment by AutismPatient** [comment]
add
-  contextIsolation: true

**Comment by luciano-work** [comment]
Hi @AutismPatient.
by default `contextIsolation` is true. In my example I have comment `contextIsolation` to enabled.

**Comment by caoxiemeihao** [comment]
Maby the project created by `create electron-vite` is better for you.
