### ISSUE TITLE
[Help] 这个多窗体配置也太麻烦了吧

### ISSUE THREAD

**Issue by moom-en** [electron-vite/electron-vite-vue#417]
#### Describe the problem you confuse
每个窗体都还要增加vite配置文件，能否直接用一个vite配置文件即可，不然很多窗体要写很多个文件，实在难受啊

**Comment by caoxiemeihao** [comment]
你需要明白你做的多窗口的功能区分颗粒度，是你自己掌握不好它，不是它很复杂。
单配置文件 👉 https://github.com/electron-vite/vite-plugin-electron/tree/main/examples/multiple-renderer
多配置文件 👉 https://github.com/electron-vite/vite-plugin-electron/tree/main/examples/multiple-window

**Comment by moom-en** [comment]
你是真能装啊，说这东西配置太复杂了还不乐意？

**Comment by caoxiemeihao** [comment]
换一个吧，我这个除了装干不了别的
