### ISSUE TITLE
一打包就报错tsconfig 设置无效

### ISSUE THREAD

**Issue by nbqcode** [electron-vite/electron-vite-vue#428]
![image](https://github.com/electron-vite/electron-vite-vue/assets/126157699/e221693d-6723-4e51-bef1-47bb4b6dbea3)

**Comment by caoxiemeihao** [comment]
改动了哪些东西?

**Comment by funnyqueen** [comment]
请问要怎么解决这个问题呢？我是mac电脑，node是14.20.0

**Comment by watchingfun** [comment]
> 请问要怎么解决这个问题呢？我是mac电脑，node是14.20.0

你不提供一个最小复现，大伙很难办啊

**Comment by simuusang** [comment]
node 版本需要 16 以上
