### ISSUE TITLE
[Help] 我如何让一个ts文件能同时被electron和src下的文件夹引入使用

### ISSUE THREAD

**Issue by watchingfun** [electron-vite/electron-vite-vue#429]
#### Describe the problem you confuse
我有一些常量，我定义在electron文件夹下了，同时被electron和src下的文件引入使用；因为我不想拷贝一份到src下，这样有改动也不好维护；现在有个问题，我npm run dev是没有任何问题的，但是build就会报错；
![image](https://github.com/electron-vite/electron-vite-vue/assets/22067924/f2f1e8cb-a282-4fa7-bea2-ef1cc5d19533)
![image](https://github.com/electron-vite/electron-vite-vue/assets/22067924/7b63fafa-6339-49a9-81ec-c4a3e07cfc60)

**Comment by watchingfun** [comment]
我解决了，把tsconfig.node.json复制一份到electron文件夹下，然后文件里include只保留electron，然后原先的tsconfig.node.json文件的include去除electron

**Comment by zzz9527me** [comment]
> 我解决了，把tsconfig.node.json复制一份到electron文件夹下，然后文件里include只保留electron，然后原先的tsconfig.node.json文件的include去除electron

你好，问下，按你说的，编译好像报错了。这里需要做其它一些修改吗。。

**Comment by zzz9527me** [comment]
> > 我解决了，把tsconfig.node.json复制一份到electron文件夹下，然后文件里include只保留electron，然后原先的tsconfig.node.json文件的include去除electron
> 
> 你好，问下，按你说的，编译好像报错了。这里需要做其它一些修改吗。。

解决了。不过感觉这种方式不友好, 很多 ../../../electron 。 能不能像vue那样，配置个相对路径, 像 @/electron/xx/xx 这样的

**Comment by watchingfun** [comment]
> > > 我解决了，把tsconfig.node.json复制一份到electron文件夹下，然后文件里include只保留electron，然后原先的tsconfig.node.json文件的include去除electron
> > 
> > 
> > 你好，问下，按你说的，编译好像报错了。这里需要做其它一些修改吗。。
> 
> 解决了。不过感觉这种方式不友好, 很多 ../../../electron 。 能不能像vue那样，配置个相对路径, 像 @/electron/xx/xx 这样的

tsconfig.json也可以配置别名，你可以参考我正在写的项目 https://github.com/watchingfun/Joi
