### ISSUE TITLE
[Help] Running built app.exe has error of required of ESM module

### ISSUE THREAD

**Issue by alisherafat01** [electron-vite/electron-vite-vue#440]
I'm developing an app and everything is working in dev mode but when I build app and running app.exe it shows the following error and I can't find out which package is complaining!!

![app exe rrorr](https://github.com/electron-vite/electron-vite-vue/assets/13902663/01dc1f77-0af9-4fc9-9ca5-a46d50eb2515)

I am really stocked :\

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by alisherafat01** [comment]
@caoxiemeihao  Umm no, it would be great if you have any clue or something

**Comment by ChrisKuBa** [comment]
please see also
https://github.com/alex8088/electron-vite/issues/294#issuecomment-1805611396

**Comment by alisherafat01** [comment]
I don't know what was happened but after I removed node_modues and use npm instead of pnpm problem solved! so I close the thread.
