### ISSUE TITLE
为什么不用electronforge

### ISSUE THREAD

**Issue by captainIT** [electron-vite/electron-vite-vue#452]
[electronforge](https://github.com/electron/forge)，初始化可以选择vite+ts模板，打包和发布也非常方便 !

**Comment by captainIT** [comment]
[also support vue3](https://www.electronforge.io/guides/framework-integration/vue-3)

**Comment by caoxiemeihao** [comment]
等这个 PR 你可以顺势切换到 Forge https://github.com/electron/forge/pull/3336
