### ISSUE TITLE
[Help] support of jsx

### ISSUE THREAD

**Issue by tjc0726** [electron-vite/electron-vite-vue#455]
#### Describe the problem you confuse
Hi, Since the last time I merged your code, the nodeintergration is not effective despite I set it to ture, which leads to jsx is not usable, since it need node module react to work.

`Uncaught (in promise) ReferenceError: React is not defined`

Wonder if there's any solution to fix jsx and why nodeintergration is not working any more

Thanks!

**Comment by caoxiemeihao** [comment]
<img width="777" alt="image" src="https://github.com/electron-vite/electron-vite-vue/assets/26263658/42483ae1-d56b-4ae0-87e4-1102e98a099f">

https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx

You need to add `@vitejs/plugin-vue-jsx` to you `vite.config.ts`

---

About `nodeintergration` is disabled by default now. Just consistent with electron official recommend.

**Comment by tjc0726** [comment]
Thank you! you're very gorgeous! I love you!

**Comment by tjc0726** [comment]
Sorry to bother again,but every line involve with jsx is marked as
`"error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists"`
thus I can't run `npm run build`
Thank you in advance!

**Comment by tjc0726** [comment]
> Sorry to bother again,but every line involve with jsx is marked as `"error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists"` thus I can't run `npm run build` Thank you in advance!

I figured it out, just add "jsxImportSource": "vue"  in tsconfig.json according to
![image](https://github.com/electron-vite/electron-vite-vue/assets/49085201/d3745a58-7f6e-4ea8-90d6-6cc14a9da7ff)


I'm genius
