### ISSUE TITLE
[Help] 如何在根目录没有index.html的情况下正常构建

### ISSUE THREAD

**Issue by penggelies07** [electron-vite/electron-vite-vue#457]
#### Describe the problem you confuse
你好，我正在使用你的模版。我在这个模版上稍微改动了一下，我希望将renderer的代码与打包项目分离，
在开发环境通过win.loadURL(localhost)调试，正式环境时renderer的dist通过外部npm包形式注入

发现在执行 npm start 的时候没有问题。
但是在执行 npm run build 的时候出现了以下报错：
![screenshot-20240111-181239](https://github.com/electron-vite/electron-vite-vue/assets/20084372/d7e1cbcc-7d34-4260-8c7f-9a7be478800c)

请问是什么原因导致的呢？期待你的帮助，非常感谢🙏

[electron-template.zip](https://github.com/electron-vite/electron-vite-vue/files/13901801/electron-template.zip)

**Comment by caoxiemeihao** [comment]
按照 Vite 的多入口配置即可 https://vitejs.dev/guide/build.html#multi-page-app

```diff
export default defineConfig(({ command }) => {
  fs.rmSync('electron/preload/dist', { recursive: true, force: true });
  fs.rmSync('electron/main/dist', { recursive: true, force: true });

  const isServe = command === 'serve';
  const isBuild = command === 'build';
  const sourcemap = isServe || !!process.env.VSCODE_DEBUG;

  return {
+   build: {
+     rollupOptions: {
+       input: 'electron/renderer/dist/index.html',
+     },
+   },
    plugins: [
      electron({
```
