### ISSUE TITLE
[Help] 如何在vue中使用Web Worker

### ISSUE THREAD

**Issue by maxoyed** [electron-vite/electron-vite-vue#458]
找了一圈没找到在 electron-vite-vue 中使用 Web Worker 的示例，大佬能给个简单的 example 吗😭

**Comment by mundane799699** [comment]
解决了吗，我也想知道如何在electron-vite中使用worker线程

**Comment by subframe7536** [comment]
https://github.com/subframe7536/electron-vite-monorepo
