### ISSUE TITLE
[Help] An error occurred while installing dependencieslp wanted report

### ISSUE THREAD

**Issue by Dinowritecode** [electron-vite/electron-vite-vue#459]
I have been experiencing this type of error while running NPM I, and I have also encountered this issue when building an Electron+Vue project before. Even when using your template to build, errors still occur. This problem has been bothering me for a long time, please help me
![1](https://github.com/electron-vite/electron-vite-vue/assets/114334287/274ebaa7-7188-44d4-9c00-1f86f5b77bc4)

**Comment by RSS1102** [comment]
It seems to be a permission issue, you can delete the `node_modules` frist, or try using a command line like `yarn i`?
