### ISSUE TITLE
[Question] 后续打包如何换成Electron Forge

### ISSUE THREAD

**Issue by binhtml5** [electron-vite/electron-vite-vue#460]
#### Describe the problem you confuse
 后续打包如何换成Electron Forge

**Comment by RSS1102** [comment]
可以直接进行替换`Electron Forge`。
[vite-plugin-electron-renderer](https://github.com/electron-vite/vite-plugin-electron-renderer)、[vite-plugin-electron-preload](https://github.com/electron-vite/vite-plugin-electron-preload)同时适用于Electron⚡️Vite和Electron Forge。

**Comment by binhtml5** [comment]
好的，谢谢
