### ISSUE TITLE
你好，在这个项目模板中怎么做窗口之间的通信呢？ 

### ISSUE THREAD

**Issue by History-1024** [electron-vite/electron-vite-vue#461]
在我的需求中，有一个窗口之间传递参数的要求，需要从父窗口传递到子窗口。我打算用主线程来进行通信的传递。但是这样貌似不支持，会报错，请教一下怎么怎么弄？
![image](https://github.com/electron-vite/electron-vite-vue/assets/65716967/2d57c1b7-3aea-4a8d-a0ea-5573f7de6cf1)
![image](https://github.com/electron-vite/electron-vite-vue/assets/65716967/e69c568d-13e1-4b5b-9022-091e5d111ea8)

**Comment by History-1024** [comment]
再补充一下，我在父窗口中可以使用preload定义的window.electronApi。在子窗口中不到

**Comment by RSS1102** [comment]
a.ts
```ts
ipcRenderer.send('a-sendMsgMain', msg)
```
main.ts
```ts
ipcMain.on('a-sendMsgMain', (e, msg) => {
	childWin.webContents.send('b-msgFromMain', msg)  // childWin为B窗口
})
```
b.ts
```ts
    ipcRenderer.on('b-msgFromMain', (e, message) => {
        console.log(message)
    });
```

**Comment by History-1024** [comment]
ipcRenderer 我在vue组件引入之后 就会报错，如图报错
![image](https://github.com/electron-vite/electron-vite-vue/assets/65716967/5ed9ba66-ee05-43b7-b8c6-a208c1b0bc9e)
代码 b.ts
![image](https://github.com/electron-vite/electron-vite-vue/assets/65716967/1fe93e6d-0501-406c-9cf9-5f50f0867b50)
代码 main.ts （这里我单独把创建子窗口的方法写在了一个文件中）
![image](https://github.com/electron-vite/electron-vite-vue/assets/65716967/a494e088-1b45-476d-8761-fcfef4e4fb32)
代码a.ts
![image](https://github.com/electron-vite/electron-vite-vue/assets/65716967/7197425b-3e5e-4549-ad5c-7c1c5c500c1d)
现在的问题是，为什么引入electron就会有报错出现？

**Comment by History-1024** [comment]
https://github.com/History-1024/DEMO-ELECTRON 这个demo
