### ISSUE TITLE
打包构建时报错  npm run build:win

### ISSUE THREAD

**Issue by History-1024** [electron-vite/electron-vite-vue#462]
#### Describe the bug
打包的时候这个有问题啊
![image](https://github.com/electron-vite/electron-vite-vue/assets/65716967/847e53e1-1909-465b-9526-95acd58b6d76)

**Comment by haokejie** [comment]
这个是网络环境问题，换一个稳定的环境，或者上科技

**Comment by RSS1102** [comment]
请查看：https://github.com/electron-vite/electron-vite-vue/blob/main/.npmrc#L6

**Comment by History-1024** [comment]
> 这个是网络环境问题，换一个稳定的环境，或者上科技

好的谢谢您

**Comment by History-1024** [comment]
> 请查看：https://github.com/electron-vite/electron-vite-vue/blob/main/.npmrc#L6

非常感谢

**Comment by History-1024** [comment]
我现在打包完成了 但是这个应用跑起来 是一空白页面，这是什么原因？![image](https://github.com/electron-vite/electron-vite-vue/assets/65716967/f59a1fe5-9a1c-495a-b396-44f1d8ba60bd)空白的页面
下面是打完包的文件夹
![image](https://github.com/electron-vite/electron-vite-vue/assets/65716967/2f70919f-164e-4054-928e-e646eb3ea2c1)
![image](https://github.com/electron-vite/electron-vite-vue/assets/65716967/7ac5aad4-fe86-4db6-82f2-9ee1740a1105)

**Comment by RSS1102** [comment]
模板项目？或者请提供最小复现。

**Comment by History-1024** [comment]
> 模板项目？或者请提供最小复现。

我怎么提供项目模板给你们？

**Comment by RSS1102** [comment]
> > 模板项目？或者请提供最小复现。
> 
> 我怎么提供项目模板给你们？

可以提供一个最小的github仓库地址

**Comment by History-1024** [comment]
> > > 模板项目？或者请提供最小复现。
> > 
> > 
> > 我怎么提供项目模板给你们？
> 
> 可以提供一个最小的github仓库地址

https://github.com/History-1024/DEMO-ELECTRON
