### ISSUE TITLE
麻烦帮忙看一下。在生产环境启动后，页面空白。在开发环境是没问题的。

### ISSUE THREAD

**Issue by History-1024** [electron-vite/electron-vite-vue#463]
最新案例地址：https://github.com/History-1024/DEMO-ELECTRON
这是开发环境下的页面
![image](https://github.com/electron-vite/electron-vite-vue/assets/65716967/8c0a5057-c3d8-407d-8e98-48255053bf86)
这是生产环境的
![image](https://github.com/electron-vite/electron-vite-vue/assets/65716967/c5643cf9-71cc-498f-b7b7-cfd490621515)

**Comment by RSS1102** [comment]
已经说了:根据你提供的最小复现，你的项目不是这个项目的。

**Comment by History-1024** [comment]
> 已经说了:根据你提供的最小复现，你的项目不是这个项目的。

额 我把项目换成你们的了 更新了仓库的……

**Comment by RSS1102** [comment]
> > 已经说了:根据你提供的最小复现，你的项目不是这个项目的。
> 
> 额 我把项目换成你们的了 更新了仓库的……

你也不说...谁知道你换了啊.....看看楼上的建议。
