### ISSUE TITLE
打包electron报x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by HelloGGX** [electron-vite/electron-vite-vue#465]
<img width="429" alt="image" src="https://github.com/electron-vite/electron-vite-vue/assets/19381672/da8b660d-d6e2-4089-84dd-0c81b8ad82a5">

**Comment by subframe7536** [comment]
用 https://npmmirror.com/

**Comment by RSS1102** [comment]
see https://github.com/electron-vite/electron-vite-vue/blob/main/.npmrc#L6
