### ISSUE TITLE
[Bug] 升级Electron v29后渲染进程ipcRender报错

### ISSUE THREAD

**Issue by fisheep01** [electron-vite/electron-vite-vue#467]
今天Electron更新了29.0.0版本，我在项目中同步升级了一下，导致了渲染进程报错，具体报错如图
![image](https://github.com/electron-vite/electron-vite-vue/assets/11489830/6ff35b44-2db7-4af7-beee-e39f425fe881)

**Comment by fisheep01** [comment]
> ![image](https://private-user-images.githubusercontent.com/81673017/306179738-bda2847b-8ff5-480f-bbea-18e7fd7f0aaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTY0OTIsIm5iZiI6MTcwODQxNjE5MiwicGF0aCI6Ii84MTY3MzAxNy8zMDYxNzk3MzgtYmRhMjg0N2ItOGZmNS00ODBmLWJiZWEtMThlN2ZkN2YwYWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA4MDMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMjIzNjM3ZWI3YzYwYzc1YjBkNTg3ZjMyMjZjOTdiOWQ1NzdmYzM4ZjBkNzk1MDM1OWM0YjJkODc2MDM0ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j7HW6P6pyRzx3c4XGhzHR2tybiKYChTlfayT1jrDeGk)
> 
> 可能是electron安装失败，可以参考配置：https://github.com/electron-vite/electron-vite-react/blob/main/.npmrc#L6

electron安装是正常的，只是渲染进程的ipcRenderer会报错，应该是框架中自带的preload.ts的实现有问题，如下图部分
![image](https://github.com/electron-vite/electron-vite-vue/assets/11489830/ce5896c4-0663-4ff2-b1a9-19fb7dea3362)
作者只是遍历了自有属性，而从Electron29开始，不知道什么原因，ipcRenderer的方法是由上层原型继承而来，从而导致了遍历不到方法

**Comment by koumoe** [comment]
今天 nuc 后出现了 同样的问题.

**Comment by subframe7536** [comment]
原因：https://www.electronjs.org/blog/electron-29-0#behavior-changed-ipcrenderer-can-no-longer-be-sent-over-the-contextbridge

我写了一个[类型安全的IPC库](https://github.com/subframe7536/typesafe-electron-ipc)，可以看看
