### ISSUE TITLE
[Help] 希望加个eslint。谢谢

### ISSUE THREAD

**Issue by wjx0912** [electron-vite/electron-vite-vue#472]
.eslintrc配置文件，规则可以严格一些；以及package.json的npm run lint

这个可以作为参考：https://github.com/cmdfas/typescript-eslint-project

**Comment by caoxiemeihao** [comment]
Vite 官方的 Vue 模板也没有加 `eslint` 用的`vue-tsc` 做代码检查.
当然主进程部分加 eslint 还是有一定争议的，有些刚入门的同学很不习惯用 `eslint`.
如果你有这个需求，推荐你使用 `create electron-vite` 创建一个 `react` 工程，自带 `eslint`.
