### ISSUE TITLE
[Help]如何打开一个新窗口并且使用vue-router跳转

### ISSUE THREAD

**Issue by estoi** [electron-vite/electron-vite-vue#474]
#### Describe the problem you confuse
作者你好，我的场景是点击一个按钮，关闭当前窗口并且打开新的窗口且跳转到某个路由。
我是一个electron初学者，希望作者大大能够解答一下。

**Comment by estoi** [comment]
@caoxiemeihao

**Comment by RSS1102** [comment]
see it : https://github.com/caoxiemeihao/electron-vite-samples/tree/main/multiple-window
