### ISSUE TITLE
printWindow.webContents.print({ silent: true })[Help] the title of help wanted report

### ISSUE THREAD

**Issue by spriteApe** [electron-vite/electron-vite-vue#475]
#### Describe the problem you confuse
使用这个架子去做一个打印功能
调用API方式为：
printWindow.webContents.print({ silent: true })
目标打印机为：
Microsoft Print to PDF 
结果：
打印出来的PDF会有缩放问题
![image](https://github.com/electron-vite/electron-vite-vue/assets/44717504/1172893a-4216-4192-b7d8-81ce41651dbd)

调用API方式改为：
 printWindow.webContents.print()
结果：
不传参打印就没问题。
![image](https://github.com/electron-vite/electron-vite-vue/assets/44717504/8aa55ee6-5431-4054-9d8a-11d10e7b9b7d)

**Comment by RSS1102** [comment]
看起来是上游electron的问题，你可以在electron内继续追踪解决方法。https://github.com/Hubertformin/electron-pos-printer/issues/113
