### ISSUE TITLE
[Bug] Missing return statement in invoke method of preload script in Electron template

### ISSUE THREAD

**Issue by bojaka2004** [electron-vite/electron-vite-vue#479]
## Issue
I am new to Electron and encountered an issue with the `invoke` method in the `preload.ts` file of a quick-start template. When I called the encapsulated `invoke` method from the renderer process, I didn't receive a response.

### Original code:
```typescript
invoke(...args: Parameters<typeof ipcRenderer.invoke>) {
  const [channel, ...omit] = args
  console.log('invoke', channel, omit);
  ipcRenderer.invoke(channel, ...omit)
}
```

However, when I added a return statement to the method, it started working as expected:

```typescript
invoke(...args: Parameters<typeof ipcRenderer.invoke>) {
  const [channel, ...omit] = args
  console.log('invoke', channel, omit);
  return ipcRenderer.invoke(channel, ...omit)
}
```

Expected Behavior
The invoke method should return a Promise, allowing the renderer process to receive the promised value from the main process.

Actual Behavior
The invoke method does not return anything, which means the renderer process is unable to receive the resolved value from the main process.

Question
Is this an oversight in the template or by design for some reason? If it's an oversight, the return statement should be included to ensure the invoke method works as intended according to the Electron documentation.

**Comment by badspider7** [comment]
This problem was already resolved yesterday🎃
please update code  #478
