### ISSUE TITLE
vite配置了base参数后，build之后找不到js文件

### ISSUE THREAD

**Issue by swift-fs** [electron-vite/electron-vite-vue#481]
项目的vite配置了base参数为`/web2d/`，开发正常，打包后在index.html引入的是`/web2d/assets/xxx.js`导致找不到文件，这个如何配置打包后也遵循配置的二级目录呀。

**Comment by swift-fs** [comment]
我可以去掉二级目录解决，但是是和web同构的，所以想尽量保持一致。

**Comment by RSS1102** [comment]
能提供一个最小复现嘛，谢谢。

**Comment by swift-fs** [comment]
在`vite.config.ts`中的配置里添加` base:'/web2d/'`，就当前`electron-vite-vue`这个项目模板build后，打开可执行文件就可以复现。如图：
![image](https://github.com/electron-vite/electron-vite-vue/assets/77133741/04d1c363-d2a2-47d6-a4a1-aba32aa77457)

通过`pnpm run dev`是可以正常跑起来的，`pnpm run build`后的setup.exe安装打开就报如图的错。

**Comment by caoxiemeihao** [comment]
Electron 打包后只识别文件路径，所以必须以 `.` 开头

```diff
- /web2d/
+ ./web2d
```

**Comment by swift-fs** [comment]
> Electron 打包后只识别文件路径，所以必须以 `.` 开头
> 
> ```diff
> - /web2d/
> + ./web2d
> ```

确实可以，非常感谢，vite文档也有写，还是要多看文档啊~~~
![image](https://github.com/electron-vite/electron-vite-vue/assets/77133741/66989307-79d2-466e-955e-3f5febbd3915)
