### ISSUE TITLE
[Bug] electron降级到22版本提示不支持require() of ES Module

### ISSUE THREAD

**Issue by nikinikinico** [electron-vite/electron-vite-vue#482]
#### Describe the bug
似乎是vite-plugin-electron插件的问题

**Comment by RSS1102** [comment]
vite-plugin-electron 好像是要在electron>=23.x.xx

**Comment by caoxiemeihao** [comment]
ELectron 从 28 开始才支持 ESM。你降级到 22 肯定会出现这种问题。
**就算你不用 Electron 用 Node.js 不支持 ESM 的版本一样会出现这个问题。**
找你的装的 npm 看看哪个入口文件是 ESM 的，要么降级 npm 包版本，要么写全 `require('module-name/xxx/xxx.js') 路径。

**Comment by nikinikinico** [comment]
我用npm create electron-vite创建的项目，再将electron降级到22版本的就没有问题。如果直接拉这个仓库的源码降到22版本就有问题。我看两个版本vite-plugin-electron的使用方式有些不一样，是不是这个原因
![image](https://github.com/electron-vite/electron-vite-vue/assets/77439774/fa0f29f2-6dd3-44dd-b895-65ed449b3e90)

**Comment by caoxiemeihao** [comment]
create-electron-vite 是最小化模板，这个项目多了好多依赖。
看你个人需求

**Comment by nikinikinico** [comment]
> create-electron-vite 是最小化模板，这个项目多了好多依赖。 看你个人需求

好的，谢谢
