### ISSUE TITLE
Not allowed to load local resource:

### ISSUE THREAD

**Issue by ohuu** [electron-vite/electron-vite-vue#95]
I'm trying to build a packaged version of my electron app but I get this error when running it.

```
Not allowed to load local resource: file:///C:/Users/Oliver/Desktop/local/resources/app.asar/dist/renderer/index.html
```

I build the package by just running `yarn build` and as you can see I'm running this on Windows. I've tried switching off webSecurity (just to see if that worked, not because I think it's a good solution) but it didn't help.

Any ideas?

**Comment by caoxiemeihao** [comment]
**First** - You can try unzip `app.asar` to `app-asar` folder.  
In your `app.asar` directory use below command. (you must be install `asar` in global environment)  
```bash
asar e app.asar app-asar
```

**Second** - You should see the following these files.  
<img width="270" alt="image" src="https://user-images.githubusercontent.com/26263658/161927831-84bc213f-b942-429a-b9d7-7ca1d2f6e293.png">
